18F/C2

config/initializers/omniauth.rb
We updated MyUSA defaults in chef. Here is the update on the C2 side.
=> Updated the MyUSA default url

app/assets/stylesheets/common/communicarts.css.scss, app/controllers/carts_controller.rb, app/views/carts/_archive_link.html.erb, app/views/carts/_cart_list.html.erb, app/views/carts/index.html.erb, spec/controllers/carts_controller_spec.rb, spec/models/cart_spec.rb
• Display a message if there are no pending or closed purchase requests
• Renamed 'Recent Purchase Requests' to 'Recently Closed Purchase Requests'
• Moved archive link into a partial
• Test Cart scopes in the model
• A bit of refactoring in carts#index to use scopes directly in the views
=> 85744742 empty recent purchases message

app/views/ncr/proposals/new.html.erb
Just a bit more obvious than the existing checkbox.
=> change Not To Exceed to a radio button

app/assets/stylesheets/communicart_mailer/email_status.css.scss, app/views/shared/_email_status.html.erb
=> [#86054712] simplify display of approvers in email status

app/decorators/cart_decorator.rb, app/models/cart_item.rb, app/views/carts/_cart.html.erb, app/views/communicart_mailer/_cart_mail.html.erb, app/views/communicart_mailer/cart_item_info.html.haml, spec/decorators/cart_decorator_spec.rb, spec/features/ncr_proposal_spec.rb, spec/integration/cart_creation_navigator_spec.rb, spec/models/cart_item_spec.rb
• Updated #total_price to consider a cart's `origin` property
• Remove custom currency helpers in favor of Rails `number_to_currency`
=> 85857380 fix total amount display

.env.example, app/mailers/communicart_mailer.rb, config/application.rb, config/initializers/env_check.rb, spec/integration/cart_creation_without_approval_group_spec.rb, spec/integration/cart_linear_approval_spec.rb, spec/integration/cart_parallel_approval_spec.rb, spec/integration/cart_rejection_spec.rb, spec/integration/comment_on_cart_item_spec.rb, spec/integration/user_ownership_of_comments.rb
=> environment variable cleanup

app/controllers/communicarts_controller.rb, app/models/approval.rb, app/views/carts/_cart.html.erb, app/views/communicarts/approval_response.html.erb, app/views/communicarts/approval_response.html.haml, spec/acceptance/cart_approval_from_link.feature, spec/factories/carts.rb, spec/steps/approval_steps.rb, spec/steps/user_steps.rb
Fixed bug that displays placeholder text instead of actual approval information
=> 86223830 fix placeholder approvals

app/controllers/communicarts_controller.rb, app/views/carts/_cart.html.erb, spec/acceptance/cart_approval_from_link.feature
The template was already handling this but the controller code wasn't updated previously to allow the comments to be shown.
=> 85707022 update no comment message

app/views/carts/_cart.html.erb
Minor style issue fix when testing [#85707022](https://www.pivotaltracker.com/story/show/85707022)
=> Fixed markup to match corresponding style

app/assets/stylesheets/common/cart_item_information.scss, app/assets/stylesheets/common/communicarts.scss, app/views/carts/_cart.html.erb, app/views/carts/_cart_item.html.erb, app/views/carts/_cart_items.html.erb, app/views/communicart_mailer/_ncr_cart.html.erb, app/views/shared/_cart_properties.html.erb
=> split up cart templates

app/controllers/comments_controller.rb, app/mailers/communicart_mailer.rb, app/models/user.rb, spec/factories/comments.rb, spec/integration/comment_on_cart_item_spec.rb, spec/mailers/communicart_mailer_spec.rb
For new carts, it's the requester, for new comments, it's the commenter, etc.
=> [#86662010] display the relevant name in the email From field

app/controllers/communicarts_controller.rb, app/views/communicarts/approval_response.html.erb
=> approval_response fixes

app/views/carts/_cart.html.erb
This code was PR'd + merged, but was clobbered in a merge shortly after. Merging this back in.
=> Restoring code that was removed from bad merge

.env.example, README.md, config/database.yml
=> Allow DB config during development

app/assets/stylesheets/common/cart_properties.scss, app/assets/stylesheets/common/communicarts.scss, app/decorators/cart_decorator.rb, app/views/carts/_cart.html.erb, app/views/shared/_cart_properties.html.erb
Thinking they should probably have less spacing, but was fighting with some conflicting styles a bit, so didn't want to spend much time on it before getting a second opition. @ericadeahl, thoughts on a quick fix for that middle section?
=> display cart properties on show page

app/models/cart.rb, app/views/shared/_cart_properties.html.erb, config/locales/en.yml, spec/features/ncr_proposal_spec.rb, spec/models/cart_spec.rb
=> 87947534: Use i18n to override field names

app/decorators/cart_decorator.rb, app/helpers/workflow_helper.rb, app/models/approval.rb, app/models/cart.rb, spec/controllers/carts_controller_spec.rb, spec/factories/carts.rb, spec/helpers/carts_helper_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/cart_spec.rb, spec/requests/cart_linear_approval_spec.rb, spec/requests/cart_parallel_approval_spec.rb, spec/requests/cart_rejection_spec.rb, spec/requests/comment_on_cart_item_spec.rb, spec/requests/user_ownership_of_comments.rb
Added a "partial_approve" event to the three state workflow and updated the Cart to use it.
Replace many chunks of code with their equivalent using a workflow.
=> ThreeStateWorkflow on cart

app/helpers/carts_helper.rb, app/models/user.rb, app/views/carts/_approval_actions.html.erb, app/views/carts/_cart.html.erb, spec/acceptance/approval_from_web_app.feature, spec/acceptance/token_expiration.feature, spec/helpers/carts_helper_spec.rb, spec/models/user_spec.rb, spec/steps/user_steps.rb
Hides approval approval actions for requesters per @cmc333333. Also included some previous feedback from @afeld.
=> 87736992 fix parallel approval display

app/models/approval.rb, app/models/cart.rb, app/models/concerns/three_state_workflow.rb, spec/decorators/cart_decorator_spec.rb
=> create a .states method in ThreeStateWorkflow

app/mailers/communicart_mailer.rb, app/views/communicart_mailer/cart_notification_email.html.erb, spec/integration/cart_linear_approval_spec.rb
Note this doesn't actually remove the underlying support...will take care of that separately.
=> [#89440756] remove instructions for replying to emails

app/assets/stylesheets/common/proposal_form.scss, app/views/ncr/proposals/form.html.erb
- Radio button top label are now in legend tags 
- Sets of radio buttons are now wrapped in fieldset
For amount fields 
- Inputs wrapped in fieldset 
- Amount is now the legend, 
for the dollar input 
- Added hidden label 'Dollar Amount'
=> Added fieldset and legend to radio buttons, fixed radio labels

app/assets/stylesheets/common/communicarts.scss, app/assets/stylesheets/common/static.scss, vendor/assets/stylesheets/webflow.scss
=> remove space around top banner

config/initializers/session_store.rb
Duration choice was completely arbitrary.
=> [#87818416] expire session after two weeks

app/views/layouts/_communicart_header.html.erb
=> add link to create a new NCR proposal

app/controllers/communicarts_controller.rb, app/models/concerns/three_state_workflow.rb, spec/controllers/communicarts_controller_spec.rb
=> Added check for double approval

.cfignore, .gitignore
https://trello.com/c/MIRccDiT/22-have-cf-automatically-ignore-files-from-the-gitignore-by-default
/cc @dlapiduz @ozzyjohnson
=> have Cloud Foundry ignore files ignored by Git

app/controllers/communicarts_controller.rb, spec/acceptance/token_expiration.feature, spec/steps/approval_steps.rb, spec/steps/user_steps.rb
This test was accidentally added to master and didn't fail because there was an undefined step. This commit will expire tokens when approving through the web app instead of an email link.
=> 88560300 expire token 1

app/controllers/communicarts_controller.rb, app/models/approval.rb, spec/acceptance/cart_approval_from_link.feature
Addresses https://www.pivotaltracker.com/story/show/90634128
=> [Delivers #90634128] Error message when approving your own cart

app/decorators/cart_decorator.rb, app/models/cart.rb, app/models/concerns/proposal_delegate.rb, app/models/proposal.rb, lib/parallel_dispatcher.rb, spec/controllers/communicarts_controller_spec.rb, spec/lib/parallel_dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/cart_spec.rb, spec/requests/user_ownership_of_comments.rb
Builds on #257.
https://github.com/18f/c2/compare/89169198_split_approvals-B...approval-simplify
=> make approval/approver terms consistent

app/assets/stylesheets/webapp/ncr.scss, app/views/ncr/work_orders/form.html.erb
https://www.pivotaltracker.com/story/show/90113244
=> Added description instruction as per Story

app/controllers/api/ncr/work_orders_controller.rb, app/models/ncr/work_order.rb, app/serializers/ncr/work_order_serializer.rb, config/routes.rb, doc/api.md, spec/factories/ncr/work_orders.rb, spec/requests/api/ncr/work_orders_spec.rb
=> various work order API improvements

config/routes.rb, spec/requests/api/ncr/work_orders_spec.rb
Per @cmc333333's comment in https://www.pivotaltracker.com/n/projects/1149728/stories/91304582.
=> [#91304582] use API_ENABLED=true specifically

app/controllers/communicarts_controller.rb
It was still producing an error in some cases where the user couldn't be found. 
Updated to check and make sure it has an approval before running through the test cases
=> Updated to be more robust

doc/overview.md
@nickbristow @brethauer @ric7694 @phirefly Does this summarize the 18F use case fairly accurately?
/cc @24thcentury
=> document 18F Operations use case

spec/requests/api/ncr/work_orders_spec.rb, spec/requests/api/users_spec.rb, spec/support/request_spec_helper.rb
...hopefully. Easier to understand [ignoring whitespace](https://github.com/18F/C2/pull/289/files?w=1).
=> fix setting and cleanup of API_ENABLED in specs

app/assets/javascripts/forms.js.coffee, app/views/ncr/work_orders/form.html.erb
Builds on #290.
https://github.com/18F/C2/compare/91100514_vendor_auto_complete...form-js-refactor
=> refactor form JS

LICENSE.md, app/assets/javascripts/forms.js.coffee
In the case of a score tie (e.g. when the page first loads), sort by the search field.
=> License for third parties. Sort auto complete

app/helpers/client_helper.rb, app/views/layouts/_communicart_header.html.erb, app/views/ncr/_header_links.html.erb, config/environments/test.rb, db/migrate/20150413201751_add_client_slug_to_users.rb, db/schema.rb, spec/features/link_to_new_proposal_spec.rb
* Adds a client field to user
* Uses it when determining whether or not to show the NCR link
Note, this performs no data migrations.
=> [Delivers #89834540] Client field on User

app/assets/stylesheets/common/communicarts.scss, app/views/layouts/application.html.erb
Curious to hear @jehlers's opinion on it, but I think it's an improvement in terms of where there eyes will be on the page.
=> [Delivers #92981132] move flash message below the header

app/views/ncr/work_orders/form.html.erb
=> [Delivers #92981276] add hints to NCR forms

app/views/ncr/work_orders/form.html.erb, spec/features/ncr_work_orders_spec.rb
For story https://www.pivotaltracker.com/story/show/93639978
=> Updated NTP emergency label

app/views/proposals/_review_status.html.erb
=> Copy-pasta failure

app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/form.html.erb
This only appears when editing a request. The link takes the user to the proposals show page.
=> Added "Discard Changes" to edit request pages"

app/views/ncr/work_orders/form.html.erb
=> [Delivers #93639962] clearer placeholder hint for select boxes

app/helpers/application_helper.rb, config/application.rb, doc/api.md, vendor/assets/stylesheets/photon/style.css
Also [finding out](https://twitter.com/aidanfeldman/status/599230880591126528) if I can submit the change to the original template.
=> fix insecure content warning on homepage

lib/tasks/import_users.rake
Not a big departure from rails console, but a bit easier to script if needed.
=> [#93640022] Add rake task for importing one user

app/assets/javascripts/filter.js.coffee, app/views/ncr/work_orders/_ba_80_fields.html.haml, app/views/ncr/work_orders/form.html.erb
Sorry for screwing this up in #368! Took re-reading the comment explaining the problem a few times for me to even understand what I did wrong :grin:
=> [Delivers #95058962] fix: show BA80 fields when BA61 is disabled

app/assets/stylesheets/common/header.scss, app/assets/stylesheets/webapp/webviews.scss
=> Added style to change color of login link

Gemfile.lock
Needed for some :sparkles: [features](https://docs.newrelic.com/docs/apm/applications-menu/monitoring/databases-slow-queries-dashboard#availablity) :sparkles:
=> upgrade New Relic gem

spec/factories/users.rb
See https://github.com/18F/C2/pull/372/files#r31368285.
/cc @annalee
=> don't call to the database when the test environment is loaded

README.md, doc/use_case_development.md
Idea came out of a loooong (ongoing) conversation in Slack:
https://18f.slack.com/archives/cap/p1431119967000254 ff.
/cc #109
=> [WIP] use case developer guide

app/decorators/proposal_decorator.rb, app/mailers/communicart_mailer.rb, config/application.rb, config/environments/production.rb, config/initializers/env_check.rb, config/initializers/mailer.rb, doc/setup.md, spec/decorators/proposal_decorator_spec.rb, spec/mailers/communicart_mailer_spec.rb
The goal is to get all emails related to a request to show up in a single thread in GMail and other mail clients.
=> [Delivers #93637304] improve email grouping

app/assets/stylesheets/common/communicarts.scss, app/assets/stylesheets/common/header.scss, app/assets/stylesheets/common/static.scss, app/assets/stylesheets/modules/request_form.scss, app/assets/stylesheets/webapp/cartlist.scss, app/assets/stylesheets/webapp/webviews.scss, app/views/gsa18f/procurements/form.html.erb, app/views/layouts/_communicart_header.html.erb, app/views/navigator/_mail_prefix.html.erb, app/views/navigator/mail_prefix.html.erb, app/views/ncr/work_orders/form.html.erb, vendor/assets/stylesheets/webflow.scss
Clicked through all(?) pages in the web app, as well as the `approval_reply_received_email`, just to make sure they all look ok.
=> clean up styles for heading elements

app/controllers/home_controller.rb, app/helpers/markdown_helper.rb, app/views/home/help.html.haml, app/views/home/help.md, app/views/layouts/_header_nav.html.erb, config/routes.rb, spec/requests/help_spec.rb
=> [Delivers #95897486] add help/FAQ page

Gemfile, Gemfile.lock, app/assets/stylesheets/webapp/ncr.scss, app/models/ncr/work_order.rb, app/views/ncr/work_orders/form.html.erb, db/migrate/20150618054349_add_direct_pay_to_work_orders.rb, db/schema.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb, vendor/assets/stylesheets/webflow.scss
=> [Delivers #96674050] add support for direct pay

Gemfile.lock, app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/form.html.erb, config/locales/en.yml, spec/features/18f_procurement_spec.rb, spec/features/ncr_work_orders_spec.rb
=> [Delivers #97035202] improve the form submit button

app/controllers/use_case_controller.rb, app/models/ncr/work_order.rb, spec/factories/ncr/work_orders.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
Paired w/ @annalee. Spec changes are easier to see [without whitespace](https://github.com/18F/C2/pull/423/files?w=1).
=> [Delivers #97560640] add validation on budget fields

app/models/ncr/work_order.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
=> [Delivers #97017456] BA60s don't get tier 1

spec/features/ncr_work_orders_spec.rb
=> Fix broken spec

app/models/ncr/work_order.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
This reverts commit f163cdf70e8e4c1016814de113afa9d0b7ef38fc.
Sorry @cmc333333. You had it right. I wasn't thinking when doing QA on this.
=> Revert "BA60s don't get tier 1"

spec/features/ncr_work_orders_spec.rb
Just to make navigating the spec file a little easier.
=> rearrange NCR feature specs to distinguish creating vs. editing

app/controllers/application_controller.rb, app/models/user.rb, spec/models/user_spec.rb
Thanks @cmc333333 for [pointing out](https://18f.slack.com/archives/cap/p1435806137002752) the bug.
=> fix checking of admin rights

app/views/help/approvers.md, app/views/help/index.html.haml, app/views/help/out_of_office.md
=> [Delivers #98375926] Move TODOs out of FAQ

app/views/home/index.html.haml, doc/overview.md
Updates per Anthony's comments
=> Updates to NCR text on home and overview

spec/features/attachment_spec.rb
It will work when run on its own, but when run with other tests,
it fails for some devs. It needs to be fixed, but it's become a
rabbit-hole and we have more critical bugs right now.
=> This is a flaky test. It's failing in some dev environments.

app/views/communicart_mailer/proposal_created_confirmation.html.erb
Thanks @jenniferthibault for pointing it out!
=> fix typo in proposal confirmation email - fixes #466

README.md, doc/overview.md, doc/production.md, script/release
Also, add a script for production deploys.
=> [Delivers #91882348] document Cloud Foundry environment information

spec/features/search_spec.rb, spec/lib/proposal_search_spec.rb
Just stumbled across this – figured we could make it more specific as a unit test.
/cc @nickbristow
=> convert searching by public_id to a unit test

app/assets/stylesheets/common/form-control.scss, app/assets/stylesheets/webapp/ncr.scss, app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/form.html.erb
=> [Delivers #97731662] add a hint that the "Org code" is the service center

app/controllers/ncr/work_orders_controller.rb, app/controllers/use_case_controller.rb, app/models/ncr/work_order.rb, spec/models/ncr/work_order_spec.rb
Hopefully made the methods a bit easier to follow.
=> refactor approver updating

app/models/ncr/work_order.rb, spec/features/ncr_work_orders_spec.rb
Just adding specs to ensure that it works as expected. My guess is this was fixed by #479.
=> [Delivers #99132706] verify that changing org code to WHSC assigns approvals properly

spec/features/ncr_work_orders_spec.rb
=> fix flaky spec

doc/production.md, script/deploy, script/release
=> [WIP] [Delivers #96622322] add zero-downtime deployment script

app/views/proposals/archive.html.erb, spec/controllers/proposals_controller_spec.rb
Appear in #506, resolved in #514, but should be merged sooner.
=> Hotfix for template typo

app/views/report_mailer/budget_status.text.erb
• Adds CL number to the report
• Prepends asterisks to requests that are greater than 5 days old
===
Conflicts:
app/views/report_mailer/budget_status.text.erb
=> Added CL output and tag if the pending request is older than 5 days

app/controllers/proposals_controller.rb, app/policies/proposal_policy.rb, spec/policies/proposal_policy_spec.rb
Easier to understand [ignoring whitespace](https://github.com/18F/C2/pull/526/files?w=1).
=> refactor specs around admin scopes

doc/setup.md
Has been moved to [`production.md`](https://github.com/18F/C2/blob/master/doc/production.md#deploying).
=> remove out-of-date deployment information

app/models/concerns/proposal_delegate.rb, app/models/proposal.rb, spec/controllers/proposals_controller_spec.rb, spec/models/proposal_spec.rb, spec/policies/proposal_policy_spec.rb, spec/support/models.rb
=> validate the client_data_type on the Proposal

app/controllers/observations_controller.rb, app/controllers/proposals_controller.rb, spec/features/observer_spec.rb
We might want to tighten this up a bit down the road, but I think it's fine for now.
=> [Delivers #100955526] allow anyone who can see the Proposal to add other observers

app/views/proposals/show.html.haml, spec/features/observer_spec.rb
The UI change to accompany #546. Should fix the `master` build.
=> allow everyone who can see the proposal to add observers

app/controllers/application_controller.rb, app/controllers/observations_controller.rb, app/policies/observation_policy.rb, app/policies/proposal_policy.rb, app/views/proposals/show.html.haml, lib/policy_finder.rb
Centralizes the authorization logic around adding/removing observers.
=> create an ObservationPolicy class

doc/overview.md
Noticed while going through it with @yozlet.
=> make a few updates to the Technical Overview page

Procfile, config/clock.rb, manifest.yml
=> tweak deployment configuration

app/helpers/value_helper.rb, app/views/proposals/show.html.erb, app/views/shared/formatter/_date.html.haml, spec/helpers/value_helper_spec.rb
In reference to https://www.pivotaltracker.com/n/projects/1149728/stories/93639992.
=> Relative proposal times

README.md, doc/developer_onboarding.md, doc/use_case_development.md
Organized the documentation links in the README, as well.
=> make the onboarding page a checklist

doc/developer_onboarding.md
Also, make links absolute so they work when copied over to GitHub Issues.
=> more links from the onboarding doc

doc/overview.md
Let's continue the discussion on browser support here. Again, not sure how relevant it is for you guys since I don't know the details of your contracts etc., but typically it's nice to have a written policy on these things before it's too late and you get roped into supporting older stuff, or newer stuff that just acts funky like iPads.
=> adding browser support table

db/migrate/20150831193037_move_observations_to_roles.rb
100427542 - migration bug due to orphaned FK records and dupes.
=> try to avoid sql constraint errors

app/views/report_mailer/budget_status.text.erb, lib/ncr/reporter.rb, spec/mailers/report_mailer_spec.rb
=> [Delivers #102956040] fix budget report

doc/developer_onboarding.md
@annalee @yozlet Mind confirming that these steps are accurate, if you haven't been getting build notifications by email?
=> [Delivers #102941602] tell new devs to subscribe to build notifications

lib/mail_preview.rb
@phirefly You can access at http://localhost:3000/mail_view/budget_status.
=> add preview endpoint for budget report email

.rubocop.yml, lib/ncr_dispatcher.rb, spec/lib/ncr_dispatcher_spec.rb
story: https://www.pivotaltracker.com/story/show/100957216
filter out any approver from email notification if they are the user modifying a request.
=> [Delivers #100957216] do not email approver if they modify a request

Gemfile, Gemfile.lock, app/controllers/gsa18f/dashboard_controller.rb, app/controllers/ncr/dashboard_controller.rb, app/helpers/proposals_helper.rb, app/helpers/value_helper.rb, spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/controllers/ncr/dashboard_controller_spec.rb, spec/controllers/proposals_controller_spec.rb, spec/features/18f_procurement_spec.rb, spec/helpers/proposals_helper_spec.rb, spec/helpers/value_helper_spec.rb, spec/spec_helper.rb
story: https://www.pivotaltracker.com/story/show/103020810
Seems to be a regression from earlier timezone work. Adds Zonebie gem to randomize timezone on every rspec run, and fixes test that assumed ET.
=> [Delivers #103020810] randomize timezone in tests, fix failing test that assumed ET

doc/developer_onboarding.md
Added tasks related to support emails into the developer onboarding section
=> Added information for adding a new member to support emails

app/mailers/feedback_mailer.rb, spec/controllers/feedback_controller_spec.rb
=> [Delivers #103357204] Feedback emails cc the feedback writer

README.md, doc/team_practices.md
this needs some love wrt process, and likely eyeballs from multiple team members. I've started with what I know and added TODO placeholders for things I'm unsure about.
=> [Delivers #102625902] start on team best practices

manifest.yml, script/prod_start, script/server_start
Just makes it a bit easier to follow and add inline comments to.
=> create a standalone script for starting the application in production

app/models/user.rb, spec/models/user_spec.rb
A couple things I noticed while reviewing #602.
=> simplify role methods on User

app/models/user.rb, spec/models/user_spec.rb
=> consoliate queries for users with a particular role

app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/form.html.erb, app/views/shared/_form_submit_button.html.erb, config/initializers/mailer.rb, spec/features/ncr_work_orders_spec.rb, spec/rails_helper.rb, spec/support/environment_spec_helper.rb
Story: https://www.pivotaltracker.com/story/show/98729742
=> [Delivers #98729742] prefix sandbox emails

.rubocop.yml
c.f. https://github.com/bbatsov/ruby-style-guide/issues/273
=> turn off TrailingComma check

spec/mailers/communicart_mailer_spec.rb, spec/steps/approval_steps.rb, spec/support/environment_spec_helper.rb, spec/support/features.rb
Also fixing Rubocop failures in the support file.
=> use with_env_var(s) throughout specs

app/controllers/proposals_controller.rb, app/models/proposal.rb, app/views/proposals/index.html.erb, lib/query/proposal/listing.rb, lib/tabular_data/container.rb, spec/controllers/proposals_controller_spec.rb, spec/features/pending_proposals_spec.rb
Story: https://www.pivotaltracker.com/story/show/99618664
* adds filter to TabularData::Container and uses it to separate pending proposals that need review by the current_user from those that do not.
* add 4th table to /proposals with Needing Review
Supercedes #616
=> [Delivers #99618664] pending proposals needing review

app/controllers/concerns/token_auth.rb, app/models/api_token.rb, app/models/approvals/individual.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/report_mailer/budget_status.text.erb, lib/populator.rb, spec/mailers/communicart_mailer_spec.rb
=> [Delivers #633] Time.zone.now

app/models/approver_comment.rb, app/models/observation.rb, app/models/proposal.rb, app/models/proposal_role.rb, app/models/user_role.rb
[Relevant PT story](https://www.pivotaltracker.com/story/show/102723774).
=> Model validations

app/mailers/concerns/conversation_threading.rb, app/mailers/concerns/proposal_conversation_threading.rb, app/mailers/feedback_mailer.rb, spec/mailers/feedback_mailer_spec.rb
This may or may not still be relevant after #641 is in.
=> [Delivers #103944538] ensure each new feedback email is in its own thread

app/models/ncr/work_order.rb, spec/models/ncr/work_order_spec.rb
After testing on staging, I'm still getting the same output as previous. I think we need to check for 'actionable'
=> Updated #current_approver_email_address 

CONTRIBUTING.md
* Also link to setup docs
* https://www.pivotaltracker.com/story/show/104755446
=> Add code of conduct to CONRTIBUTING.md

db/migrate/20150921183423_add_db_constraints.rb
* zap proposal_role rows pointing at non-existent users
* clean up duplicate role records
=> [Delivers #102764816] db data cleanup for constraints

CONTRIBUTING.md
Credit for the idea to @jessieay in https://github.com/18F/C2/pull/653#issuecomment-145537396.
=> link from CONTRIBUTING to the team practices doc

manifest.yml
Came across a few that were set manually which aren't sensitive.
=> move additional environment variables to manifest

spec/factories/proposals.rb, spec/features/proposal_show_spec.rb, spec/features/proposals/history_spec.rb, spec/requests/proposals_spec.rb
* Can check that one off the to do list!
=> Create delegate transient attribute

app/models/ncr/work_order.rb, spec/models/ncr/work_order_spec.rb
This is some tidying up based on comments on #650 after it was merged.
=> Comment cleanup

doc/setup.md, lib/populator.rb, lib/tasks/populate.rake, spec/lib/populator_spec.rb
* Fixes https://www.pivotaltracker.com/story/show/104924964
=> [Delivers #104924964] Update/document rake task for populating dashboard

spec/features/active_admin_spec.rb, spec/features/cancel_spec.rb, spec/features/version_check_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/support/feature_spec_helper.rb
* Did an `rspec` profile and edited the 3 slowest specs
* Made single quotes more consistent while I was there
* Replaced a "sleep" with Timecop
* Inlined `let` statements since those can get hairy
=> Speed up 3 slowest specs

app/policies/concerns/gsa_policy.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/controllers/proposals_controller_spec.rb, spec/factories/users.rb, spec/features/18f_procurement_spec.rb, spec/features/active_admin_spec.rb, spec/features/attachment_spec.rb, spec/features/cancel_spec.rb, spec/features/linear_approvals_spec.rb, spec/features/ncr_work_orders_spec.rb, spec/features/parallel_approvals_spec.rb, spec/features/roles_conversion_spec.rb, spec/features/tabular_data_spec.rb, spec/helpers/ncr/work_orders_helper_spec.rb, spec/lib/csv_user_importer_spec.rb, spec/lib/dispatcher_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/lib/ncr_dispatcher_spec.rb, spec/lib/populator_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/mailers/feedback_mailer_spec.rb, spec/mailers/report_mailer_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/user_spec.rb, spec/policies/gsa18f/procurement_policy_spec.rb, spec/policies/ncr/work_order_policy_spec.rb, spec/requests/set_user_after_login_spec.rb, spec/support/environment_spec_helper.rb
* https://www.advomatic.com/blog/what-to-use-for-test-email-addresses
=> [Delivers #105569568] Use `example.com` for all test email addresses

app/models/proposal.rb, db/migrate/20151013224625_add_default_flow_to_proposals.rb, db/schema.rb
* Let's try to avoid callbacks!
* http://samuelmullen.com/2013/05/the-problem-with-rails-callbacks/
=> Replace callback with DB default

Rakefile, doc/setup.md
* Running `rake` runs test suite
=> [Delivers #105695746] Add default `rake` task

lib/ncr/reporter.rb
I had some local changes pending when @afeld closed this case last week, this is the actual code that was used to create the report, which includes an Id column.
=> adding public_id field to annual report

doc/production.md
* Afeld is now an admin woot woot!
=> [Delivers #104760642] Update Mailchimp setup instructions

app/controllers/application_controller.rb, app/models/user.rb, spec/factories/users.rb, spec/features/active_admin_spec.rb, spec/models/user_spec.rb
* Was returning a 500 because we weren't checking for a current user
before doing admin role check
=> [Delivers #105128776] Return 401 with logged out user visits '/admin'

Gemfile, Gemfile.lock, spec/support/features.rb
Doesn't take out quite as much of our support code as I was hoping it would, but ah well.
=> [Delivers #105137620] use Climate Control gem for setting environment variables in specs

app/mailers/feedback_mailer.rb, spec/mailers/feedback_mailer_spec.rb
Story: https://www.pivotaltracker.com/story/show/106119314
=> [Delivers #106119314] set explicit Reply-To for feedback email to override our default

app/controllers/ncr/work_orders_controller.rb
Per suggestion in https://github.com/18F/C2/pull/656/files#r42406827.
/cc @jessieay
=> minor refactor to named method in WorkOrdersController

lib/incoming_mail/handler.rb, spec/features/incoming_mail_handler_spec.rb
Story: https://www.pivotaltracker.com/story/show/106110788
Email was not being triggered for new comments.
=> [Delivers #106110788] manually trigger email for new comment

lib/incoming_mail/handler.rb, spec/features/incoming_mail_handler_spec.rb
refactor test for clarity, fix regression where replying via email did not generate email to subscribers
=> fix email send regression

app/models/proposal.rb, db/seeds.rb, lib/roles_conversion.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/roles_conversion_spec.rb, spec/helpers/ncr/work_orders_helper_spec.rb, spec/lib/csv_user_importer_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/api/users_spec.rb, spec/requests/set_user_after_login_spec.rb
* Mirrors production data more closely
* Add spec that ensures removed approvers are notified
* Story: https://www.pivotaltracker.com/story/show/98774038
=> [Delivers 98774038] Create one seed user for each approver type

spec/controllers/ncr/work_orders_controller_spec.rb, spec/features/ncr/work_orders/approver_edit_spec.rb, spec/features/roles_conversion_spec.rb, spec/helpers/ncr/work_orders_helper_spec.rb, spec/lib/csv_user_importer_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/api/users_spec.rb, spec/requests/set_user_after_login_spec.rb, spec/support/proposal_spec_helper.rb
Extracted from #660. See commits.
=> various spec cleanup

app/mailers/report_mailer.rb, lib/ncr/reporter.rb, spec/lib/ncr/reporter_spec.rb
* Story: https://www.pivotaltracker.com/story/show/105300436
=> [Delivers #105300436] Add test for annual report mailer

app/controllers/ncr/work_orders_controller.rb, app/controllers/use_case_controller.rb, app/models/ncr/work_order.rb, app/views/ncr/work_orders/form.html.haml, config/locales/simple_form.en.yml, spec/controllers/ncr/work_orders_controller_spec.rb, spec/factories/ncr/work_orders.rb, spec/features/ncr/work_orders/approve_spec.rb, spec/features/ncr/work_orders/comment_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/ncr/work_orders/show_spec.rb, spec/features/requester_switches_work_order_to_whsc_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/models/ncr/work_order_spec.rb
Builds/depends on #656. The diff:
https://github.com/18f/c2/compare/96851664-simplify-forms...96851664-simplify-forms-B
=> refactor WorkOrder model/controller to use an attribute for the approving official email

doc/production.md
* Story: https://www.pivotaltracker.com/story/show/104760686
=> [Delivers #104760686] Update CF docs

app/models/proposal.rb, config/application.rb, lib/incoming_mail/handler.rb, lib/services/inbound_mail_parser.rb, lib/services/observation_creator.rb, spec/features/incoming_mail_handler_spec.rb, spec/lib/services/observation_creator_spec.rb, spec/models/proposal_spec.rb
* Branch off of https://github.com/18F/C2/pull/724
* Also add service class to capture duplicate logic in `Proposal`
=> Add service classes to encapsulate mail handler logic

Gemfile, Gemfile.lock, app/controllers/concerns/token_auth.rb, app/mailers/communicart_mailer.rb, app/models/api_token.rb, app/policies/api_token_policy.rb, db/migrate/20151027010707_add_unique_index_to_api_token_access_token.rb, db/schema.rb, spec/controllers/proposals_controller_spec.rb, spec/factories/api_tokens.rb, spec/helpers/communicart_mailer_helper_spec.rb, spec/lib/ncr_dispatcher_spec.rb, spec/models/api_token_spec.rb, spec/models/approval_spec.rb, spec/models/proposal_spec.rb, spec/policies/api_token_policy_spec.rb, spec/rails_helper.rb, spec/requests/proposals_spec.rb, spec/support/shoulda_matchers.rb, spec/views/communicart_mailer/_email_reply.html.erb_spec.rb
* Add validations for expired_at and access_token
* Use `has_secure_token`, which will be part of Rails 5
* Add uniqueness validation for access_token
* Add unique index for access_token
* Add specs for untested methods
* Refactor ApiToken policy
=> Address "todos" for ApiToken

spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/controllers/ncr/dashboard_controller_spec.rb, spec/features/attachment_spec.rb, spec/requests/api/ncr/work_orders_spec.rb, spec/requests/api/users_spec.rb
* Converted to stories where appropriate
https://www.pivotaltracker.com/story/show/106791668
https://www.pivotaltracker.com/story/show/106791568
https://www.pivotaltracker.com/story/show/106791460
* Removed two pending specs with ambiguous meaning
* Fixes failing spec with pending status
=> Pending specs -> Tracker stories

app/models/ncr/work_order.rb, lib/roles_conversion.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/lib/roles_conversion_spec.rb, spec/rails_helper.rb
* Speeds up test suite from 3 mins, 30 seconds to 2 mins 20 seconds
=> Do not run seeds before each test run

app/views/gsa18f/procurements/form.html.haml, app/views/ncr/work_orders/_ba_80_fields.html.haml, app/views/ncr/work_orders/form.html.haml
Also Removed asterisk from the Work Orde field since it is not required
=> [Delivers #99713258] Indicate significance of asterisk in form. 

app/controllers/comments_controller.rb, app/controllers/concerns/token_auth.rb, app/controllers/observations_controller.rb, app/controllers/use_case_controller.rb, app/models/concerns/proposal_delegate.rb, app/models/proposal.rb, app/models/user.rb, app/views/communicarts/authorization_error.html.haml, doc/authorization.md, spec/controllers/comments_controller_spec.rb, spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/controllers/observations_controller_spec.rb, spec/controllers/proposals_controller_spec.rb, spec/factories/gsa18f/procurements.rb, spec/features/client_slug_authz_spec.rb, spec/features/tabular_data_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/user_spec.rb, spec/requests/proposals_spec.rb
Story: https://www.pivotaltracker.com/story/show/98149712
Implements documentation, tests and fixes for authorization audit, notably:
* responds with 403 and authorization error message rather than redirecting with flash message
* articulates authorization roles and rules for pending ATO application
=> [Delivers #98149712] authorization audit

app/views/default/_proposal_mail.html.erb
* Just following instructions!
=> Remove GSA Advantage references

spec/factories/approvals.rb, spec/factories/ncr/work_orders.rb, spec/features/requester_switches_work_order_to_whsc_spec.rb, spec/models/approval_spec.rb, spec/models/ncr/work_order_spec.rb
=> [Refactor] Add Factory for BA80 Ncr::WorkOrder

app/controllers/proposals_controller.rb, app/controllers/use_case_controller.rb, app/decorators/proposal_decorator.rb, app/mailers/concerns/proposal_conversation_threading.rb, app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/communicart_mailer/approval_reply_received_email.html.haml, app/views/communicart_mailer/approval_reply_received_email.text.erb, app/views/communicart_mailer/comment_added_email.html.haml, app/views/communicart_mailer/comment_added_email.text.erb, app/views/proposals/show.html.haml, config/locales/en.yml, lib/services/client_data_creator.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/factories/gsa18f/procurements.rb, spec/factories/ncr/work_orders.rb, spec/factories/proposals.rb, spec/features/ncr/work_orders/approve_spec.rb, spec/features/proposals/listing_spec.rb, spec/features/search_spec.rb, spec/features/tabular_data_spec.rb, spec/lib/services/client_data_creator_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/proposal_spec.rb
* Add public_id in class rather than callback
* Story: https://www.pivotaltracker.com/story/show/98376564
This is a refactor so QA should be that creating a new NCR Work order works as expected
=> Add service class for proposal creation

app/views/proposals/index.html.erb
A small HTML nit: fix the empty list DOM structure to be consistent for all tables.
=> fix DOM structure where then are zero completed proposals

app/models/ncr/work_order.rb, lib/roles_conversion.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/roles_conversion_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/rails_helper.rb
Reverts 18F/C2#746
This works great on a clean db, but on an existing db, we need to look up the User with the appropriate role, not rely on the env vars.
=> Revert "Do not run seeds before each test run"

app/controllers/auth_controller.rb
Just a minor refactoring, removing things that are no longer used.
=> clean up AuthController

app/controllers/proposals_controller.rb, app/views/proposals/show.html.haml
* Remove unused vars
* Do not use `self` for instance methods
* Create story for TODO https://www.pivotaltracker.com/story/show/107765772
=> Small ProposalsController refactors

lib/role_picker.rb
* Fixes https://rpm.newrelic.com/accounts/921394/applications/5480870/traced_errors/a28401-527aa035-87db-11e5-a540-f8bc12425498
=> client -> client_slug in RolePicker

lib/role_picker.rb, lib/subscriber_list.rb, spec/lib/role_picker_spec.rb, spec/lib/subscriber_list_spec.rb
* Follow up to https://github.com/18F/C2/pull/786
=> Add specs for RolePicker

app/controllers/ncr/work_orders_controller.rb
Just a minor refactor to make it more clear.
=> create a #work_order method for use in that controller

app/models/concerns/proposal_delegate.rb, app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, lib/dispatcher.rb, lib/populator.rb, lib/subscriber_list.rb, spec/lib/dispatcher_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/proposal_spec.rb, spec/support/shared_examples/client_data.rb
* Shared examples have tests for shared behavior that was previously mostly untested
=> Add shared example for client data objects

.env.example, app/models/gsa18f/procurement.rb, db/seeds.rb, doc/envvars.md, lib/roles_conversion.rb, spec/features/18f_procurement_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/rails_helper.rb, spec/support/environment_spec_helper.rb
Story: https://www.pivotaltracker.com/story/show/108022488
No functional change, just switches from environment variables to roles, similar to what we did with NCR a month+ ago.
=> Delivers #108022488] gsa18f roles

app/models/user.rb, db/migrate/20150901141746_move_client_admin_role.rb, db/migrate/20150901190853_move_admin_env_var_to_role.rb, lib/roles_conversion.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/lib/populator_spec.rb, spec/models/user_spec.rb
* Always excpect arg type to be string rather than object
* Increased flexibility also created increased complexity / confusion
* Move class methods above instance methods
=> Small refactors to User class

app/models/proposal.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/proposal_spec.rb, spec/policies/ncr/work_order_policy_spec.rb, spec/services/proposal_update_recorder_spec.rb
* Refactor method to take email address as arg rather than email OR obj
=> Proposal#add_observer takes string as argument

app/admin/proposal.rb, spec/features/admin_spec.rb
* To test:
visit admin
click on proposals
view-only options should be present (no edit/delete/create)
=> Dev admin can view proposals

app/controllers/gsa18f/procurements_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, config/data/ncr/ool_org_codes.yml, lib/ncr/organization.rb, lib/ncr/reporter.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/factories/ncr/work_orders.rb, spec/features/client_slug_authz_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/proposals/listing_spec.rb, spec/features/requester_switches_work_order_to_whsc_spec.rb, spec/lib/ncr/organization_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/proposal_spec.rb
* Was using `name` attr which is not an actual db attr for either obj
=> Clean up params methods for client data objs

doc/production.md, manifest.yml
Story: https://www.pivotaltracker.com/story/show/98196566
Contact me for credentials.
=> [Delivers #98196566] ELK logging

spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/features/18f_procurement_spec.rb, spec/features/ncr/work_orders/approver_edit_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/edit_spec.rb, spec/features/ncr/work_orders/post_approval_modification_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/proposals/listing_spec.rb, spec/features/requester_switches_work_order_to_whsc_spec.rb, spec/features/sandbox_warning_spec.rb, spec/lib/query/proposal/search_spec.rb, spec/rails_helper.rb, spec/support/environment_spec_helper.rb
=> Disable sandbox warning in test env

app/views/shared/_table.html.haml, lib/expired_record_cleaner.rb
Story: https://www.pivotaltracker.com/story/show/108578654
=> [Delivers #108578654] fix Hakiri XSS warning

lib/roles_conversion.rb, spec/lib/roles_conversion_spec.rb
`db:seed` cannot run in production until this is fixed.
=> add tests for RolesConversion

app/admin/user.rb
=> add proposals panel to /admin/users/:id page

app/controllers/application_controller.rb, app/controllers/feedback_controller.rb, app/models/user.rb, app/views/home/index.html.haml, config/routes.rb, spec/features/feedback_spec.rb, spec/features/login_spec.rb, spec/models/user_spec.rb, spec/requests/proposals_spec.rb
* Redirect inactivated users to root path with flash message
* Flash message contains link but that is currently not working
* Story: https://www.pivotaltracker.com/story/show/106953324
=> [Delivers #106953324] Do not allow inactivated users to log in

app/views/default/_proposal_properties.html.erb
Story: https://www.pivotaltracker.com/story/show/108898896
=> [Delivers #108898896] zap FY15 in favor of year-less title

app/assets/javascripts/ncr_work_orders.js, app/models/ncr/work_order.rb, app/views/ncr/work_orders/_form.html.haml, db/schema.rb, spec/features/ncr/work_orders/create_spec.rb, spec/models/ncr/work_order_spec.rb
Story: https://www.pivotaltracker.com/story/show/108595344
=> [Delivers #108595344] ba60 building optional

app/views/gsa18f/dashboard/index.html.haml, app/views/ncr/dashboard/index.html.haml
=> pretty up the dashboard with built-in bootstrap styles

app/models/ncr/work_order.rb, app/views/ncr/work_orders/_form.html.haml
A couple small changes to fix display of NCR Organization on modify form and show pages.
=> Jy 108795040 ncr organizations table b

doc/data_retention.md
Story: https://www.pivotaltracker.com/story/show/106870524
Documentation only.
See also https://github.com/18F/DevOps/issues/512
=> [Delivers #106870524] add data retention policy per GSA audit guide

.codeclimate.yml
* List of engines: http://docs.codeclimate.com/article/296-engines-available-engines
=> Add more code climate checks

Gemfile, app/admin/dashboard.rb, app/admin/job.rb, app/admin/role.rb, app/admin/user.rb
* Small style changes re: code climate feedback
=> Single -> Double quotes in Gemfile

app/models/proposal.rb, app/models/step.rb, app/models/steps/individual.rb, spec/factories/api_tokens.rb, spec/factories/steps.rb, spec/models/proposal_spec.rb, spec/models/step_spec.rb, spec/models/steps/individual_spec.rb
* `where` does not work on steps
* see docs at http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-find
=> Root step is first step

Gemfile.lock
Per https://groups.google.com/forum/#!topic/ruby-security-ann/aSbgDiwb24s.
=> upgrade Nokogiri

app/views/proposals/index.html.erb, spec/features/proposals/index_spec.rb, spec/features/proposals/sort_index_spec.rb, spec/support/proposal_table_spec_helper.rb
* For https://trello.com/c/XM2HDJ32
=> Hide "needs review" section when no proposals need review

app/controllers/gsa18f/dashboard_controller.rb, app/controllers/ncr/dashboard_controller.rb, app/decorators/client_data_collection_decorator.rb, app/queries/gsa18f_dashboard_query.rb, app/queries/ncr_dashboard_query.rb, spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/controllers/ncr/dashboard_controller_spec.rb, spec/decorators/client_data_collection_decorator_spec.rb, spec/queries/gsa18_dashboard_query_spec.rb, spec/queries/ncr_dashboard_query_spec.rb
* Use query objects and decorators instead of controller methods
* This should help us generalize in the future
=> Clean up duplicate logic in Dashboard controllers

lib/query/proposal/listing.rb, lib/query/proposal/versions.rb, lib/tabular_data/container.rb, lib/tabular_data/container_config.rb, spec/lib/tabular_data/container_config_spec.rb, spec/lib/tabular_data/container_spec.rb, spec/support/fixtures/container_config.yml
* Move `config_for_client` method into its own class
=> Small Tabular Data refactors

Gemfile, Gemfile.lock
also see https://github.com/rubygems/rubygems.org/issues/644#issuecomment-33130622 for hardcoded alternate mirror list
=> rubygems.org giving SSL errors -- try this mirror instead

.about.yml
Updating the services entry to match the services listed in your README.
=> Correcting and extending about.yml services entry

spec/lib/ncr/reporter_spec.rb
=> add tests for NCR::WorkOrder step workflow and CSV reporting

README.md, doc/developer_onboarding.md, doc/overview.md
I updated a 404 link to a working one. 
Assuming the link I changed is correct.
=> Updating dead link

doc/developer_onboarding.md
Opening this up with recent changes to onboarding tasks. May be adding more in the next day or so.
=> Updates to onboarding list

app/views/default/email_header/_approvals_complete.html.haml, spec/mailers/mailer_spec.rb
Trello: https://trello.com/c/6cqZ3aHm
=> if final step is_a Purchase, use different text in email

app/assets/javascripts/selectizer.js.coffee, app/helpers/ncr/work_orders_helper.rb, app/mailers/concerns/proposal_conversation_threading.rb, app/models/ncr/work_order.rb, app/serializers/ncr/work_order_serializer.rb, app/services/proposal_update_recorder.rb, app/views/ncr/work_orders/_form.html.haml, config/locales/en.yml, config/locales/simple_form.en.yml, db/migrate/20160201194548_ncr_organizations_string_to_relation.rb, db/schema.rb, lib/ncr/reporter.rb, spec/features/ncr/work_orders/change_work_oder_to_whsc_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/helpers/ncr/work_orders_helper_spec.rb, spec/lib/ncr/approval_manager_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/mailers/concerns/proposal_conversation_threading_spec.rb, spec/models/ncr/organization_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/api/ncr/work_orders_spec.rb, spec/support/feature_spec_helper.rb
* Use foreign key instead of string
* https://trello.com/c/HRGz6lNP/58-make-ncr-organization-use-a-real-foreign-key
=> NCR Work Order associated with NCR Organization

app/views/layouts/_c2_header.html.erb
Trello: https://trello.com/c/BqUkShEV
=> try to avoid NR template error

app/controllers/gsa18f/procurements_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/models/gsa18f/procurement.rb, app/models/gsa18f/procurement_fields.rb, app/models/ncr/work_order.rb, app/models/ncr/work_order_fields.rb, doc/use_case_development.md, spec/models/gsa18f/procurement_fields_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/ncr/work_order_fields_spec.rb, spec/models/ncr/work_order_spec.rb
* Client data fields were confusing and lightly tested
=> Extract classes for Client Data fields

doc/client_setup.md
Trello: https://trello.com/c/i4Koni9u
The example code is based on the `Test::ClientRequest` code in `spec/`. NOTE this example code hasn't been tested. I would expect that anyone adding a new client would amend this document based on real-world experience. This is intended as a starting place.
=> add document describing setup for a new client

README.md
=> Add information about demos in the README

db/chores/proposal_cleaner.rb, spec/db/chores/proposal_cleaner_spec.rb
* To prevent migration issue https://github.com/18F/C2/pull/937#issuecomment-183009980
=> Add class to remove proposals without client data

.rubocop.yml
=> zapping obsoleted rubocop rule

app/decorators/proposal_decorator.rb, app/helpers/mailer_helper.rb, app/helpers/value_helper.rb, app/mailers/mailer.rb, app/views/comment_mailer/comment_added_email.html.haml, app/views/comment_mailer/comment_added_email.text.erb, app/views/default/email_header/_approvals_complete.html.haml, app/views/layouts/mailer.html.erb, app/views/mailer/approval_reply_received_email.html.haml, app/views/mailer/approval_reply_received_email.text.erb, config/locales/mailers/en.yml, spec/mailers/comment_mailer_spec.rb, spec/mailers/mailer_spec.rb
* https://trello.com/c/xvL5TN7d
=> Move even more emails to I18n

db/migrate/20160222185247_convert_gsa18_f_to_text.rb, db/schema.rb
Trello: https://trello.com/c/xC3qGgZL/138-gsa18f-procurements-limited-to-255-chars
=> do not limit text fields to 255 chars

manifest.yml
prep for production release of master tonight
=> c2-prod-elasticsearch is now provisioned

doc/cloud_foundry_setup.md, doc/developer_onboarding.md
=> Add docs on setting on a dev env per-developer

lib/mail_previews/mailer_preview.rb
* Email now lives in ProposalMailer
=> Remove stale email preview

app/controllers/concerns/token_auth.rb
=> [Refactor] Small updates to token auth controller

app/helpers/mailer_helper.rb, app/mailers/approval_mailer.rb, app/mailers/proposal_mailer.rb, app/models/dispatcher.rb, app/views/approval_mailer/approval_reply_received_email.html.haml, app/views/approval_mailer/approval_reply_received_email.text.erb, app/views/approval_mailer/approver_removed.html.haml, app/views/approval_mailer/approver_removed.text.erb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/cancellation_mailer/cancellation_notification.html.haml, app/views/comment_mailer/comment_added_notification.html.haml, app/views/layouts/basic.html.erb, app/views/mail_shared/email_header/_removed.html.haml, app/views/proposal_mailer/emergency_proposal_created_confirmation.html.haml, app/views/proposal_mailer/proposal_created_confirmation.html.haml, config/locales/mailers/en.yml, lib/mail_previews/approval_mailer_preview.rb, spec/mailers/approval_mailer_spec.rb, spec/mailers/mailer_spec.rb
* https://trello.com/c/uWQFAloH/135-email-conversion-removal-as-approver
=> Update styles for "approver removed" email

app/mailers/mailer.rb, lib/mail_previews/mailer_preview.rb
* Was moved to ObserverMailer previously
=> Remove unused `proposal_observer_email` method

spec/features/return_to_spec.rb
see e.g. https://circleci.com/gh/18F/C2/3934
=> wrap actions that touch the ES server in es_execute_with_retries

app/models/concerns/client_data_mixin.rb, app/models/concerns/step_manager.rb, app/models/proposal.rb, app/queries/proposal_query.rb, spec/models/proposal_spec.rb, spec/queries/proposal_query_spec.rb, spec/support/shared_examples/client_data.rb
* As we move toward polymorphic, these will no longer work (can't do
polymoporphic has_many through)
* Part of https://trello.com/c/hHfzNgSu
=> Remove `has_many through: :user` relations on Proposal

app/controllers/auth_controller.rb, app/mailers/welcome_mailer.rb, app/views/welcome_mailer/welcome_notification.html.haml, app/views/welcome_mailer/welcome_notification.text.erb, config/locales/mailers/en.yml, lib/mail_previews/welcome_mailer_preview.rb, spec/features/cancel_spec.rb, spec/features/comment_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/proposals/approve_spec.rb, spec/mailers/welcome_mailer_spec.rb, spec/requests/set_user_after_login_spec.rb
Trello: https://trello.com/c/HvrtBUy8
=> Welcome mailer

app/mailers/proposal_mailer.rb, app/models/dispatcher.rb, app/models/ncr_dispatcher.rb, app/models/null_user.rb, app/services/ncr/work_order_updater.rb, app/views/mail_shared/email_header/_already_approved.html.haml, app/views/proposal_mailer/proposal_updated_step_complete.html.haml, app/views/proposal_mailer/proposal_updated_step_complete.text.erb, app/views/proposal_mailer/proposal_updated_step_complete_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_step_complete_needs_re_review.text.erb, config/locales/mailers/en.yml, lib/mail_previews/proposal_mailer_preview.rb, spec/mailers/mailer_spec.rb, spec/mailers/proposal_mailer_spec.rb, spec/models/ncr_dispatcher_spec.rb
* one template for steps that need to be re-reviewed, one for steps
that do not
* re-reviewed: https://trello.com/c/jWfjbfxD
* not re-reviewed: https://trello.com/c/jWfjbfxD
Needs re review:
Does not need re-review:
=> Create email templates for emails to step users after step complete

doc/setup.md
At last. https://trello.com/c/p9dKEhQb/32-expand-myusa-setup-instructions
I think this covers the problems that were had in the past.
=> Myusa doc update

app/models/concerns/client_data_mixin.rb, app/models/ncr/organization.rb, app/models/user.rb, spec/controllers/proposals_controller_spec.rb, spec/factories/test/client_request.rb, spec/models/ncr/organization_spec.rb, spec/models/test/client_request_spec.rb, spec/models/user_spec.rb, spec/support/fixtures/test_models.rb
trello: https://trello.com/c/UctuAOdM
This change should stringify associations in CSV download, rather than just printing the foreign key id.
=> Approving official download

app/mailers/observer_mailer.rb, app/models/dispatcher.rb, app/models/ncr_dispatcher.rb, app/views/observer_mailer/proposal_complete.html.haml, app/views/observer_mailer/proposal_complete.text.erb, config/locales/mailers/en.yml, lib/mail_previews/observer_mailer_preview.rb, spec/mailers/observer_mailer_spec.rb, spec/models/dispatcher_spec.rb
http://localhost:5000/rails/mailers/observer_mailer/proposal_complete
https://trello.com/c/d6Pnezlx
=> Create ObserverMailer#proposal_complete email (17)

app/mailers/welcome_mailer.rb, app/views/mail_shared/_inlined_styles.html.erb, app/views/mail_shared/call_to_action/_subheader.html.haml, app/views/mail_shared/email_header/_hero_text.html.haml, app/views/welcome_mailer/welcome_notification.html.haml, config/locales/mailers/en.yml
=> Setting up the welcome email

app/controllers/auth_controller.rb, app/exceptions/email_required.rb, app/models/user.rb, app/views/auth/failure.html.haml, spec/controllers/auth_controller_spec.rb, spec/models/user_spec.rb
trello: https://trello.com/c/lkYMVM4H/184-unchecking-email-share-in-myusa-authorization-results-in-horrible-rails-error
I am not sure how to test this because (a) it seems to require mocking MyUSA more thoroughly than we do and (b) I could not duplicate the error locally.
=> make sure we have email address via myusa

app/admin/report.rb, app/admin/scheduled_report.rb, app/mailers/report_mailer.rb, app/models/report.rb, app/models/scheduled_report.rb, app/services/scheduled_reporter.rb, config/clock.rb, db/migrate/20160307161402_add_scheduled_reports.rb, db/schema.rb, lib/tasks/clock_tasks.rb, spec/factories/scheduled_report.rb, spec/mailers/report_mailer_spec.rb, spec/models/report_spec.rb, spec/models/scheduled_report_spec.rb, spec/services/scheduled_reporter_spec.rb, spec/support/message_delivery.rb
trello: https://trello.com/c/S4PVVXP5/165-backend-mail-out-custom-report-daily-weekly-monthly
This is the backend/model support only, no UI as part of this card.
=> Report scheduler

app/decorators/attachment_decorator.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/attachment_mailer/new_attachment_notification.text.erb, app/views/mail_shared/_inlined_styles.html.erb, app/views/mail_shared/panel/_row_content_image.html.haml, config/locales/mailers/en.yml, lib/mail_previews/attachment_mailer_preview.rb
* https://trello.com/c/e4FmHzbx/191-fix-the-email-attachments-and-create-condition-for-file-image-or-file-link-based-on-uploads
=> Render attachment preview in email

app/mailers/proposal_mailer.rb, app/views/mail_shared/panel/_attachment_items.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, app/views/step_mailer/proposal_notification.html.haml, app/views/step_mailer/proposal_notification.text.erb, app/views/step_mailer/step_reply_received.html.haml, config/locales/mailers/en.yml
https://trello.com/c/60fsK5PN/147-4-email-conversion-approver-new-request-for-approval
=> 🎉 StepMailer#proposal_notification

app/controllers/client_data_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/mailers/proposal_mailer.rb, app/models/ncr_dispatcher.rb, app/services/ncr/work_order_updater.rb, app/services/proposal_update_recorder.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/layouts/email.html.haml, app/views/mail_shared/_inlined_styles.html.erb, app/views/mail_shared/panel/_row_content_modified.html.haml, app/views/proposal_mailer/proposal_updated_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_needs_re_review.text.erb, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, config/locales/mailers/en.yml, lib/mail_previews/proposal_mailer_preview.rb, spec/factories/ncr/work_orders.rb, spec/mailers/proposal_mailer_spec.rb, spec/models/ncr_dispatcher_spec.rb, spec/services/ncr/work_order_updater_spec.rb, spec/services/proposal_update_recorder_spec.rb
* Add specs for `Ncr::WorkOrderUpdater`, too
https://trello.com/c/nbI2mxDU/150-10-email-conversion-approver-modified-request-for-an-awaiting-approval
=> Add comment text to Proposal update emails

app/mailers/proposal_mailer.rb, app/views/mail_shared/_inlined_styles.html.erb, app/views/mail_shared/call_to_action/_button.html.haml, app/views/mail_shared/call_to_action/_email_reply.html.haml, app/views/proposal_mailer/proposal_updated_while_step_pending.html.haml, config/locales/mailers/en.yml
https://trello.com/c/nbI2mxDU/150-10-email-conversion-approver-modified-request-for-an-awaiting-approval
=> Update proposal_updated_while_step_pending template

app/controllers/proposals_controller.rb, app/models/proposal.rb, spec/features/proposals/approve_spec.rb
trello: https://trello.com/c/K3Qppj5S/209-validate-step-before-completing-it
=> Validate step is actionable before completing it

app/decorators/step_decorator.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/mail_shared/approval/_chain.html.haml, app/views/mail_shared/call_to_action/_email_reply.html.haml, app/views/mail_shared/email_header/_updated.html.haml, app/views/mail_shared/panel/_attachment_items.html.haml, app/views/mail_shared/panel/_comment_items.html.haml, app/views/mail_shared/panel/_header_name.html.haml, app/views/mail_shared/panel/_proposal_attributes.html.haml, app/views/observer_mailer/observer_added_notification.html.haml, app/views/observer_mailer/proposal_complete.html.haml, app/views/proposal_mailer/emergency_proposal_created_confirmation.html.haml, app/views/proposal_mailer/proposal_complete.html.haml, app/views/proposal_mailer/proposal_updated_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, app/views/proposal_mailer/proposal_updated_while_step_pending.html.haml, app/views/step_mailer/proposal_notification.html.haml, app/views/step_mailer/proposal_notification.text.erb, config/locales/decorators/en.yml, config/locales/mailers/en.yml, spec/views/mail_shared/_email_reply.html.erb_spec.rb
* Update copy
* Add attachment / comment count
* Add requester full name at top of proposal attributes box
* Add "reply to this email to comment" text
https://trello.com/c/5i8lFRhz
=> Email 4 style tweaks

app/views/proposal_mailer/proposal_updated_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.text.erb, config/locales/mailers/en.yml
https://trello.com/c/o6sAVSOy/216-9-round-3
=> Updates to email 9

app/views/proposal_mailer/proposal_updated_while_step_pending.html.haml, app/views/proposal_mailer/proposal_updated_while_step_pending.text.erb
https://trello.com/c/yQ7ojArd/217-10-round-3
=> Updates to email 10

app/views/observer_mailer/proposal_complete.html.haml, app/views/observer_mailer/proposal_complete.text.erb
https://trello.com/c/XJzMEbDU/220-17-round-3
=> Email 17 updates

app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/attachment_mailer/new_attachment_notification.text.erb, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.text.erb, config/locales/mailers/en.yml
https://trello.com/c/ZR0bSuTF/219-15-round-3
=> Email 15 updates

app/views/cancelation_mailer/cancelation_notification.html.haml, app/views/cancelation_mailer/cancelation_notification.text.erb, config/locales/mailers/en.yml
https://trello.com/c/qsRVBdX6/222-19-round-3
=> Email 19 updates

app/views/cancelation_mailer/cancelation_confirmation.html.haml, app/views/cancelation_mailer/cancelation_confirmation.text.erb, config/locales/mailers/en.yml
https://trello.com/c/CZgah8ci/221-18-round-3
=> Email 18 updates

app/views/comment_mailer/comment_added_notification.html.haml, app/views/comment_mailer/comment_added_notification.text.erb, config/locales/mailers/en.yml
https://trello.com/c/9eRVMATR/218-14-round-3
=> Email 14 updates

app/views/step_mailer/step_reply_received.html.haml, lib/mail_previews/step_mailer_preview.rb
https://trello.com/c/uimwbVk3/211-2-round-3
=> Email 2 updates

app/controllers/proposals_controller.rb, app/decorators/proposal_decorator.rb, app/decorators/step_decorator.rb, app/views/mail_shared/approval/_chain.html.haml, config/locales/decorators/en.yml, config/locales/defaults/en.yml, config/locales/mailers/en.yml
* Include steps status
* Include completed_at date if completed step
* Include step number
https://trello.com/c/E4Ho4BNk/240-include-step-status-in-approval-chain
=> Add more detail to approval chain

app/views/help/running_reports.md
Getting a little broader than “CSV” since many users aren’t familiar with CSVs.
@phirefly 
Not essential to announcing the reporting changes to users, but probably helpful in the long run.
=> Update reports help

config/locales/decorators/en.yml
=> Update translation for decorator

app/decorators/attachment_decorator.rb, app/views/mail_shared/panel/_row_content_image.html.haml
=> Fix the attachment link

app/helpers/mailer_helper.rb, spec/helpers/mailer_helper_spec.rb, spec/helpers/value_helper_spec.rb
* Were showing up as "-"
* Because we were checking for `.present?`
* Change to check for `.nil?`
* Add specs YEAH testing
https://trello.com/c/oo2LPdqD
=> Show "false" proposal values as "No" in email

app/controllers/proposals_controller.rb, spec/support/es_spec_helper.rb
* Updated incorrectly in merge
* https://github.com/18F/C2/commit/a340de63d51c47467dadd5bbf3d6d9d9d31a9881
=> Update method name

app/mailers/report_mailer.rb, app/models/report.rb, spec/mailers/report_mailer_spec.rb
attached CSV was missing newlines between rows
=> Send report now email

app/controllers/auth_controller.rb, spec/features/cancel_spec.rb, spec/features/comment_spec.rb, spec/features/gsa18f/procurements/approve_spec.rb, spec/features/ncr/work_orders/approve_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/proposals/approve_spec.rb, spec/requests/set_user_after_login_spec.rb
* Helpful for evaluating emails in feature specs
https://trello.com/c/XBFISjaN/271-set-default-to-no-welcome-email
=> Set default to "no" welcome email

app/models/proposal.rb, app/views/shared/_search_form.html.haml, spec/models/proposal_spec.rb
trello: https://trello.com/c/LNnQtzg9/236-search-not-working-for-card-holder-name-field-queries
note requires re-indexing in order to QA
=> Card holder search

app/helpers/mailer_helper.rb, spec/helpers/mailer_helper_spec.rb
* Was showing as blank because of helper logic
https://trello.com/c/S1KJlZVr
=> Show proposal attribute as "-" when ""

config/initializers/omniauth.rb
trello: https://trello.com/c/C7GEfi1t
=> no profile first/last request from myusa

app/assets/stylesheets/common/base.scss, app/assets/stylesheets/webapp/summary.scss, app/controllers/summary_controller.rb, app/models/user.rb, app/presenters/client_summary.rb, app/queries/gsa18f/dashboard_query.rb, app/queries/ncr/dashboard_query.rb, app/views/layouts/_header_nav.html.erb, app/views/summary/index.html.haml, db/chores/roles_conversion.rb, db/seeds.rb, spec/controllers/summary_controller_spec.rb, spec/factories/users.rb, spec/features/nav_spec.rb, spec/features/summary_spec.rb, spec/models/user_spec.rb, spec/presenters/client_summary_spec.rb, spec/queries/gsa18f/dashboard_query_spec.rb, spec/queries/ncr/dashboard_query_spec.rb, spec/support/page_objects/home_page.rb, spec/support/page_objects/summary_page.rb
For [this Trello card](https://trello.com/c/A7EoU4o1/106-acquisition-gateway-summary-dashboard-updates), and also includes a fix for [the "No approved count" bug](https://trello.com/c/i80CJ99O).
=> AG dashboard & summary updates

app/mailers/step_mailer.rb, app/views/step_mailer/step_reply_received.html.haml, app/views/step_mailer/step_reply_received.text.erb
* Was defaulting to last completed step
* Should be the same thing, but this is more straightforward
=> Use step user in `StepMailer`

app/decorators/proposal_decorator.rb, spec/decorators/proposal_decorator_spec.rb
trello: https://trello.com/c/Mlt0yGBC/291-reporting-email-bug
=> proposal.final_completed_date requires at least one step

app/models/ncr/organization.rb, spec/models/ncr/work_order_spec.rb
trello: https://trello.com/c/4yAps2bL/241-budget-routing-request-any-request-with-a-code-with-p112xxxx-configuration
=> add P112XXXX to definition of ba_6x_tier1_team

db/chores/roles_conversion.rb, doc/developer_onboarding.md, doc/team_practices.md, spec/models/gsa18f/procurement_spec.rb
* All go to one shared mailbox with a `+`
* Will improve QA process
* https://trello.com/c/JAPEAiM7/260-qa-setup-have-a-shared-setup-for-approval-users
=> Set up consistent system approver email addresses

app/models/gsa18f/procurement_fields.rb, spec/controllers/gsa18f/procurements_controller_spec.rb
* Param was not being sent correctly in controller
https://trello.com/c/bOFnBDST
=> Save procurements as `recurring` when `recurring`

app/admin/user.rb, spec/features/admin_spec.rb
card: https://trello.com/c/3Iazk964/296-ability-to-create-users-via-admin-console
=> create User from /admin UI

app/models/proposal.rb, spec/models/proposal_spec.rb
I have wanted this for a while, mostly for when cleaning up data post-bug-fix.
=> add Proposal.fully_complete! convenience method

app/admin/proposal.rb, app/admin/step.rb, app/models/steps/individual.rb, spec/models/steps/individual_spec.rb
trello: https://trello.com/c/y5c9XvmW/299-discuss-support-tools-needed-e-g-ability-to-manually-approve-as-an-admin
full functionality depends upon #1126
=> Manage steps admin

app/admin/step.rb
=> fix param name in permitted list

spec/models/steps/individual_spec.rb
trello: https://trello.com/c/Wib4cFDJ/298-as-a-mailbox-user-i-should-be-assigned-a-request-that-has-been-put-into-re-approval-status
this is just a test to validate the story in the card. the code itself is already in master.
=> add test to validate step assignment reverts on restart

app/policies/api_token_policy.rb, app/policies/attachment_policy.rb, app/policies/concerns/gsa_policy.rb, app/policies/gsa18f/procurement_policy.rb, app/policies/proposal_policy.rb, app/policies/report_policy.rb, app/policies/scheduled_report_policy.rb, config/locales/errors/en.yml
trello: https://trello.com/c/rXd3KLCd/208-policies-should-use-locales-instead-of-hardcoded-strings
=> Policies use locale strings

app/decorators/ncr/work_order_decorator.rb, app/models/ncr/work_order_fields.rb, app/serializers/ncr/work_order_serializer.rb, app/views/ncr/work_orders/_ba_80_fields.html.haml, config/locales/activerecord/en.yml, config/locales/decorators/en.yml, db/migrate/20160331143230_rename_ncr_code_column.rb, db/schema.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/models/ncr/work_order_fields_spec.rb, spec/requests/api/ncr/work_orders_spec.rb
trello: https://trello.com/c/TfqNfraq/272-rename-code-field-in-database
=> Rename NCR code column

app/views/shared/_status.html.erb, spec/features/ncr/work_orders/post_approval_modification_spec.rb, spec/support/page_objects/proposal_page.rb
trello: https://trello.com/c/Wib4cFDJ/298-as-a-mailbox-user-i-should-be-assigned-a-request-that-has-been-put-into-re-approval-status
=> add feature test demonstrating mailbox system user assigned on approval restart

app/helpers/search_helper.rb, db/schema.rb, spec/queries/proposal_search_query_spec.rb, spec/support/es_spec_helper.rb
master build failing, sometimes. this attempts to address the failures.
=> Misc test fixes

app/assets/javascripts/search.js, app/assets/stylesheets/common/_constants.scss, app/assets/stylesheets/common/search.scss, app/views/shared/_search_form.html.haml, app/views/shared/_search_ui.html.haml
trello: https://trello.com/c/LvyMo4E6/86-as-a-user-i-can-easily-find-advanced-search
deployed now to https://c2-dev-pkarman.18f.gov/
cc @ericronne
=> Adv search options UI tweeks

spec/features/search_spec.rb
seeing DeadClient failure trigger psql constraint errors. trying to avoid those here using same approach as elsewhere.
=> refactor test to avoid let() and before()

app/admin/user.rb, app/models/steps/parallel.rb, config/locales/decorators/en.yml
while verifying https://trello.com/c/MRo5TnY3/207-as-a-delegate-i-can-modify-a-request-that-has-not-yet-been-approved-in-my-current-step
I added these /admin/ features to make it easier to review/manage user delegates.
Also fixed a typo and a missing locale translation.
=> Admin user delegates

app/controllers/ncr/work_orders_controller.rb, app/models/steps/individual.rb, spec/features/ncr/work_orders/post_approval_modification_spec.rb, spec/models/steps/individual_spec.rb
ticket: https://18f.uservoice.com/admin/tickets/178
fixes re-approval checks for budget approvers.
=> re-approval fix (work_order.modifier)

app/models/comment.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/proposals/show.html.haml, config/locales/activerecord/en.yml, spec/features/ncr/work_orders/post_approval_modification_spec.rb, spec/models/comment_spec.rb
trello: https://trello.com/c/TYWpleej/285-as-a-user-i-can-see-the-approval-date-in-the-request-history-below-the-comments-section-so-that-i-understand-the-entire-life-cyc
=> add completed_ and restart_ comments

db/migrate/20160406142950_fix_versions_item_type_for_steps.rb, db/schema.rb, lib/c2_version.rb
trello: https://trello.com/c/V4fvtjy7/321-500-error-on-proposal-history
see trello code for full explanation.
=> fix versions.item_type for older data

app/models/concerns/searchable.rb, app/services/proposal_update_recorder.rb, spec/services/proposal_update_recorder_spec.rb
ticket: https://18f.uservoice.com/admin/tickets/193
=> in rails, .blank? == (.nil? or .empty?) -- support nil values

lib/tasks/dev.rake
rake dev:prime was failing due to an issue with the method name "file"
Changed to `temp_file`
=> fixed dev.rake, changed def file > def temp_file

app/views/mail_shared/approval/_chain.html.haml
* Instead of instance var
* Better to use local vars in view files to prevent "mystery guest"
* We were already passing `proposal` var to view partial anyway!
=> Use local var in `approval/chain` partial

app/controllers/comments_controller.rb, spec/controllers/comments_controller_spec.rb, spec/features/comment_spec.rb
* Move data checking into controller spec (out of feature spec)
* Done while investigating https://trello.com/c/1XMufWy1, which I was
unable to get to the source of
=> Refactor comment specs

spec/decorators/c2_version_decorator_spec.rb, spec/factories/approvals.rb, spec/factories/proposals.rb, spec/factories/steps.rb, spec/features/linear_approvals_spec.rb, spec/features/proposals/index_spec.rb, spec/helpers/mailer_helper_spec.rb, spec/models/concerns/step_manager_spec.rb, spec/models/step_spec.rb, spec/models/steps/individual_spec.rb, spec/models/steps/parallel_spec.rb, spec/models/steps/serial_spec.rb, spec/services/role_picker_spec.rb, spec/views/mail_shared/_email_reply.html.erb_spec.rb
* Were using `approval_step` and `approval` interchangeably
=> Use `approval_step` factory everywhere

app/models/concerns/client_data_mixin.rb, app/models/concerns/step_manager.rb, app/models/proposal.rb, app/models/step.rb, app/models/steps/individual.rb, app/views/mail_shared/approval/_chain.html.haml, spec/models/concerns/step_manager_spec.rb, spec/models/proposal_spec.rb, spec/support/shared_examples/client_data.rb
Changed class in proposal for
individual steps from "Steps:Individual" to
"Step"
Scope "individual" limits steps to "Approval"
and "Purchase"
https://trello.com/c/Tsg7daOb/389-sometimes-steps-don-t-show-up
=> Steps would be randomly missing from emails

doc/api.md
I'm ambivalent about keeping the client-model-specific attributes documented here. It will then be a maintenance burden.
=> API v2 docs

app/controllers/proposals_controller.rb, app/views/proposals/show_next.html.haml, spec/controllers/proposals_controller_spec.rb
On `proposal#show` check for `?detail=view` to load alternate `show_next.html.haml`
=> Create check for query param to load alternate view

app/policies/proposal_policy.rb, spec/features/cancel_spec.rb, spec/policies/proposal_policy_spec.rb
trello: https://trello.com/c/j4c8Lxfp/318-ability-of-tier-2-approvers-to-cancel-a-request
=> Actionable user can cancel

app/helpers/mailer_helper.rb, app/mailers/application_mailer.rb, app/mailers/attachment_mailer.rb, app/mailers/cancelation_mailer.rb, app/mailers/comment_mailer.rb, app/mailers/observer_mailer.rb, app/mailers/proposal_mailer.rb, app/mailers/step_mailer.rb, app/models/dispatcher.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/cancelation_mailer/cancelation_confirmation.html.haml, app/views/mail_shared/approval/_chain.html.haml, app/views/step_mailer/step_reply_received.html.haml, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/helpers/mailer_helper_spec.rb, spec/mailers/attachment_mailer_spec.rb, spec/mailers/cancelation_mailer_spec.rb, spec/mailers/comment_mailer_spec.rb, spec/models/dispatcher_spec.rb, spec/models/incoming_mail_handler_spec.rb
* To prevent wackiness if we ever remove / move images in app
https://trello.com/c/FGZuU0RY/387-inline-all-icons-in-emails
=> Inline step icons in emails

spec/controllers/proposals_controller_spec.rb
should fix failing spec on master.
=> fix tests to use locale strings

app/views/proposals/details/_activity.html.haml, app/views/proposals/details/_approvals.html.haml, app/views/proposals/details/_purchase.html.haml, app/views/proposals/details/_request_details_column.html.haml, app/views/proposals/details/history/_approval.html.haml, app/views/proposals/details/history/_attachment.html.haml, app/views/proposals/details/history/_comment.html.haml, app/views/proposals/details/history/_proposal.html.haml, app/views/proposals/details/history/_step.html.haml
Because thats how the code refers to it everywhere else.
=> Rename folder from detail to details

app/views/proposals/detail/_attachment.html.haml, app/views/proposals/show_next.html.haml
Dependent on preceding PRs related to new details page design
Adds the layout partials for the Attachment content.
https://trello.com/c/0OrpiMHD 
- Attachment Card Markup
=> Add new details page attachment partial markup (Merge #1185 first)

app/decorators/step_decorator.rb, app/presenters/history_event.rb, app/presenters/history_list.rb, app/presenters/tabular_data/container.rb, config/locales/decorators/en.yml, spec/decorators/step_decorator_spec.rb, spec/presenters/history_list_spec.rb
This is dependent on https://github.com/18F/C2/pull/1169
Parse the history on a proposal and make it accessible as a instance variable to display in show_next.html.haml
https://trello.com/c/0OrpiMHD/395-transition-design-new-details-branch-into-master-through-smaller-prs
=> New details page/add history instance

spec/features/admin_spec.rb
* Highlight that email not sent on step update
=> Clarify / update admin specs

app/helpers/mailer_helper.rb, spec/helpers/mailer_helper_spec.rb
trello: https://trello.com/c/geOmqtU0/403-invalid-timezone-error-in-mailer
=> Invalid timezone

app/mailers/comment_mailer.rb, spec/mailers/comment_mailer_spec.rb
to fix failing jobs like https://cap.18f.gov/admin/jobs/120940
=> be more generous in what we receive (email or User) in mailer method

doc/developer_onboarding.md
zap duplicate line, add example of replacing usernames
=> Update onboarding doc template

app/admin/user.rb, spec/features/admin_spec.rb
trello: https://trello.com/c/Nlt4bleY/410-verify-timezone-editing-works
=> use only TimeZone names in dropdown list, not UTC offsets

app/assets/stylesheets/redesign/_card-summary.scss, app/assets/stylesheets/redesign/_foundation_custom.scss, app/assets/stylesheets/redesign/_foundation_settings.scss, app/views/proposals/details/_summary.html.haml
Add new designs for Summary Bar.
https://trello.com/c/KS9DRViS/373-details-summary-bar
=> Add Summary Bar

app/assets/stylesheets/redesign/_card-approvals.scss, app/assets/stylesheets/redesign/_card-summary.scss
Updating styles for all cards headers.
https://trello.com/c/nsoucIhH/374-details-approvals-card
=> Add changes for approval card + IE fixes

app/assets/stylesheets/redesign/_basic.scss, app/assets/stylesheets/redesign/_card-summary.scss, app/assets/stylesheets/redesign/_top-notification.scss, app/views/proposals/details/_action.html.haml, app/views/proposals/details/_summary.html.haml, app/views/proposals/show_next.html.haml, spec/features/attachment_spec.rb
Update design from v18
https://trello.com/c/c8FuCaEf/372-overall-design-changes-to-details-page
=> Update the status bar and background colors for cards

app/assets/stylesheets/redesign/_card-summary.scss, app/views/proposals/details/_approvals.html.haml, app/views/proposals/details/_summary.html.haml
The Approval steps were loading out of order.
Fixing this.
=> Fix the approval steps ordering

db/migrate/20160429143512_user_timezone_default.rb, db/schema.rb
changes db default to `Eastern Time`
=> change users.timezone default, clean up data

db/migrate/20160426212643_fix_step_user_completer.rb
trello: https://trello.com/c/WDBh0nXW/413-fix-completed-steps-where-completer-is-null
=> fixes unique db constraint bug discovered when run against recent prod db snapshot

app/mailers/application_mailer.rb, app/mailers/concerns/mail_addressing.rb, app/models/incoming_mail/handler.rb, app/models/incoming_mail/response.rb, spec/models/incoming_mail_handler_spec.rb
https://trello.com/c/GOYM8mdl/419-feedback-form-requires-authn
=> avoid email loops by dropping suspect messages into the bit bucket

config/database.yml, config/initializers/konacha.rb, config/puma.rb
Konacha test runner complains about `tile/coffee`. 
This `require` resolves the issue.
=> Resolve Konacha test error

app/assets/javascripts/details/state/details_request_form_state.js, spec/javascripts/details/state/details_request_form_spec.js.coffee, spec/javascripts/spec_helper.js.coffee
Create events to trigger on changes around request details page
New Design JavaScript
=> Add change events around request details form changes [NDJS: Merge in order 1]

app/assets/javascripts/details/app.js, app/assets/javascripts/details/shell/c2.js, app/views/proposals/show_next.html.haml, spec/javascripts/details/shell/c2_spec.js.coffee
Create a shell file that makes it easier to test combining JS. Shell function operates the same way all other JS files are expected to work.
The `C2` object is exported and accessed publicly via `app.js`.
New Design JavaScript
=> Organize the JavaScript glue file [NDJS: Merge in order 3]

app/controllers/comments_controller.rb, app/views/comments/create.js.erb, app/views/proposals/details/_activity.html.haml, app/views/proposals/details/_comment_list.html.haml, spec/features/comment_spec.rb, spec/support/wait_for_ajax.rb
Comments now appear on page without reloading
=> Make comments ajax

app/assets/javascripts/details/state/details_request_form_state.js, app/assets/javascripts/details/views/details_request_form.js, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/state/details_request_form_spec.js.coffee, spec/javascripts/details/views/details_request_form_spec.js.coffee
1. Split up the details_request_form state and view functionality
=> 1️⃣️ Break up the form state and form view behavior [NDJS 1]

app/assets/javascripts/details/views/action_bar.js, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/state/edit_mode_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/attachment_card_spec.js.coffee
Add new helper structure for the specs. Also update the `action-bar` event naming convention.
=> 2️⃣ Use a shared details helper + update event names [NDJS 2]

app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/views/action_bar.js, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/state/edit_mode_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/attachment_card_spec.js.coffee
Create ability to save the request details form. Trigger the form using .submit().
This is rebased on-top of #1237. Please merge #1237 before this one.
=> 3️⃣ Add Request Details form data save methods [NDJS 3]

app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/state/details_request_form_state.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/details_request_form.js, app/views/layouts/_new_javascript.html.haml, app/views/proposals/show_next.html.haml, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/state/details_request_form_spec.js.coffee, spec/javascripts/details/state/edit_mode_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/attachment_card_spec.js.coffee, spec/javascripts/details/views/details_request_form_spec.js.coffee
Set up the C2 shell file constructors. Confirm its working via tests.
=> 4️⃣ C2 shell constructors and basic test [NDJS 4]

Gemfile.lock, app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/state/details_request_form_state.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/details_request_form.js, app/views/layouts/_new_javascript.html.haml, app/views/proposals/show_next.html.haml, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/state/details_request_form_spec.js.coffee, spec/javascripts/details/state/edit_mode_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/attachment_card_spec.js.coffee, spec/javascripts/details/views/details_request_form_spec.js.coffee
Create a condition in the c2 shell file to optionally load config parameters. This provides a way to override the test conditions with a mock dom. Helps for unit tests.
Merge the NDJS files with smaller numbers first.
=> 5️⃣️ Provide ability for tests to use config params [NDJS 5] 

Gemfile.lock, app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/state/details_request_form_state.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/details_request_form.js, app/views/layouts/_new_javascript.html.haml, app/views/proposals/show_next.html.haml, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/state/details_request_form_spec.js.coffee, spec/javascripts/details/state/edit_mode_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/attachment_card_spec.js.coffee, spec/javascripts/details/views/details_request_form_spec.js.coffee
Create a file that stitches the other JS together. All events that require another functions from another file will use `shell/c2.js`. The tests are setup using the `detail_helper` to improve DRY unit testing.
This needs to be merged after the preceding NDJS PRs.
=> 6️⃣ Add C2.js glue code and events  [NDJS 6] 

doc/api.md
=> API doc improvements

lib/tasks/dev.rake, script/bootstrap
[Trello card](https://trello.com/c/sN6MiJDN/443-bootstrap-script-fails)
=> script/bootstrap: Better error checking and feedback

Gemfile
Makes it a lot easier to interactively work with the production data.
=> Moved pry-rails to production

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/cancel_card.js, app/assets/stylesheets/redesign/_card-cancel.scss, app/assets/stylesheets/redesign/app.scss, app/views/layouts/_new_javascript.html.haml, app/views/proposals/details/_cancel.html.haml, app/views/proposals/show_next.html.haml, spec/features/cancel_spec.rb, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee
Clicking cancel request brings up modal form
Form excepts a reason and allows you to cancel or return to the proposal
=> Functionality for cancel request button on redesign

app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/state/details_request_form_state.js, spec/javascripts/details/state/details_request_form_spec.js.coffee
To identify form submission problems, I changed the source of form submissions. Instead of using the `$form.submit()`, we are now using `$form.serialize()` as the data source for a ajax request.
I also removed the unused form field indexing in `details_request_form`.
=> Change the source of form submission

app/assets/stylesheets/redesign/_card-cancel.scss, app/views/proposals/details/_activity.html.haml, app/views/proposals/details/_cancel.html.haml, app/views/proposals/details/_summary.html.haml, app/views/proposals/show_next.html.haml
Changed buttons on form
Changed spacing
Added close button on form
Moved cancel form button to top
=> Updated styling of the cancel form on the redesign page

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/observer_card.js, app/controllers/observations_controller.rb, app/views/observations/create.js.erb, app/views/observations/destroy.js.erb, app/views/proposals/show_next.html.haml, spec/features/observer_spec.rb
Notifies user when an observer is added and removed
=> Added visual notification for added observers

app/assets/stylesheets/redesign/_card-request_details.scss, vendor/assets/javascripts/jquery.dirrty.js
Identify changes on fields. Change dirrty.js to work with selectize by targeting parent elements.
=> Update dirrty to work with selectize

app/assets/stylesheets/redesign/_card-request_details.scss, app/views/ncr/fields/_rwa_number.html.haml, app/views/ncr/fields/_work_order_code.html.haml
Fix broken styles from last PR regarding `RWA` and `workorder_code`.
=> Update the RWA and workorder information

app/assets/javascripts/application.js, app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/state/details_request_form_state.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/notifications.js, app/assets/stylesheets/common/base.scss, app/assets/stylesheets/ncr/_fields.scss, app/assets/stylesheets/redesign/_card-action.scss, app/assets/stylesheets/redesign/_card-request_details.scss, app/assets/stylesheets/redesign/_top-notification.scss, app/views/ncr/fields/_description.html.haml, app/views/proposals/details/_action.html.haml, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/views/action_bar_spec.js.coffee, spec/javascripts/details/views/notification_bar_spec.js.coffee, vendor/assets/javascripts/progressbar.js
Add action bar styles to appear/disappear based on usability. During approval mode, the buttons will change to display accordingly.
Notifications have been beefed up. Designs now match existing spec. Notifications also now close automatically with a timer. The timer is visible on the close button, as a circle that closes on completion.
=> Adding notification and action bar styles

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/modal_card.js, app/assets/javascripts/required_for_submit.js.coffee, app/assets/stylesheets/redesign/_animation.scss, app/assets/stylesheets/redesign/_card-modal.scss, app/assets/stylesheets/redesign/app.scss, app/views/layouts/_new_javascript.html.haml, app/views/proposals/details/_modal.html.haml, app/views/proposals/details/_summary.html.haml, app/views/proposals/details/modals/_cancel.html.haml, app/views/proposals/details/modals/_template.html.haml, app/views/proposals/show_next.html.haml, spec/features/cancel_spec.rb, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/views/modal_card_spec.js.coffee
Create a decoupled method for generating modals/popups that can be used for various purposes.
=> New Modal/Popup generation process

app/assets/stylesheets/redesign/_card-attachments.scss.erb, app/views/proposals/details/_attachment.html.haml, app/views/proposals/details/_attachment_list.html.haml
Some minor improvements to the attachments card
Removed header text as per @amberwreed 
added "Remove" when you hover on delete button
=> Attachment refinements

app/assets/stylesheets/redesign/_card-action.scss, app/assets/stylesheets/redesign/_card-request_details.scss, app/assets/stylesheets/redesign/_card-summary.scss, app/assets/stylesheets/redesign/_card.scss.erb
- Updating the blue being used to be more accessible
- Change the color and opacity of the action bar
- Adding the underline on hovered anchor tags
=> Adding small style changes for functionality

app/assets/javascripts/details/shell/c2.js, app/presenters/history_event.rb, app/presenters/history_list.rb, app/views/proposals/details/history/_procurement.html.haml, app/views/proposals/details/history/_workorder.html.haml, spec/presenters/history_event_spec.rb, spec/presenters/history_list_spec.rb
Includes formatted diffs of proposal & client_data object data updates.
=> Save card activity updates

app/helpers/value_helper.rb, app/views/proposals/details/history/_attachment.html.haml, app/views/proposals/details/history/_comment.html.haml, app/views/proposals/details/history/_procurement.html.haml, app/views/proposals/details/history/_proposal.html.haml, app/views/proposals/details/history/_step.html.haml, app/views/proposals/details/history/_workorder.html.haml, app/views/proposals/show_next.html.haml
Show the date when an activity item wasn't made on the current day
=> options passed to date with tooltip that formats time

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/modal_card.js, app/assets/stylesheets/redesign/_card-action.scss, app/assets/stylesheets/redesign/_card-modal.scss, app/assets/stylesheets/redesign/_card-request_details.scss
=> Update the confirmation window animation

app/assets/javascripts/details/shell/c2.js, app/views/attachments/create.js.erb, app/views/attachments/destroy.js.erb, app/views/proposals/details/_attachment_list.html.haml
Added error notification and handling for attachments
=> Attachment refinements 2

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/state/details_request_form_state.js, app/assets/stylesheets/redesign/_card-summary.scss, app/views/ncr/fields/_title.html.haml, app/views/proposals/details/_summary.html.haml, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/state/details_request_form_spec.js.coffee
Trigger the edit function on the title bar when modify is activated.
Submitting PR now while small. Due to many files changing, I want to catch any issues early. Does not _save_. Just triggering edit mode.
=> Make titles editable from "modify" action bar

app/assets/stylesheets/redesign/_foundation_settings.scss
Update the blue being used globally.
=> Change the global blue used on buttons

app/views/proposals/details/_status.html.haml, app/views/proposals/show_next.html.haml
Make changes to the "approvals" card title. Change to "status".
=> Make changes to approval partials and card to status

app/assets/stylesheets/redesign/_card.scss.erb
Reference request from prototype functionality spreadsheet
=> Change the padding on card header to 30px

doc/setup.md
Trello card: https://trello.com/c/T5K6IQXf/480-revise-docs-to-recommend-rbenv-not-rvm
=> Recommend rbenv for developer machines

app/assets/javascripts/details/views/modal_card.js, app/assets/stylesheets/redesign/_card-modal.scss, app/views/proposals/details/modals/_template.html.haml
Focus moves to modal when its activated.
=> Focus is moved to the modal when its activated for keyboard users

lib/mail_previews/attachment_mailer_preview.rb, lib/mail_previews/cancelation_mailer_preview.rb, lib/mail_previews/mailer_preview_helpers.rb
Was getting errors for mailer previews. Added some stubbing to prevent this.
=> Added stubs for when mailer previews to prevent errors

spec/factories/ncr/work_orders.rb, spec/features/observer_spec.rb
This fixes test issues and updates how the beta "flag" was being set to be more stable.
=> Fix observer spec tests

app/views/proposals/details/_status.html.haml
https://trello.com/c/iIKdPjz9/501-status-panel-not-displaying-status-of-step
=> Create a pending status on the actionable and pending states of status

app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/notifications.js
Updates to notifications after editing.
- Alert notices do not automatically disappear
- Extend time of notices to 7.5 seconds
- Clear all notices when save/cancel is clicked
=> Update notification behavior

app/assets/javascripts/details/data/details_save.js, spec/javascripts/details/data/details_save_spec.js.coffee, spec/javascripts/details/details_helper.js.coffee
Filling out unit test stubs for events:
- `details-form:save`
- `details-form:respond`
- `details-form:success`
- `details-form:error`
=> Create tests for details_save.js

doc/developer_onboarding.md, doc/envvars.md, doc/troubleshooting_alerts.md
This is the start of a guide to troubleshooting alerts and downtime. Currently incomplete, and while I'll be adding more info, I'd really appreciate additions from those who've diagnosed/fixed problems in the past. In particular, I don't know anything about looking after the `worker` process.
/cc @phirefly @pkarman @jessieay @rememberlenny
=> [WIP] Troubleshooting guide

app/views/proposals/details/_status.html.haml
https://trello.com/c/mKEhP6tK/515-steps-start-at-step-0
=> Step counter set by index instead of model

app/assets/stylesheets/common/base.scss, app/assets/stylesheets/redesign/_card.scss.erb, app/views/proposals/show.html.haml
=> added style for wordwrapping filenames of attachments

manifest.yml
* Micropurchase wants to use Prod API!
* See https://github.com/18F/C2/blob/a935eb3807ec7a859941e590616f883ae4be285c/doc/api.md
=> Enable API on prod

app/assets/javascripts/details/views/notifications.js, spec/javascripts/details/views/notification_bar_spec.js.coffee
Add the tests to the notification's javascript
=> Adding tests to the notification's page

app/decorators/gsa18f/procurement_decorator.rb, app/decorators/ncr/work_order_decorator.rb
Reorder form fields based on latest design. Does not contain changes on style.
=> Reorder the NCR and 18f form fields to be styled with new layout

app/views/gsa18f/fields/_date_requested.html.haml
Fix error on 18F fields when date requested is blank.
https://trello.com/c/xdGCqTSq/527-18f-beta-user-500-occurs-when-viewing-new-detail-page-for-18f
=> Fix error on 18F fields when date requested is blank

app/controllers/proposals_controller.rb, app/views/proposals/details/_top_notification.html.haml, config/locales/views/en.yml
Adds a message for users who revert to the old design
=> top message for beta users who revert to old design

app/views/gsa18f/_request_details.html.haml, app/views/gsa18f/fields/_total_price.html.haml, app/views/ncr/_request_details.html.haml, app/views/ncr/fields/_title.html.haml, app/views/proposals/details/_request_details.html.haml, app/views/proposals/details/_summary.html.haml
Partials were rendering partials relative to the current_user. User the requester of the proposal to qualify which partial is rendered.
=> Fix how partials are rendered

app/views/proposals/details/_attachment.html.haml
Change the condition that hides attach file button.
=> Make attachments editable when completed

app/assets/javascripts/force_ethnio.js, app/views/layouts/_new_javascript.html.haml, app/views/proposals/details/_top_notification.html.haml
**Ready for code review**
Add ethnio pop-up after a user clicks "Show old design"
To collect feedback as to why the user stopped using the new page
=> Show ethnio popup on revert

app/assets/javascripts/details/shell/c2.js
Update the cancel button notification message.
https://trello.com/c/ixQcz0yp/529-reset-modified-values-after-canceling
=> Update the cancel notification message

app/assets/javascripts/details/views/details_request_card.js, app/views/ncr/fields/_amount.html.haml
On the new page, amount displays with 2 decimals now. Before only 1 was showing.
=> Amount formatted by javascript with 2 digits

app/decorators/c2_version_decorator.rb, app/presenters/history_list.rb, app/views/proposals/details/history/_attachment.html.haml, spec/features/attachment_spec.rb
=> Add Entry for deleted attachments in activity feed

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/activity_card.js, app/assets/javascripts/details/views/approvals_card.js, app/assets/javascripts/details/views/view_helper.js, app/controllers/proposals_controller.rb, app/views/layouts/_new_javascript.html.haml, app/views/proposals/show_next.html.haml, config/routes.rb
Added approval card controller and use it to update the approval card when a user modifies the proposal.
=> Update approval status on proposal modification

doc/api.md
=> Add some docs for Proposals#update action in API

app/views/reports/show.html.haml
@amberwreed to give thumbsup + merge
=> Update link to Reports

app/assets/javascripts/details/views/summary_bar.js, app/views/ncr/fields/_title.html.haml
The details view `title` field was not being updated on the frontend. During refactoring, the selectors targeting the title broke.
There was no test to detect this would break.
=> Update the details title

app/controllers/client_data_controller.rb, app/presenters/flash_with_now.rb, app/presenters/flash_without_now.rb
Fix notices from `proposal#show` view were appearing in other pages.
Add the `.now` attribute on notices.
=> Create notices around the controller's JS related interactions

app/assets/stylesheets/redesign/_card-modal.scss, app/assets/stylesheets/redesign/_card-summary.scss, app/views/proposals/details/_summary.html.haml, app/views/proposals/show.html.haml
Moving cancel down and changing requester copy
=> Title tweaks

circle.yml, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/views/notification_bar_spec.js.coffee
Turn on the CircleCI JavaScript tests.
They were disabled and shouldnt have been.
=> Turn on JS tests on circleCI

app/assets/javascripts/details/shell/c2.js, spec/features/observer_spec.rb
https://trello.com/c/aq3wTFN1/562-content-change-for-notificaitons
=> removed "Observer added/removed" from notification in redesign

app/assets/javascripts/home/load.js, app/assets/stylesheets/home.scss, app/views/home/index.html.haml
The home page loaded with a jump, as the header was displayed. This fixes this by adding the custom styles in at the start and setting a minimum height temporarily to keep it from jumping
https://trello.com/c/od2gcZME/438-fix-visual-glitch-when-loading-c2
=> updated home page styles to be less jarring on load

app/assets/javascripts/details/data/update_view.js, app/assets/stylesheets/redesign/_card-request_details.scss, app/helpers/application_helper.rb, app/views/gsa18f/_request_details.html.haml, app/views/gsa18f/fields/_additional_info.html.haml, app/views/gsa18f/fields/_cost_per_unit.html.haml, app/views/gsa18f/fields/_date_requested.html.haml, app/views/gsa18f/fields/_justification.html.haml, app/views/gsa18f/fields/_link_to_product.html.haml, app/views/gsa18f/fields/_office.html.haml, app/views/gsa18f/fields/_product_name_and_description.html.haml, app/views/gsa18f/fields/_purchase_type.html.haml, app/views/gsa18f/fields/_quantity.html.haml, app/views/gsa18f/fields/_recurring.html.haml, app/views/gsa18f/fields/_recurring_interval.html.haml, app/views/gsa18f/fields/_recurring_length.html.haml, app/views/gsa18f/fields/_urgency.html.haml, app/views/ncr/_request_details.html.haml, app/views/ncr/fields/_building_number.html.haml, app/views/ncr/fields/_cl_number.html.haml, app/views/ncr/fields/_description.html.haml, app/views/ncr/fields/_direct_pay.html.haml, app/views/ncr/fields/_emergency.html.haml, app/views/ncr/fields/_function_code.html.haml, app/views/ncr/fields/_rwa_number.html.haml, app/views/ncr/fields/_soc_code.html.haml, app/views/ncr/fields/_vendor.html.haml, app/views/ncr/fields/_work_order_code.html.haml
Substitute empty fields with "--".
https://trello.com/c/U20LQWkm/606-add-if-a-form-field-is-blank
=> Substitute empty fields with "--"

app/assets/stylesheets/redesign/_card.scss.erb
Provide padding below the last box, so the actionbar doesn't cover the observers card.
https://docs.google.com/spreadsheets/d/1ZpzCwhExizevhZhS-g3rZQmE9ihXyRv-uGGbjUVCweo/edit#gid=0
=> Give action bar space below

app/views/ncr/fields/_direct_pay.html.haml
and to not show direct pay when it is false
https://trello.com/c/rdMHoAp2/609-remove-direct-pay-in-summary-view-if-it-s-value-is-false
=> Updated direct pay message to say "Direct pay will be used"

app/controllers/proposals_controller.rb, app/models/role.rb, app/models/user.rb, app/views/proposals/index_next.html.erb, config/initializers/01_c2.rb
https://trello.com/c/X1osmofH/645-initial-setup-of-list-view-redesign
=> Setup for new beta list view

app/views/layouts/_scripts.html.haml, app/views/proposals/show_next.html.haml
Rename files to make sense for upcoming use
=> Preparing beta list changes and renaming files

app/views/proposals/details/_action.html.haml
https://trello.com/c/Zs56zRTq/655-buttons-on-action-bar-should-be-all-caps
=> upcased action bar

app/assets/stylesheets/webapp/webviews.scss
https://trello.com/c/36BPEZIh/650-feedback-link-hidden-by-action-bar-on-details-page
=> move footer above action bar

app/views/layouts/_sidebar_shared.html.haml
Fix the anchor links in the sidebar. Previously syntax was wrong.
=> Fix anchor links in sidebar

app/assets/stylesheets/redesign/_basic.scss, app/assets/stylesheets/redesign/_card-summary.scss, app/assets/stylesheets/redesign/_card.scss.erb, app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss, app/helpers/application_helper.rb, app/views/layouts/_sidebar_shared.html.haml, app/views/layouts/application.html.haml
Add the count of a sidebar request category in the navigation.
=> Create bucket counters

app/views/gsa18f/_request_details.html.haml, app/views/gsa18f/fields/_date_requested.html.haml
Fix condition for 18f client_slug being broken with blank date time.
=> Urgent: 18f client_slug doesnt handle date-time when string is blank

app/assets/javascripts/details/shell/list_view_bridge.js, app/assets/javascripts/details/views/list/list_view.js, app/assets/javascripts/details/views/shared/sidebar_nav.js, app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss, app/helpers/application_helper.rb, app/views/layouts/_sidebar_shared.html.haml, app/views/proposals/details/_summary.html.haml, config/tables/proposals.yml
- Updating sidenav styles
- Make entire rows clickable
- Change over behavior in sidenav
- Remove return to request in details page
- Add new columns in list view NCR
- Save the columns state via browsers
=> Lots of changes with Amber

app/assets/javascripts/details/views/shared/sidebar_nav.js, app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/views/layouts/_c2_header_next.html.haml
Add a mobile menu toggle in small viewports
=> Add mobile menu toggle

app/controllers/application_controller.rb, app/controllers/attachments_controller.rb, app/controllers/client_data_controller.rb, app/controllers/proposals_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/_notices.html.haml, app/views/proposals/details/_top_notification.html.haml, app/views/proposals/index.html.erb, app/views/proposals/index_next.html.erb, config/locales/views/en.yml, config/routes.rb, spec/controllers/proposals_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb
https://trello.com/c/fA0YU6Zs/700-add-active-beta-notification-to-top-of-list-view
Shows the "new version of this page" at the top
of the list view.
Only shows when
1) The env[BETA_LIST_VIEW] is set to true
2) The user is a beta user
Updated the route logic to a single route to toggle
active beta user status
Added new method to make clear how to check if beta
features can be activated.
=> Show New features beta toggle at top of list view

Gemfile, Gemfile.lock
Updated per vulnerabilities recently discussed in the #cap slack
=> Updated doorkeeper gem

app/assets/javascripts/details/views/list/list_view.js, app/assets/stylesheets/common/_constants.scss, app/assets/stylesheets/common/search.scss, app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/views/layouts/_scripts.html.haml, app/views/layouts/_user_header.html.haml, app/views/proposals/index_next.html.erb, app/views/shared/formatter/_review_status.html.haml, config/locales/decorators/en.yml, config/tables/proposals.yml, spec/features/proposals/index_spec.rb, vendor/assets/javascripts/DataTables/dataTables.ellipsis.js, vendor/assets/stylesheets/foundation/forms/_text.scss
Lots of small changes!
- If user doesnt have client slug, prompt to set up (https://trello.com/c/rzZY5DKR/723-if-user-doesnt-have-client-slug-prompt-to-set-up)
- Search visual design refinement (https://trello.com/c/KQpgOkU6/719-search-visual-design-refinement)
- Nav hover state border (https://trello.com/c/koa1PFcO/698-nav-hover-state-border)
- Consistency between filter arrows (https://trello.com/c/htyt74bd/697-consistency-between-filter-arrows)
- Change red row close button to dark blue (https://trello.com/c/EJKfOZJ3/716-change-red-row-close-button-to-dark-blue)
- Building number column (https://trello.com/c/de7dH2Ic/717-building-number-column)
- Main nav font should be Helvetica (https://trello.com/c/eNJACyuO/710-main-nav-font-should-be-helvetica)
- List view table data alignment, …
=> New List Page Design Refinements

app/assets/javascripts/details/views/list/list_view.js
Set default columns when you first view a page. 
https://trello.com/c/xhwgb0X5/742-set-1st-time-default-attributes-for-list-view-table-headers
=> Set default columns in list view

app/assets/stylesheets/redesign/_basic.scss, app/assets/stylesheets/redesign/_card.scss.erb, app/controllers/client_data_controller.rb, app/views/layouts/_application_next.html.haml, app/views/layouts/_application_old.html.haml, app/views/layouts/application.html.haml, app/views/ncr/_request_details.html.haml, app/views/ncr/work_orders/_attachments.html.haml, app/views/ncr/work_orders/_form_new.html.haml, app/views/ncr/work_orders/new.html.haml, app/views/ncr/work_orders/new_next.html.haml
Create the styles for the new request page
- Attachments card
- Observer's cards
- Sidebar button state styling
=> Style the new requests page

app/queries/proposal_listing_query.rb, spec/features/ncr/work_orders/dashboard_spec.rb
A rails error occured when downloading a CSV of proposals from ncr/dashboard.
https://trello.com/c/MwvagDCL/751-support-monthly-downloads-broken
=> Monthly downloads broken

app/assets/javascripts/add_minus.js.coffee, app/assets/stylesheets/redesign/_card-action.scss, app/assets/stylesheets/redesign/_card-activity.scss, app/assets/stylesheets/redesign/_card-attachments.scss.erb, app/assets/stylesheets/redesign/_card.scss.erb, app/assets/stylesheets/webapp/webviews.scss, app/views/ncr/work_orders/_form_new.html.haml, app/views/ncr/work_orders/new_next.html.haml, app/views/proposals/details/_save_action.html.haml
Make the new request page fully functional.
- Add the ability to submit the form. 
- Add the ability to attach files.
- Add the ability to add observers.
- Prevent form from submitting if certain functionality is missing
=> New Request functionality

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/list/list_config.js, app/assets/javascripts/details/views/list/list_view.js, app/assets/stylesheets/redesign/_list.scss.erb, app/views/layouts/_scripts.html.haml
Control the list view columns. Specify width and ellipsis usage. Use a separate config file to determine styles.
Config uses class name on `th` element to make adjustments. The class name is generated using new function.
The columns are browser dependent and relatively inconsistent. This is meant to add a fix to 80% of the use cases. Because of the `table` element's `responsive` parameter, this is the best we can do.
https://trello.com/c/GaVUDVdE/743-list-view-column-width
=> Adjust the listview columns

app/assets/javascripts/details/views/list/list_config.js, app/assets/stylesheets/redesign/_card.scss.erb, app/views/gsa18f/procurements/_form_new.html.haml, app/views/gsa18f/procurements/new_next.html.haml, config/tables/proposals.yml
Setup the new request page to work with GSA18f client users.
Style the beta form with existing show/hide functionality.
https://trello.com/b/kAW72R3m/c2-birthday-cake
=> Setup the GSA18f New Request Page

spec/features/client_slug_authz_spec.rb
Check to make sure the templates work with proper env vars.
=> Add tests to new request page

app/controllers/client_data_controller.rb, app/views/gsa18f/procurements/_form_new.html.haml, app/views/ncr/work_orders/_form_new.html.haml
On beta, when form submission is rejected due to validation, load new form.
=> Load correct new form on unvalidated submissions

app/assets/stylesheets/redesign/_card-action.scss
Simple
https://trello.com/c/zVDru6Z6/757-action-bar-open-space-at-bottom
=> Change the height spacing on actionbar

app/helpers/application_helper.rb, app/views/proposals/show_next.html.haml
Add helper to check for details view beta. Keep assets in the details page if list view is deactivated.
=> Create the condition for non-list_view_conditions to work

app/assets/javascripts/details/app.js, app/assets/javascripts/details/views/list/list_view.js, app/controllers/proposals_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.haml, app/views/proposals/index_next.html.erb, config/routes.rb, db/migrate/20160831150925_add_list_view_config_to_users.rb, db/schema.rb
Stores the List view datatable config on the user model.
https://trello.com/c/eWEDzESl/686-save-list-view-user-configuration-on-server
=> Store list view config on the user model

app/views/gsa18f/_header_links_next.html.haml, app/views/layouts/_header_nav_next.html.haml, app/views/ncr/_header_links_next.html.haml
https://trello.com/c/AV34XTwx/767-de-emphasize-reporting-link-in-left-nav
=> Made reports link normal link instead of button style

app/views/gsa18f/procurements/new_next.html.haml, app/views/ncr/work_orders/new_next.html.haml, app/views/proposals/details/_save_action.html.haml, spec/features/client_slug_authz_spec.rb
=> New request page fixes

app/assets/javascripts/search.js, spec/features/search_spec.rb
https://trello.com/c/3pxqJwki/771-advanced-search-open-by-default
=> Shows advanced options automatically on search

app/assets/stylesheets/redesign/_card-action.scss
Center cancel button on new request page
=> Center the cancel button

app/assets/javascripts/details/shell/action_bar_bridge.js, app/controllers/ncr/work_orders_controller.rb, spec/features/ncr/work_orders/post_approval_modification_spec.rb
Don't merge, just seeing if tests pass
=> testing the tests

app/assets/stylesheets/redesign/_list.scss.erb, app/views/shared/_search_form.html.haml
What: https://trello.com/c/QYMPGkCw/773-date-within-field-line-break
=> Adjusted style of date on search so its on one line

app/assets/stylesheets/common/search.scss, app/assets/stylesheets/redesign/_card-action.scss, app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/assets/stylesheets/webapp/proposal_list.scss, app/views/layouts/_scripts_next.html.haml, app/views/layouts/_sidebar_shared.html.haml, app/views/layouts/_styles_next.html.haml, app/views/layouts/application.html.haml, app/views/proposals/details/_request_details.html.haml, app/views/proposals/show_next.html.haml, app/views/shared/_search_form.html.haml, app/views/shared/_search_ui.html.haml
- Remove Requests menu item link https://trello.com/c/jV3fdsR6/770-remove-requests-menu-item-link
- Detail page: Layout rendering problem  https://trello.com/c/aJgHZE4w/753-detail-page-layout-rendering-problem
- Proposals page: layout issue on current design https://trello.com/c/BSKsMoCQ/747-proposals-page-layout-issue-on-current-design
- Shifting of content on page load https://trello.com/c/zCS8E21E/781-shifting-of-content-on-page-load
- Style conversion: proposal#new https://trello.com/c/PLw3eR9m/676-style-conversion-proposal-new
=> Remaining style changes for launch

app/assets/javascripts/details/views/list/list_view.js, app/assets/stylesheets/redesign/_card.scss.erb, app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/views/proposals/index_next.html.erb, app/views/shared/_search_ui.html.haml
- Remove the bug report text in "new request"
- Add transitions to how listview is loaded. Remove the FOUC and add user feedback.
=> Listview: Adding transitions to page load

app/views/proposals/details/_comment_list.html.haml
https://trello.com/c/3Ef39EmD/762-step-1-approval-appearing-twice-in-the-timeline
Simple fix to remove duplicate renders from appearing in the timeline
=> Remove duplicate events

app/views/proposals/details/_top_notification.html.haml, config/locales/views/en.yml
Functionality:
User clicks revert to old design
- Top bar shows survey link
- Ethnio screener displays for survey
Upon revisitin the old pages, top bar continues to show survey link.
=> Turned ethnio screener back on.

app/assets/images/chevron-down.svg, app/assets/stylesheets/redesign/_basic.scss, app/views/ncr/work_orders/_form_new.html.haml
https://trello.com/c/nc1T2rj9/633-not-to-exceed-needs-dropdown-arrow
=> Dropdown arrows

app/views/ncr/work_orders/_form_new.html.haml
Design was updated to remove certain fields from New Request page on NCR.
https://trello.com/c/7zvFavvO/798-object-field-soc-code-func-code-cl-are-displaying-when-submitting-a-new-request
=> Remove the unused fields in new requests

app/views/ncr/work_orders/_form_new.html.haml, app/views/ncr/work_orders/new_next.html.haml
Adds explicit labeling, aria attributes, field sets.
=> Update new request form to be more 508 compliant

app/assets/stylesheets/redesign/_sidebar-nav.scss.erb
Fix the mobile nav using the new sidebar.
https://trello.com/c/sAoljkQd
=> Fix navigation on mobile viewport

app/views/shared/_search_form.html.haml
Adds labels to the search menu form
=> Fixed labels on search menu

app/assets/stylesheets/redesign/_layout.scss
=> Correct the advanced search

app/views/layouts/_scripts_next.html.haml
Re-add the datatable JS files. Im not sure how this slipped by.
=> Re-add the datatables js files

app/decorators/gsa18f/event_decorator.rb, app/models/gsa18f/event.rb, app/models/gsa18f/event_fields.rb, app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/fields/_event_provider.html.haml, app/views/gsa18f/fields/_free_event.html.haml, app/views/gsa18f/fields/_title_of_event.html.haml, app/views/gsa18f/fields/_travel_required.html.haml, app/views/gsa18f/fields/_type_of_event.html.haml, db/migrate/20160923200153_add_fields_to_events_table.rb, db/migrate/20160923202931_change_event_column_names.rb, db/schema.rb
Add new fields, 
Renamed fields to match mockups
https://trello.com/c/wz8iIjdg/822-update-18f-event-fields-to-match-mockup
=> Update Events form to match mockups

app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/fields/_supervisor_id.html.haml
=> added select for supervisor

app/models/gsa18f/event.rb, db/migrate/20160927192531_add_gsa18f_talent_approver_role.rb, db/schema.rb
- Step 1: [PS] (Talent Approver)
- Step 2: [JX] (GSA18F Approver)
- Step 3: [Ops purchaser mailbox] (Ops Purchaser)
- Add role 'Talent Approver', assign PS the role in production
=> Create Training Requests approver chain

app/models/user.rb, app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/fields/_supervisor_id.html.haml
=> Limit supervisors to 18fers

app/assets/stylesheets/redesign/_card.scss.erb, app/views/gsa18f/events/_form_new.html.haml
=> added tool tips to event page

app/controllers/gsa18f/events_controller.rb, app/views/gsa18f/events/new_next.html.haml, db/chores/roles_conversion.rb
=> Added attachments to event form and added seed for new role

app/views/gsa18f/events/_form_new.html.haml, config/tables/proposals.yml, db/chores/roles_conversion.rb, db/schema.rb
Add columns for list view event fields.
=> Update the GSA18f list view

app/models/concerns/purchase_card_mixin.rb, app/models/gsa18f/event.rb, app/views/gsa18f/events/_form_new.html.haml
Checks form before submission to ensure fields are filled out
=> Add form validations

app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/views/gsa18f/_header_links_next.html.haml
TeamOps: Highlight left nav when on the Event form
https://trello.com/c/g4LNsNSG/839-teamops-highlight-left-nav-when-on-the-event-form
=> Create active new requests nav class

app/assets/stylesheets/redesign/_forms.scss, app/views/gsa18f/events/_form_new.html.haml, app/views/shared/_search_form_next.html.haml
Add tooltip for nsf field.
https://trello.com/c/7yShb1By/842-teamops-tooltip-for-nfs-form-copy-provided-by-pia
=> Add tooltip for nsf

app/models/concerns/purchase_card_mixin.rb, app/models/gsa18f/event.rb
If event is marked as free, can be submitted with amount.
If event price is 0, must be marked as free.
https://trello.com/c/0R570RDW/841-cost-per-unit-submits-as-0-0-when-putting-in-20000
=> Changed price logic for event,

app/views/gsa18f/events/_form_new.html.haml
=> add required fields to evnets form

app/assets/stylesheets/redesign/_card.scss.erb, app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/events/new_next.html.haml, config/locales/decorators/en.yml, spec/features/gsa18f/events/create_spec.rb, spec/features/gsa18f/events/edit_spec.rb
https://trello.com/c/K5812f97/857-team-ops-update-content-for-the-team-ops-form
=> Content updates and style tweaks.

app/views/proposals/index_next.html.erb
Table loading circle was showing non stop when table had no data. 
Table loading circle only loads now if the table has data
=> Loading circle only shows when table has data

app/assets/stylesheets/redesign/_forms.scss, app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/procurements/_form_new.html.haml, app/views/ncr/work_orders/_form_new.html.haml
Added asterisks to Procurement and work order forms.
=> Added asterisks to all three forms

app/assets/stylesheets/redesign/_card.scss.erb, app/models/gsa18f/event.rb
Change the text for the error labels and add styles.
=> Add css styles for error related labels

app/assets/javascripts/details/views/modal_card.js, app/assets/javascripts/reports.js, app/assets/stylesheets/redesign/_card-modal.scss, app/assets/stylesheets/redesign/_list.scss.erb, app/views/proposals/query.html.haml, spec/features/reports_spec.rb
Fix the report "Save the report" link.
=> Fix "Save the report"

app/views/home/home_redesign.html.haml
There was no login on the new homepage.
=> Added login to new homepage

app/presenters/tabular_data/column.rb, app/views/shared/formatter/_currency.html.haml, app/views/shared/formatter/_none.html.haml, config/tables/proposals.yml, spec/presenters/tabular_data/column_spec.rb
Create default fields of `n/a` and blank fields with `-`.
=> Proposals pages blank/not applicable

spec/features/proposals/index_spec.rb, spec/support/responsive_helper.rb
Add tests to the DataTable on `Proposals#index`.
=> Adding DataTable tests on index spec

app/views/ncr/work_orders/_form_new.html.haml
=> Associated work order field with input

app/helpers/application_helper.rb, app/views/layouts/_header_nav.html.erb, config.ru
Delete a couple comments erroneously left in and put cloud.gov vs. myUSA login behind an env. var
=> Clean up cloud auth

doc/emails.md, doc/overview.md
=> Add email documentation

app/views/home/home_redesign.html.haml
Now only the sandbox warning is hidden when in an ENV that has
that set to hide.
=> Conditional was hiding all warnings, not just the sand box warning

doc/production.md
Add instructions on user provided services.
=> Add deployment instructions

app/views/home/home_redesign.html.haml
small thing to make tests easier
=> add header id to nav for tests

doc/setup.md
Would love @nickbristow to take a look, as someone who recently had to do some of this setup.
=> Update docs for cloud.gov lovin

spec/features/proposals/index_spec.rb, spec/support/responsive_helper.rb
Tests were failing due to the order they were running. This attempts to address some of them. 
Specifically proposal/index_spec
=> make tests more reliable

app/admin/proposal.rb
Updates CSV download link on proposals admin page.
=> Adjusted CSV download on proosal admin to show all fields

app/admin/proposal.rb
Adds the Attachment files to the csv export
=> Add attachments to csv

doc/setup.md
... and add note about the weird login bug we're seeing.
=> Fix cg-fake-uaa config details

.env.example, .gitignore, doc/setup.md
These helped me get running locally (without using docker).
=> Updates to setup docs
