18F/C2

app/helpers/application_helper.rb, app/views/layouts/_communicart_header.html.erb
While testing, I realized the 'Back to main portal' link is showing up on the homepage as well as on the very page it links to. Added a quick way to handle this.
=> Conditionally display the portal link

app/views/layouts/_communicart_header.html.erb, config/routes.rb
Noticed that [this commit](https://github.com/18F/C2/commit/c783bb5e) didn't account for the route `/carts/index`. Simplified the route for the carts#index page by taking advantage of the existing `resources :carts` routes definition.
=> Simplified route to carts/index to work with c783bb5e

Gemfile, Gemfile.lock
Not in use right now... we can always re-add it if needed.
=> remove NewRelic gem

app/views/carts/_cart.html.erb
Debating about which layout I like best:
a)
b)
c) (in this commit)
d)
I don't have a sense of how long these descriptions will be on average, which I think would help us decide. The ones I saw were pretty short (not even a full sentence). @ericadeahl Thoughts?
=> [#86662046] display cart name on show page

app/controllers/home_controller.rb, spec/integration/set_user_after_login_spec.rb
This does not override a `return_to` if the page the user came from specifies one.
=> Redirect to carts after logging in

app/views/communicart_mailer/_reply_section.html.erb, app/views/communicart_mailer/cart_notification_email.html.erb
Mention commenting in the footer link for emails. This lets the user know how to comment.
=> Mention commenting in the footer link

app/controllers/carts_controller.rb, app/helpers/carts_helper.rb, app/models/cart.rb, app/views/carts/_cart_list.html.erb, app/views/carts/index.html.erb, spec/controllers/carts_controller_spec.rb, spec/helpers/carts_helper_spec.rb
In [a previous commit](https://github.com/18F/C2/commit/ce8d72294607d27eb72bf1457f22c7bb9dd753a6#commitcomment-9500132), @phirefly mentioned that we didn't have a spec for the helper method that gathered the email addresses to be displayed for each cart on the index page. Instead of verifying the existing functionality, this PR:
* Displays all carts the current_user is involved with, whether they are an approver, a requester, or an observer
* Lists the approver(s) who are being waited on for the cart to progress
This screenshot shows all the different states:
=> display detailed status on cart index page

app/controllers/application_controller.rb, app/controllers/communicarts_controller.rb, app/controllers/home_controller.rb, app/models/api_token.rb, app/models/user.rb, app/views/communicarts/approval_response.html.erb, spec/acceptance/cart_approval_from_link.feature, spec/controllers/communicarts_controller_spec.rb
When the approver clicks approve/reject from the notification email, 1019568 now logs that user in to the system via the token. With 3552747, they now get redirected to the normal cart show page, instead of rendering a different view at a different URL.
Checked w/ @cmc333333 and @NoahKunin [in #cybersec](https://18f.slack.com/archives/cybersec/p1422567486000148) to verify that this is ok, security-wise.
=> [#87250330] sign the user in via token

Gemfile, Gemfile.lock
We don't use this, and if we did want API docs, might as well point people to http://www.rubydoc.info/github/18F/C2/master.
=> remove sdoc gem

app/models/cart.rb, lib/linear_dispatcher.rb, spec/integration/cart_linear_approval_spec.rb, spec/lib/linear_dispatcher_spec.rb
If a cart gets approved or rejected, don't send emails to the "next" approver. I'm not restricting to "rejected" in case there's ever a way to approve the whole cart outside of the normal work flow.
=> 86218872: Add guard when sending emails in linear flow

app/assets/stylesheets/modules/shared/email_status.scss, app/helpers/communicart_mailer_helper.rb, app/models/cart.rb, app/views/shared/_email_status.html.erb
In anticipation of us reconciling the two treatments for linear/parallel status displays, I kept this simple by just removing the vertical line between approvals.
Before:
After:
=> [#87139776] Update icon image helper for emails to account for linear

app/models/approval.rb, app/models/cart.rb, lib/dispatcher.rb, lib/linear_dispatcher.rb, spec/lib/linear_dispatcher_spec.rb, spec/lib/parallel_dispatcher_spec.rb, spec/models/cart_spec.rb
Leverages #210 by sending an email on *cart* rejection, regardless of approval state. To do this, I split out approvals and rejections in the dispatcher class, instead of running all approval changes through the same method.
=> 87948180: Email sent on all rejections

db/migrate/20141214220050_create_proposals.rb, db/migrate/20150303052026_remove_flow_and_status_from_carts.rb, db/schema.rb
Before this change, I was getting an exception during the `up` part of the migration that `delegate` needs the associated object to be present... in other words, a :chicken: and :egg: problem of the Proposal needing to exist for every Cart in order for the associated Proposals to be created.
This solution is a bit of a hack, but it's certainly easier than writing raw SQL. @phirefly Mind checking out this branch locally and giving it a try?
=> fix Proposal migration to not rely on models

app/views/shared/_cart_properties.html.erb
This is a 508 fix, identifies the first cell in each row as a header cell.
=> Added scope = row to first cell in cart properties table

db/migrate/20150311092117_associate_api_tokens_with_approvals.rb
Two branches were developed in parallel. When applied sequentially, migrations was breaking. This patch fixes that, at least from a schema perspective. I've relatively confident that the logic is maintained, but if you could verify it's doing what you intended @afeld, that'd be wonderful.
=> Use proposal_id in this migration so that it can be ran in order

app/controllers/communicarts_controller.rb, app/decorators/cart_decorator.rb, app/mailers/communicart_mailer.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/carts/_cart.html.erb, app/views/carts/_cart_list.html.erb, app/views/communicart_mailer/_cart_mail.html.erb, app/views/communicart_mailer/_gsa18f_cart.html.erb, app/views/communicart_mailer/_navigator_cart.html.erb, app/views/communicart_mailer/_ncr_cart.html.erb, app/views/communicart_mailer/approval_reply_received_email.html.erb, app/views/communicart_mailer/approval_reply_received_email.text.erb, app/views/communicart_mailer/comment_added_email.html.erb, app/views/communicart_mailer/comment_added_email.text.erb, app/views/shared/_proposal_properties.html.erb, lib/dispatcher.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/cart_creation_without_approval_group_spec.rb
Also replaces the explicit `client_data_legacy` calls with similar delegated methods
Does not change functionality at all, but should allow a `name` field to be added with ease.
=> Use a (delegated) proposal field for cart name

Gemfile, Gemfile.lock, app/controllers/carts_controller.rb, app/models/approval.rb, app/models/cart.rb, app/models/concerns/proposal_delegate.rb, app/models/gsa18f/proposal_form.rb, app/models/ncr/work_order.rb, app/models/observation.rb, app/models/proposal.rb, app/models/user.rb, db/migrate/20150324015230_split_approvals.rb, db/schema.rb, lib/dispatcher.rb, spec/controllers/carts_controller_spec.rb, spec/factories/approval_groups.rb, spec/factories/approvals.rb, spec/factories/carts.rb, spec/features/18f_proposal_spec.rb, spec/features/ncr_work_orders_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/cart_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/cart_creation_without_approval_group_spec.rb, spec/requests/communicarts_spec.rb, spec/spec_helper.rb, spec/steps/approval_steps.rb, spec/support/requests.rb
`Approval`s no longer have a `role` – there is an equivalent `Observation` model, and a `requester_id` on the `Proposal` directly. These were the minimum required changes...I'll do some other cleanup in a follow-up PR.
=> [Delivers #89169198] split observers and requester from Approval model

app/serializers/approval_serializer.rb, app/serializers/ncr/work_order_serializer.rb, app/serializers/proposal_serializer.rb, app/serializers/user_serializer.rb, doc/api.md, spec/requests/api/ncr/work_orders_spec.rb
Follow-up to https://github.com/18F/C2/pull/269.
=> add WorkOrder#description attribute to API docs

circle.yml
Follow-up to https://github.com/18F/C2/pull/280 – was causing the build on `master` (but not other branches) to fail.
https://circleci.com/gh/18F/C2/727
We might [set up continuous deployment](https://docs.cf.18f.us/apps/continuous-deployment/) down the road, but we can discuss that separately.
=> remove deployment task from CircleCI

app/controllers/comments_controller.rb, app/mailers/communicart_mailer.rb, app/models/cart.rb, app/models/comment.rb, app/models/concerns/proposal_delegate.rb, app/models/proposal.rb, app/views/comments/index.html.haml, app/views/communicart_mailer/comment_added_email.html.erb, app/views/communicart_mailer/comment_added_email.text.erb, config/initializers/observers.rb, db/migrate/20150410142248_make_comments_only_reference_proposals.rb, db/schema.rb, lib/dispatcher.rb, lib/mail_preview.rb, lib/populator.rb, spec/controllers/comments_controller_spec.rb, spec/factories/comments.rb, spec/mailers/communicart_mailer_spec.rb, spec/requests/user_ownership_of_comments.rb
Builds on #294: https://github.com/18F/C2/compare/cart-auth...comment-auth?expand=1
* Adds a proposal field for comments, migrates existing comments to use that field, and removes the existing polymorphic field.
* Removes all references to said polymorphic field
* Adds authorization when creating comments
* Specs to test that authorization
=> [Delivers #91070178] Comment Authorization and connection to Proposal

app/controllers/communicarts_controller.rb, app/helpers/communicart_mailer_helper.rb, app/models/approval_delegate.rb, app/models/proposal.rb, app/models/user.rb, app/policies/proposal_policy.rb, db/migrate/20150415025447_create_approval_delegates.rb, db/schema.rb, doc/overview.md, spec/controllers/comments_controller_spec.rb, spec/factories/approvals.rb, spec/factories/carts.rb, spec/factories/users.rb, spec/features/ncr_work_orders_spec.rb, spec/helpers/communicart_mailer_helper_spec.rb, spec/models/user_spec.rb, spec/policies/proposal_policy_spec.rb, spec/requests/carts_spec.rb, spec/requests/communicarts_spec.rb, spec/steps/user_steps.rb
A User can have zero or more ApprovalDelegates, which are other users who can approve requests instead of them. Not loving the names I used for new models/columns/associations...very open to suggestions for alternatives. Open questions:
* If an approver has delegates, should they still be allowed to approve?
TODOs:
=> [Delivers #92448720] add notion of approval delegates

app/helpers/communicart_mailer_helper.rb, spec/helpers/communicart_mailer_helper_spec.rb
=> [Delivers #92876748] delegate notification emails shouldn't use URL to automatically login

app/controllers/communicarts_controller.rb, app/helpers/application_helper.rb, app/helpers/communicart_mailer_helper.rb, app/views/layouts/_communicart_header.html.erb, spec/acceptance/token_expiration.feature, spec/controllers/communicarts_controller_spec.rb, spec/helpers/communicart_mailer_helper_spec.rb, spec/mailers/communicart_mailer_spec.rb
A little janky, and not convinced about the approach, but it should work for now. The new flow, when logged out:
1. Delegate sees notification email
1. They click "Approve" from the email
1. If signed in:
* Yes: Approved.
* No:
1. They are redirected to the homepage, with a flash message saying they should log in
1. They click "Sign in with MyUSA"
1. After completing the OAuth flow, Approved.
Could use some manual testing as well if someone has a moment to try it.
=> prompt delegate to log in when approving

app/models/approval_delegate.rb
Just noticed that we have some duplicates in our database. Cleaned them up, but this will prevent new ones.
=> ensure that delegates can only be assigned to an approver once

app/controllers/communicarts_controller.rb, app/models/user.rb
Fixes two issues:
* The subsequent notification email was showing the delegator as having approved, not the delegate.
* The delegate wasn't being assigned in the case of rejection.
=> [Delivers #92876870] fix display of approver after a delegate approves

app/controllers/attachments_controller.rb, spec/controllers/attachments_controller_spec.rb
=> [Delivers #93440210] Friendly error message when attachment not present

app/controllers/attachments_controller.rb, app/policies/attachment_policy.rb, app/views/proposals/show.html.erb, config/routes.rb, spec/features/attachment_spec.rb, spec/policies/attachment_policy_spec.rb
Only the original uploader has permission to delete. Others don't see the "delete" link. Interface looks like:
=> [Delivers #93379244] Add ability to remove attachment (if the original uploader)

app/models/cart.rb, app/models/proposal.rb, app/views/default/_proposal_list.html.erb, app/views/default/_proposal_mail.html.erb, app/views/gsa18f/_proposal_list.html.erb, app/views/ncr/_proposal_list.html.erb, app/views/proposals/_review_status.html.erb, app/views/proposals/archive.html.erb, app/views/proposals/index.html.erb, spec/models/cart_spec.rb, spec/models/gsa18f/procurement_spec.rb
Removes the field from the Proposal model, which requires removing it from the default proposal listing template.
Went ahead and also removed a chunk in proposal_mail which isn't used by any existing client that also referenced this field.
=> Remove total_price from proposal interface

app/mailers/communicart_mailer.rb, app/models/gsa18f/procurement.rb, app/views/communicart_mailer/approval_reply_received_email.html.erb, spec/mailers/communicart_mailer_spec.rb
Here is the updated language
This used to say "Cart"
=> updated verbage for emails and proposal view

lib/tasks/import_users.rake
Call like:
```sh
rake import_users:team_yaml DIR=/path/to/data-private/team/
```
This did not include a CSV importer, but you can imagine how similar it'd be
=> [#93698442] Script for importing 18f users

app/models/ncr/work_order.rb, spec/factories/ncr/work_orders.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
Per the spec. Only thing I'm not too clear on is how rails handles empty values -- should I just be using `allow_nil` (and not testing the empty string)?
=> [Delivers #93639720] Validate RWA Number format

app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, spec/models/ncr/work_order_spec.rb
I didn't update for the `Cart#public_identifier` for backwards-compatibility reasons...not sure if it matters one way or another.
=> [Delivers #94113926] have public_identifier reference the proposal ID rather than the client model's

app/helpers/value_helper.rb
Displaying time for comments. Decided to display in ET since our first group is in that timezone. Also displaying the month, day, year in a more readable format since we have the space.
=> [Finished #93639564] Display the time for comments

app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/form.html.erb, spec/features/18f_procurement_spec.rb, spec/features/ncr_work_orders_spec.rb
Noticed on dev the discard changes was using work order id, when it needed proposal. 
Fixed that and added a test.
=> Fixed discard changes bug, add tests

app/views/gsa18f/_proposal_list.html.erb, app/views/ncr/_proposal_list.html.erb, spec/features/proposal_listing_spec.rb
While this wouldn't affect normal users so much, devs often have proposals of various types in their proposal list. Don't let that lead to an error.
=> [Delivers #94399790] Account for proposal lists including mixes of proposals

app/assets/stylesheets/common/communicarts.scss, app/controllers/concerns/token_auth.rb, app/controllers/proposals_controller.rb, app/helpers/communicart_mailer_helper.rb, app/policies/api_token_policy.rb, app/views/proposals/show.html.erb, config/routes.rb, spec/controllers/proposals_controller_spec.rb, spec/helpers/communicart_mailer_helper_spec.rb, spec/policies/api_token_policy_spec.rb, spec/steps/user_steps.rb
Using a GET-able URL when performing an action is problematic due to the confused deputy problem. Imagine a malicious requester crafted an email with an `img` with the src pointing to the approval url. If an approver loaded this "image", their browser would be acting on their behalf to approve the request.
This limits the surface area of this attack a bit by generally forcing a POST to occur. The exception is that the "approve" button in an email cannot be a POST and work correctly in most mail readers. Since this had to be a GET, we single out this exception by adding a special check that a token is present.
Continues to look like:
=> [Delivers #94019990] Be more careful when approving via GET

app/assets/javascripts/forms.js.coffee, app/assets/javascripts/required_for_submit.js.coffee, app/assets/stylesheets/common/communicarts.scss, app/assets/stylesheets/webapp/webviews.scss, app/views/proposals/show.html.erb, spec/features/attachment_spec.rb, spec/features/comment_spec.rb
This extends #344 by
* changing the style of disabled buttons so that it's obvious they're disabled
* abstracting the disable-checking code into a declarative style
* using that style to re-use the code for file submission
* adding tests
Also fixes a reference to a non-existent image. Looks like:
=> [Delivers #93639592] Disable submit when nothing is present

app/assets/stylesheets/common/button_to.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/webapp/webviews.scss, app/views/layouts/_header_nav.html.erb, app/views/proposals/show.html.erb, config/routes.rb, spec/controllers/home_controller_spec.rb, spec/features/attachment_spec.rb, spec/features/logout_spec.rb, vendor/assets/stylesheets/photon/style.css
Logging a user out used to require Javascript to convert a link into a POST request. When the home page was replaced, that magic disappeared, so logging out became broken.
Instead of fixing the Javascript, allow everyone visiting `/logout` to be logged out.
=> [Delivers #93997522] Don't rely on rails magic to POST/DELETE

config/application.rb, config/initializers/paperclip.rb
Just to keep the `application.rb` simple.
=> move Paperclip config to a standalone file

app/views/ncr/work_orders/form.html.erb
Make it just a bit more obvious that requests are BA80 when feature flagged
=> Added BA80 into title when feature flagged

app/assets/stylesheets/common/communicarts.scss, app/controllers/attachments_controller.rb, app/views/communicart_mailer/_attachments.html.haml, app/views/communicart_mailer/_comments.html.erb, app/views/communicart_mailer/approval_reply_received_email.html.erb, app/views/communicart_mailer/proposal_notification_email.html.erb, app/views/proposals/show.html.erb, config/routes.rb, spec/controllers/attachments_controller_spec.rb, spec/features/attachment_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/attachment_spec.rb
Adds an endpoint for viewing attachments. This will redirect after performing the appropriate authorization.
Then, in emails, include the attachments as links. Note: the links do _not_ automatically log the user in.
Looks like
=> [Delivers #95898302] Include attachments in proposal emails

app/controllers/api/ncr/work_orders_controller.rb
Was noticing a *ton* of SQL queries in the log when loading the NCR form...turns out it was doing a separate database call for every association :grin: This brings it down to a single query. On my local machine, loading http://localhost:3000/api/v1/ncr/work_orders.json with 841 WorkOrders:
**Before**
```
Completed 200 OK in 6391ms (Views: 5853.2ms | ActiveRecord: 535.2ms)
```
**After**
```
Completed 200 OK in 1274ms (Views: 1258.1ms | ActiveRecord: 13.5ms)
```
=> [Delivers #96626124] eager load the associated models for the WorkOrder API

app/controllers/application_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/controllers/use_case_controller.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/policies/ncr/work_order_policy.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
This allows approved work orders to be edited, adds a notice when editing such a work order, and tags edit comments as occurring post approval.
To do that:
* Added a mechanism for Work Orders (or other client-specific models) to override proposal's policies. In this case, this allowed Work Orders to be edited post approval while other client-specific models cannot be
* Adds a line to the "edited" comment noting that this edit took place after the proposal was approved
* Moved "edited" comment logic into Ncr::WorkOrder, as it's quite coupled at the moment
Looks like:
__Edit form__
__Email header__
__Web interface__
=> [Delivers #95888854] Allow Work Orders to be edited post approval

app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/navigator/_proposal_mail.html.erb, spec/features/ncr_work_orders_spec.rb, spec/features/proposal_listing_spec.rb, spec/models/proposal_spec.rb
Also make `WorkOrder#project_title` required. I know it wasn't in this sprint, but I had some time on the train and it was the easiest story to do offline :smile_cat:
=> [Delivers #96691408] make #name present for all Proposals

app/assets/javascripts/filter.js.coffee, app/assets/stylesheets/webapp/ncr.scss, app/assets/stylesheets/webapp/webviews.scss, app/controllers/feedback_controller.rb, app/mailers/communicart_mailer.rb, app/views/feedback/create.html.haml, app/views/feedback/index.html.haml, app/views/home/index.html.haml, app/views/layouts/application.html.erb, config/routes.rb, public/404.html, public/422.html, public/500.html, spec/controllers/feedback_controller_spec.rb, spec/features/return_to_spec.rb
Also tweaks the logic around js filters to allow for logic when an option is _not_ selected. There are currently no links to this form.
=> [Delivers #93381468] Add an endpoint for feedback, along with its form

app/views/communicart_mailer/approval_reply_received_email.html.erb, app/views/communicart_mailer/comment_added_email.html.erb, app/views/communicart_mailer/proposal_created_confirmation.html.erb, app/views/communicart_mailer/proposal_notification_email.html.erb, app/views/communicart_mailer/proposal_observer_email.html.erb, app/views/layouts/communicart_mailer.html.erb
Also moves the `body` tag into the containing template.
=> [Delivers #93381468] Add link to feedback in mail messages

Gemfile.lock, app/models/ncr/work_order.rb, app/views/ncr/work_orders/form.html.erb, config/locales/en.yml, db/migrate/20150620004844_add_billing_fields_to_work_orders.rb, db/schema.rb, spec/features/ncr_work_orders_spec.rb, spec/features/search_spec.rb, spec/models/ncr/work_order_spec.rb
Easier to understand the spec changes [ignoring whitespace](https://github.com/18F/C2/pull/408/files?w=1).
---
=> [Delivers #97070798] add budget-related fields to work order form

.env.example, spec/controllers/gsa18f/dashboard_controller_spec.rb, spec/rails_helper.rb
Updated to fix test failures on master. 
Oddly, I noticed that only the `controller` type is needed to be explicitly mentioned. model and feature specs appear to be loading EnvironmentSpecHelper just fine.
=> Fix master failure 20150622

app/policies/ncr/work_order_policy.rb, app/policies/proposal_policy.rb, app/views/ncr/work_orders/form.html.erb, spec/features/ncr_work_orders_spec.rb, spec/policies/ncr/work_order_policy_spec.rb, spec/policies/proposal_policy_spec.rb
Also added a header around the budget fields.
=> [Delivers #97070798] allow approvers to edit WorkOrders

app/assets/javascripts/selectizer.js.coffee, app/views/ncr/work_orders/form.html.erb, spec/features/ncr_work_orders_spec.rb, spec/features/search_spec.rb
This converts the select field for buildings into a text field (like vendor). The list of entries that it searches over is pre-populated to include all known buildings (i.e. the static list) + any additional buildings that have been used in previous requests.
=> [Delivers #94434346] Allow Custom Buildings

app/views/communicart_mailer/_email_reply.html.erb, spec/views/communicart_mailer/_email_reply.html.erb_spec.rb
Paired with @afeld 
When a requester modifies a request that has already been approved, the approver that has already taken action gets an email. This email does not require action (i.e. we do not display an 'Approve' button), but we still display `Or Send a Comment`.  Change this link to say `View this request.`
=> [Delivers 94714266] link text to requests in emails

lib/tasks/cf.rake, manifest.yml
App continues to work when deployed to dev and the output from `cf push` indicates that the migration script is ran. However, we'll want to wait until there's an actual migration to confirm.
=> [Delivers #94419078] Add scripts/manifest so that cloud foundry will run migrations on deploy

app/assets/stylesheets/modules/shared/email_status.scss, app/helpers/communicart_mailer_helper.rb, app/views/shared/_email_status.html.erb
Bypass the stripping of full domain url for css images that need to display within emails; temporary workaround pending updates to roady-rails and likely email design updates.
=> 97171464 fix email icons

app/assets/stylesheets/webapp/webviews.scss, app/views/gsa18f/procurements/form.html.erb, app/views/ncr/work_orders/_ba_80_fields.html.haml, app/views/ncr/work_orders/form.html.erb
Adds (using CSS) a little asterisk to indicate required fields.
Looks like:
=> [Delivers #92032848] Mark required fields

vendor/assets/stylesheets/photon/style.css
This fixes a pet peeve of mine with the Photon template you guys are using. There's a nice dotted underline for the links, but when you hover over it, that line is replaced with a solid line at a different vertical offset. I found this pretty jarring / annoying. I got rid of the text decoration on :hover and replaced it with a thicker, solid bottom border.
If you guys didn't mind the original styling or just don't want to start messing with Photon, no hard feelings.
=> Minor UI tweak: link hover now less jarring

app/assets/javascripts/selectizer.js.coffee, spec/features/ncr_work_orders_spec.rb
Selectize now splits on `XxxxxXXxxxxX` which has a far less likely error rate than splitting on `,`
=> Updated test to check for , updated selectizer options

app/controllers/use_case_controller.rb
The message that pops up when no changes are made to the work order, is now in a red error box as requested @phirefly
=> Changed 'no changes' message to red

app/controllers/ncr/work_orders_controller.rb, app/models/ncr/work_order.rb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/factories/ncr/work_orders.rb
Originally to resolve a 500 when loading the "edit" screen, I found a deeper issue around editing emergency work orders. That'll take a deeper dive and is not a priority, so we'll swing back to it; in the mean time, I fixed the immediate 500 and added some pending tests.
=> [#97405884][#98775964] Editing Emergencies

app/models/ncr/work_order.rb, config/locales/en.yml, spec/features/ncr_work_orders_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/ncr/work_order_spec.rb, spec/support/environment_spec_helper.rb, spec/support/features.rb
It does this by reusing `self.organization.code` and applying a regex for buildings.
Also updated some specs which were testing the executing environment via `with_env_vars`, an extension of `with_env_var`.
=> [#96904782] NCR email subject should only include codes

app/policies/ncr/work_order_policy.rb, spec/features/ncr_work_orders_spec.rb, spec/policies/ncr/work_order_policy_spec.rb
Just adds another OR clause to permissions checking.
=> [Delivers #98941214] Allow observers to modify ncr requests

app/controllers/feedback_controller.rb, app/views/feedback/index.html.haml, spec/controllers/feedback_controller_spec.rb
For logged in users, continues to look like:
For non-logged in users, looks like:
=> [Delivers #98953098] Add an email field to feedback form

app/views/ncr/work_orders/form.html.erb, spec/features/ncr_work_orders_spec.rb
We were generating a select box for approving official, but not providing a blank option. This meant that the first time a user filled out an entry, they were defaulting the approving official to the first user in the drop down.
=> [Delivers #98958450] Start with the approver selection blank

app/controllers/ncr/work_orders_controller.rb, app/models/ncr/work_order.rb, app/views/ncr/work_orders/form.html.erb, spec/controllers/ncr/work_orders_controller_spec.rb, spec/features/ncr_work_orders_spec.rb
Users can no longer switch requests between emergency and non-emergency status, as this messes up approvals and observers.
=> [Delivers #98775964] Emergency fields is disabled when editing

Gemfile, config/newrelic.yml, config/puma.rb
We had a [configuration](https://github.com/puma/puma/issues/128#issuecomment-21050609) that worked for an older version of the newrelic gem; according to the [current docs](https://docs.newrelic.com/docs/agents/ruby-agent/troubleshooting/new-relic-puma) this is no longer required.
Tested by pushing to staging; started logging almost immediately.
=> [#Delivers 98973752] Use default puma/newrelic config as it works out of the box

doc/setup.md
I have setup C2 twice now, and both times it was necessary to put in the proper Redirect_URI in the MyUSA application configuration. Also, docs should reflect simplified database configuration.
=> Updating setup doc to include MyUSA redirect uri and DATABASE_URL

app/views/layouts/_header_nav.html.erb, spec/features/link_to_new_proposal_spec.rb
Displays no default client link. 
If it looks good, please indicate a ship but please *no merge* until @phirefly has verified all ncr users have the correct client_slug.
=> Remove default NCR navlink

app/assets/stylesheets/common/header.scss, app/assets/stylesheets/common/sandbox_banner.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/webapp/webviews.scss, app/views/home/index.html.haml, app/views/layouts/_communicart_header.html.erb, app/views/shared/_sandbox_warning.html.haml, spec/features/sandbox_warning_spec.rb
"As a SANDBOX USER, I can see a reminder that the website is a sandbox so that I don't accidentally make live requests."
=> [Delivers #98910592] warning banner for sandbox sites.

app/assets/stylesheets/common/communicarts.scss, app/assets/stylesheets/modules/shared/email_status.scss, app/controllers/concerns/token_auth.rb, app/mailers/communicart_mailer.rb, app/policies/proposal_policy.rb, app/views/help/proposal_process.md, app/views/proposals/show.html.erb, doc/overview.md, lib/dispatcher.rb, lib/linear_dispatcher.rb, lib/mail_preview.rb, spec/features/18f_procurement_spec.rb, spec/features/ncr_work_orders_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/policies/proposal_policy_spec.rb
Split out from #454, this removes references to the rejected state from our code base.
=> Remove 'rejected' state completely

app/assets/stylesheets/common/header.scss, app/assets/stylesheets/common/sandbox_banner.scss, app/assets/stylesheets/common/static.scss, app/assets/stylesheets/home.scss, app/assets/stylesheets/modules/layouts/header_nav.scss, app/assets/stylesheets/webapp/webviews.scss
Fixes a css bug that was causing the frontpage nav to show up an unreadable dark blue instead of white. Also moves the header nav css into its own stylesheet.
Paired with @afeld.
Before the fix:
After:
=> Frontpage nav css fix

app/views/gsa18f/_proposal_list.html.erb, app/views/ncr/_proposal_list.html.erb, spec/features/proposal_listing_spec.rb
Fixes a bug where the requester email address is hidden in the "my requests" table for users with a client slug set.
=> [Delivers #99321148] Show requester in request list for client-specific users

lib/populator.rb, spec/controllers/attachments_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/proposals_controller_spec.rb, spec/factories/gsa18f/procurements.rb, spec/factories/ncr/work_orders.rb, spec/factories/proposals.rb, spec/features/attachment_spec.rb, spec/features/comment_spec.rb, spec/features/display_status_spec.rb, spec/features/ncr_work_orders_spec.rb, spec/features/version_check_spec.rb, spec/lib/dispatcher_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/models/attachment_spec.rb, spec/models/comment_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/models/proposal_spec.rb, spec/policies/attachment_policy_spec.rb, spec/policies/proposal_policy_spec.rb
Split out from #454 , this updates the proposal factory with specific traits for parallel and serial approvals. Also fixes some cruft in the procurement spec, which wasn't testing what it should have been.
=> Split parallel and serial proposal approvers

app/models/approval.rb, db/migrate/20150721205524_add_approved_at_to_approvals.rb, db/schema.rb, spec/factories/approvals.rb, spec/helpers/communicart_mailer_helper_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/models/approval_spec.rb, spec/views/communicart_mailer/_email_reply.html.erb_spec.rb
Split from #454, this creates an `approved_at` field for approvals. The field is set when the approval enters the approved state. Also backfills existing data.
Also simplifies options on the approval factory (rather than setting non-useful defaults).
=> Add materialized "approved_at" field to approvals

app/assets/stylesheets/common/sandbox_banner.scss, app/views/home/index.html.haml
• Moved sandbox banner after the head tag
• Added some CSS to deal with some Photon overriding on the homepage. This fixes the font size problem on the homepage.
Old with small font size:
Current font sizes on prod:
Font sizes with these changes
:
=> Added minor css tweaks to deal with Photon overrides on the homepage

app/views/proposals/index.html.erb, spec/features/proposal_listing_spec.rb
Request that are cancelled no longer show in the completed list.
=> Cancelled request no longer show in completed

app/views/proposals/show.html.erb
Displays the requested date on the request detail page.
=> [Delivers #99298112] show submitted date

spec/decorators/proposal_decorator_spec.rb, spec/factories/ncr/work_orders.rb, spec/features/cancel_spec.rb
For the cancel specs, my guess is that the multiple `login_as` calls for certain specs was the problem, but I'm not entirely sure. Re-ran the entire suite multiple times with
```bash
n=0
until [ $n -ge 5 ]
do
bundle exec rspec || break
n=$[$n+1]
done
```
=> [Delivers #99336494] fix flaky specs

app/models/approval.rb, app/models/approvals/individual.rb, app/models/concerns/proposal_delegate.rb, app/models/gsa18f/procurement.rb, app/models/proposal.rb, app/serializers/approvals/individual_serializer.rb, db/migrate/20150724144605_add_type_to_approvals.rb, db/schema.rb, spec/factories/approvals.rb, spec/factories/proposals.rb, spec/features/comment_spec.rb, spec/features/display_status_spec.rb, spec/lib/dispatcher_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/models/comment_spec.rb, spec/models/proposal_spec.rb, spec/steps/approval_steps.rb, spec/steps/user_steps.rb
Split out from #454 
This doesn't change too much of `app` - it migrates all approvals to the `Approvals::Individual` subclass and removes all but one entry point for setting the approval chain.
Most of the code updates are to the specs, which were heavy users of `add_approver`
=> [#98024644] Approvals::Individual and a single approval chain entry point

doc/production.md, manifest.yml
Moves the non-sensitive Cloud Foundry configuration into a config file, meaning that it's now version controlled.
=> add manifest file

app/controllers/proposals_controller.rb, app/views/shared/_table.html.haml, lib/proposal_search.rb, lib/tabular_data/container.rb, spec/controllers/proposals_controller_spec.rb, spec/features/tabular_data_spec.rb, spec/lib/tabular_data/container_spec.rb
* Remove the ability to sort on the search page; we can rely on the search ranking
* Simplify `ProposalSearch` so that it doesn't have a separate projection (and hence doesn't need to `select *`)
The latter resolves an explosion when searching.
~~This needs tests.~~ @annalee I _think_ this might resolve #100944736 too but I'm not positive.
=> [Delivers #100901060, Possibly #100944736] Interaction b/w TabularData and ProposalSearch

.rubocop.yml
Yesterday, I enabled Code Climate to run on our pull requests, which runs [Rubocop](https://github.com/bbatsov/rubocop) by default. Ruboop is aggressive, but luckily Code Climate only shows the "offsenses" on changed lines with pull requests. Example:
https://codeclimate.com/github/18F/C2/pull/538#style
Explicitly excluded some Cops (ones that I saw in the page above and don't agree with – will probably want to add more as we go), but used `--auto-gen-config` to generate the `.rubocop_todo.yml` to "zero the scale" (so to speak).
Would like to get this in before #538.
=> add a Rubocop configuration file

app/decorators/proposal_decorator.rb, app/models/approval.rb, app/models/approvals/individual.rb, app/models/proposal.rb, app/models/user.rb, app/policies/proposal_policy/scope.rb, lib/query/proposals.rb, spec/lib/query/proposals_spec.rb, spec/models/approval_spec.rb, spec/models/approvals/individual_spec.rb, spec/policies/proposal_policy/scope_spec.rb
Issue introduced in #538.
More importantly, converted the queries to Arel, which makes the various conditions for the subsets of Proposals composable. http://www.scuttle.io/ was super helpful in doing the conversion. Want to play around with them more to try and make them more readable, but I think they're ok for now.
Both pull requests are in service of https://www.pivotaltracker.com/story/show/99002900.
=> fix client admins not being able to see all Proposals they are involved with

app/controllers/api/users_controller.rb
This should fix a flaky test, which appeared in https://circleci.com/gh/18F/C2/1693.
=> ensure that GET /api/v1/users.json is sorted by ID

app/controllers/proposals_controller.rb, lib/query/proposal/listing.rb, spec/lib/query/proposal/listing_spec.rb
In other words, app/client admins won't see _all_ Proposals on that page.
=> [Delivers #99002900] only display Proposals a user is involved with on /proposals

app/views/help/approver_out_of_office.md, app/views/help/delegated-request.md, app/views/help/index.html.haml, app/views/help/modifiying_requests.md, app/views/help/new_work_order.md, app/views/help/printing.md, app/views/help/proposal_process.md, app/views/help/requests_over_3000.md, app/views/help/verbal_ntp_requests.md, app/views/layouts/help.html.haml
- Retitled FAQ to Help where relevant. Format-independent title that’s
consistent w/ URL may be easier to work with over the long term. Also
keeps breadcrumb, page title, and nav title consistent.
- Added some questions to cover additional issues.
- Edits to make language slightly more specific and/or active.
@phirefly 
There are a couple other help needs, like formatting instructions for submissions, that I think are better served elsewhere. I will file those as issues instead.
=> Edits to Help content

Gemfile, Gemfile.lock, Procfile, app/controllers/feedback_controller.rb, app/mailers/communicart_mailer.rb, bin/delayed_job, config/application.rb, config/initializers/delayed_job.rb, db/migrate/20150819172749_create_delayed_jobs.rb, db/schema.rb, doc/setup.md, lib/clock_tasks.rb, lib/dispatcher.rb, lib/dispatcher/class_methods_mixin.rb, lib/ncr_dispatcher.rb, spec/features/observer_spec.rb, spec/lib/dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/mailers/report_mailer_spec.rb
This takes the sending of emails out of the request cycle, which has a few benefits:
* Response times will be faster
* Emails failing to send will no longer fail the overall request
* Failed email sends will be retried, and if those fail, we have a record of it
Updated gems, as well.
=> [Delivers #101210264] background email sending

app/views/layouts/_analytics.html.erb
This specifies an `agency` of `GSA` for DAP reporting, and adds a missing `forceSSL` flag to GA settings.
=> Specifies DAP agency field, adds forceSSL

app/mailers/communicart_mailer.rb, lib/dispatcher.rb, lib/mail_preview.rb, lib/ncr_dispatcher.rb, spec/lib/dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb
Don't _love_ the idea of the mailer being responsible for this, but it centralizes the logic that's needed for the mail to be sent successfully.
Came up because the delayed email sends are failing on staging because they don't have a token (which should have been created before, but is now missing for whatever reason). This sidesteps the issue of creating the token if it doesn't exist right before the email is sent.
=> move API token creation into the mailer

Gemfile, Gemfile.lock, config/initializers/peek.rb
...which I just made! In short, this will allow us to see the state of our background worker queue when using the app. See the repository for more info:
https://github.com/18F/peek-delayed_job
=> add DelayedJob plugin for peek

doc/production.md, script/deploy, script/release
As discussed in Slack, `cf-blue-green` doesn't work for C2 at the moment: it doesn't start the scheduler and worker processes the way it should, due to https://github.com/18F/cf-blue-green/issues/18.
Also adds a `./script/deploy` command, so that the deployer shouldn't have to think about the underlying deploy command(s).
=> temporarily remove use of cf-blue-green

app/views/proposals/query.html.haml, app/views/proposals/show.html.haml
In response to [remove search box from `show` templates](https://www.pivotaltracker.com/story/show/95181828) and [Ability to clear out existing search results](https://www.pivotaltracker.com/story/show/95162638). 
I am not sure this an exact solution to the latter story. The "Clear search terms" link just leads back to `/proposals`, effectively clearing the search box.
I am also pretty sure my Haml can be improved. Thanks for taking a look! :)
=> Search UI modifications

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/helpers/report_helper.rb, app/helpers/value_helper.rb, app/mailers/report_mailer.rb
Use the browser's timezone for displaying timestamps in the browser. Use UTC for dates and times in emails, and make the timezone explicit.
https://www.pivotaltracker.com/story/show/102087948
=> 102087948 timestamps

app/helpers/ncr/work_orders_helper.rb, app/views/ncr/work_orders/form.html.erb, spec/features/ncr_work_orders_spec.rb, spec/models/ncr/work_order_spec.rb
Make a new vendor string value sticky on form error.
https://www.pivotaltracker.com/story/show/101217598
NOTE there is no accompanying test for this because (a) I could find no prior art in spec/ for testing HTML responses and (b) there was no regression apparent in existing tests. I would be happy to blaze that trail (testing HTML responses) if folks think it is needed.
=> 101217598 vendor form fix

app/helpers/value_helper.rb
The helper method that humanizes the timestamp was operating on a string which lacked the timezone, so it assumed UTC. Passing it a Time object instead, with proper localized timezone, should help it Do The Right thing in its date math.
=> 102087948 timezone coercion

db/migrate/20150831193037_move_observations_to_roles.rb, db/schema.rb
Follow-up to #581.
`#each_row` returns each row as an array, whereas `#each` returns them as a Hash :facepalm: This migration is getting on my nerves.
=> use #each instead of #each_row in migration

app/models/approval.rb, lib/dispatcher.rb, spec/lib/dispatcher_spec.rb
Story: https://www.pivotaltracker.com/story/show/100733040
Only send cancellation emails to non-pending approvers.
=> cancellation emails

.rubocop.yml, app/models/ncr/work_order.rb, lib/dispatcher/class_methods_mixin.rb, lib/ncr_dispatcher.rb, spec/lib/ncr_dispatcher_spec.rb, spec/models/ncr/work_order_spec.rb
Relevant story: https://www.pivotaltracker.com/story/show/100957216
I'm not convinced that this doesn't affect *too many* notification cases, despite that tests are passing (including new test).
=> do not notify user with email when they update a request

app/models/ncr/work_order.rb, spec/models/ncr/work_order_spec.rb
The public ID field already uses the fiscal_year method to set the work order's id based on the current fiscal year. Added tests to the method and we should be good to go.
Paired with @afeld.
=> [Delivers #101217754] Adding tests for the work_order.fiscal_year method

lib/ncr_dispatcher.rb, spec/lib/ncr_dispatcher_spec.rb
It appears that requesters were only getting notified on comments, not changes, to a proposal. This PR adds code + test to verify requesters are getting notified when a proposal changes.
=> [Delivers #100957216] notify requester on proposal change

db/seeds.rb, doc/setup.md, manifest.yml, script/server_start, script/start
Addressing an issue raised in #602.
For any changes to `seeds.rb`, we want to ensure that those records are created on our various environments, without needing to duplicate the seeding in a migration. This change makes a `start` script, which should be used on development machines or servers, which
* Runs migrations
* Runs seeds
* Starts the server with the background workers
=> run `rake db:seed` on deploy

script/deploy
Per anecdote from recent deploy mishap, require explicit appname in `script/deploy`.
=> require appname on deploy, to avoid deploying everywhere

doc/production.md, script/deploy, script/release
:zero: :clock10: :rocket: :zap: :tada: 
Everyone please run the following before we merge this:
```bash
brew update
brew upgrade cloudfoundry-cli
cf --version
npm update -g cf-blue-green
npm list -g --depth=0 2>&1 | grep cf-blue-green
```
Check the box next to your name below once you're all good.
Thanks!
/cc https://github.com/18F/cf-blue-green/pull/22
=> re-enable zero-downtime deployment

.env.example, config/database.yml
add new TEST_DATABASE_URL env variable, and default to explicit 'url' syntax to avoid clearing db when DATABASE_URL is set explicitly.
=> Test database config

manifest.yml, script/server_start
Tested on dev:
It's particularly helpful in the graph views, where the deployments show up as vertical lines:
Not that interesting here since there's no real traffic to dev in the middle of the night, but you get the idea.
=> keep track of deployments in New Relic

doc/team_practices.md
Lots of auto whitespace deletion, but the add is about pairing/verbal thumbs ups:
https://github.com/18F/C2/compare/add_to_team_practices?expand=1#diff-00437664927745e664dbc25f87a61ecdR61
=> Added notes about shipping code when pairing or getting verbal approval

app/models/gsa18f/procurement.rb, app/views/gsa18f/procurements/form.html.erb, config/data/18f.yaml, config/tables/proposals.yml, db/migrate/20150924162801_change_procurement_urgency_to_integer.rb, db/schema.rb, spec/factories/gsa18f/procurements.rb, spec/features/18f_procurement_spec.rb, spec/features/tabular_data_spec.rb
Allows gsa18F `Procurement`s to be sorted by `urgency`in the table at /proposals, and changes the type of `urgency` from `:string` to `:integer` to support sorting. 
:warning: Includes a migration to update existing urgency values to integers, but only for the 3 urgency strings currently in 18f.yaml. Please confirm that only these 3 values exist before running the migration in production. Happy to update the migration if there are other values.
*Context/notes to self:*
- If a user can have multiple clients (i.e. work w/ multiple orgs/agencies), /proposals should probably become a tabbed view. Sorting by urgency is unlikely to make sense across clients. 
- Spacing out the integer values (10/20/30 vs 1/2/3) is so folks can add new urgency levels later w/o a data migration.
- With shorter, …
=> [Delivers #98787550] sort gsa18f procurements by urgency

app/models/ncr/work_order.rb, lib/ncr/reporter.rb, spec/models/ncr/work_order_spec.rb
fixes bug reported in QA for https://www.pivotaltracker.com/story/show/102267428
=> [Delivers #102267428] pick highest pending approver on the stack

app/assets/stylesheets/webapp/proposal_list.scss, app/views/ncr/work_orders/form.html.erb, app/views/proposals/index.html.erb, spec/features/ncr_work_orders_spec.rb
1) On the new request from, moves the 'Service Center' text into the label for the related field. This is based on feedback received while doing training sessions.
2) Layout fixes on the My Requests page
Before:
After:
=> Minor ui fixes

app/models/concerns/proposal_delegate.rb, app/models/ncr/work_order.rb
Stumbled across while reviewing #666.
=> use existing logic to retrieve the current approver on a WorkOrder

manifest.yml
The impetus here is that we are setting up Mandrill in #640, which requires us to pick a domain for our transactional emails to send to/from. I didn't want to set it up with @cap.18f.gov and have to re-configure everything when we switch the site from https://cap.18f.gov to https://c2.18f.gov, so went with the latter. Because users will see this new domain in their inboxes, I'm afraid of them typing it in the browser and getting a 404.
This PR simply makes https://c2.18f.gov point `c2-prod`, though we don't need to advertise this fact.
Since this is a production-only change, we can't _really_ QA it beforehand, but I tested the equivalent change for `c2-staging`:
```yaml
hosts:
- c2-staging
- c2-staging-2
```
then ran
```
$ cf push c2-staging
...
$ curl -I https://c2-staging-2.18f.gov …
```
=> [Delivers #104013748] add c2.18f.gov as a production domain

app/models/ncr/work_order.rb
Story: https://www.pivotaltracker.com/n/projects/1149728/stories/104981410
resurrect the not-nil check for approving_official and default to system_approver_emails when nil (not sure in what legit biz case it would be undefined)
=> [Delivers #104981410] fix broken budget email report

.env.example, Gemfile, Gemfile.lock, config/environments/development.rb, doc/setup.md
Asset logging, e.g.
```
Started GET "/assets/icon-logout.png" for ::1 at 2015-10-08 13:18:47 -0400
```
is basically just noise, so added a gem that silences it. Also removed the now-not-really-useful `ASSETS_DEBUG` config flag, which was [apparently](https://github.com/18F/C2/pull/618/files#r41514899) added to reduce the number of asset logging messages received. Now it's a non-issue, and it makes JS debugging easier since they appear in separate files.
=> silence logging of requests for assets in development

manifest.yml
this is necessary until 18F CF buildpacks are updated.
=> add explicit buildpack so that Ruby 2.2.3 is supported on cloud.gov

.about.yml
Currently, the .about.yml file parsing is breaking on the empty dash records for`milestones` and `blog`. Removing the records, i.e. going from this state:
```
milestones:
-
...
blog:
-
```
to:
```
milestones:
...
blog:
```
corrects the issue.
=> Correcting the formatting of the .about.yml file.

app/views/help/requests_over_3000.md
Just one question, but it needed care:
- changes limit to $3500
- specifies FY 2016 (avoids confusion re older requests)
- adds link to procurement request form
- fixes a small typo
=> Updates help language to reflect increased FY 2016 limit

app/controllers/attachments_controller.rb, app/controllers/comments_controller.rb, app/controllers/proposals_controller.rb, app/mailers/concerns/proposal_conversation_threading.rb, app/models/comment.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/views/proposals/cancel_form.html.erb, lib/dispatcher.rb, spec/controllers/comments_controller_spec.rb, spec/factories/proposals.rb, spec/features/cancel_spec.rb, spec/features/observer_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/proposal_spec.rb
* When a proposal is cancelled, we send a cancellation email to
requester and approvers
* Extra email about cancellation comment is repetitive
* Fixes #99273060
=> [Fixes #99273060] Suppress comment email on proposal cancellation

.env.example, config/database.yml, config/puma.rb, doc/envvars.md, manifest.yml
I've been seeing the app hanging and `502 Bad Gateway` errors when trying to load the site a few times recently, and yesterday at 5pm ET the app was `down` for no particular reason. After looking at the top graph in New Relic, I believe the problem is a memory constraint during garbage collection.
There may be other issues that are causing us to consume that much memory, but increasing the instance capacity and having a backup instance in production should at least keep it from crashing. See the individual commits for more explanation of the changes.
=> improve availability of production

.rubocop.yml
CodeClimate appears unhappy with this directive. Maybe a version issue?
```
undefined method `each_key' for "EnforcedStyle:double_quotes":String
```
FWIW, Rubocop does not require double quotes by default, on purpose: https://github.com/bbatsov/rubocop/issues/1615
=> ruboconf directive for double_quotes fails on CodeClimate

app/assets/javascripts/filter.js.coffee, app/assets/javascripts/flash_errors.js.coffee, app/assets/javascripts/required_for_submit.js.coffee, app/assets/javascripts/selectizer.js.coffee, coffeelint.json
Building on https://github.com/18F/C2/pull/695.
Easiest way for me to figure out which rules I do/don't agree with is to run it locally. My process:
1. Changed all of the `level`s to `error` (i.e. enabled all of the rules).
1. Ran `coffeelint app/assets/javascripts/`.
1. For lint errors I agreed with, made the appropriate fix(es). For those I didn't, changed the config value to `ignore`.
1. Committed as 65124c3
1. Removed the config options that matched the defaults (044a329)
`coffeelint app/assets/javascripts/` passes locally.
=> tweak CoffeeLint config

doc/team_practices.md
* `script/deploy` failed for me, perhaps because of blue-green
* Ideally, we should indicate to others when we are QAing something
=> Updates to Team Practices doc

app/mailers/application_mailer.rb, spec/mailers/communicart_mailer_spec.rb
Since our new production sender email address is *inbox@c2.18f.gov* without any human-readable name, the sender appears as 'inbox' when viewing the message. Let's make it friendlier.
=> C2 from email address

app/assets/stylesheets/common/form-control.scss
Just something I stumbled across while working on #656.
https://github.com/postcss/autoprefixer/issues/44#issuecomment-41183918
=> allow autoprefixer to handle the cross-browser placeholder styles

app/models/proposal.rb, config/locales/en.yml, spec/models/proposal_spec.rb
Also, adding an observer _without_ specifying a reason should not create a comment.
=> [Delivers #104865396] Ensure adding observer with reason creates an update comment

app/decorators/ncr/work_order_decorator.rb, lib/ncr/reporter.rb, spec/decorators/ncr_work_order_decorator_spec.rb, spec/lib/ncr/reporter_spec.rb
Story: https://www.pivotaltracker.com/story/show/106019438
This makes the CSV logic match the in-line report email logic.
=> [Delivers #106019438] CSV should respect proposal status when picking approver

.about.yml
The extra dash made it look like two items, one without anchor text, and one without a URL.
cc: @afeld @pkarman @openbrian
=> Remove extra dash from beginning link item

app/models/user.rb, lib/dispatcher.rb, lib/role_picker.rb, spec/features/cancel_spec.rb
* Active observers are observer who are not approver or requester
* Previously, were not receiving an email
* Story: https://www.pivotaltracker.com/story/show/99273060
=> [Delivers #99273060] Send cancellation conf email to active observers

app/admin/dashboard.rb, app/admin/job.rb, app/models/delayed_job.rb, spec/features/active_admin_spec.rb
Story: https://www.pivotaltracker.com/story/show/102133698
Adds `delayed_jobs` to the `/admin` UI.
It seems like there could/should be a way to monitor queue length with New Relic, but I'm not sure how best to do that, since we are testing for a negative activity. See comments on https://www.pivotaltracker.com/story/show/103541696
**Testing**: since the intended non-dev behavior is for delayed jobs to be executed very quickly, it can be difficult to test this under our CF environments. If you wanted to QA this in dev environment, you could generate email and then check the dashboard to verify that the reporting SQL correctly finds the pending jobs. Otherwise, to QA in a CF environment, generate email in any common way and verify that there are no regressions. In practice the `/admin` UI …
=> [Delivers #102133698] delayed job queue visibility

doc/team_practices.md
* Stories that are not actionable should be moved to icebox
* Reference: https://18f.slack.com/archives/cap/p1446062132000076
=> Add info on blocked stories to Team Practices doc

app/models/ncr/work_order.rb, db/migrate/20151028234110_add_defaults_to_ncr_work_orders.rb, db/schema.rb
* Add DB constraint rather than setting in a callback
=> Add defaults to DB for boolean NCR::WorkOrder fields

app/admin/job.rb
Was getting this when starting the app:
```
DEPRECATION WARNING: Active Admin: using `action_item` without a name is deprecated! Use `action_item(:edit)`. (called from action_item at /Users/aidanfeldman/.rvm/gems/ruby-2.2.3/bundler/gems/activeadmin-470817d8b43b/lib/active_admin/dsl.rb:92)
DEPRECATION WARNING: Active Admin: using `action_item` without a name is deprecated! Use `action_item(:edit)`. (called from action_item at /Users/aidanfeldman/.rvm/gems/ruby-2.2.3/bundler/gems/activeadmin-470817d8b43b/lib/active_admin/dsl.rb:92)
DEPRECATION WARNING: Active Admin: using `action_item` without a name is deprecated! Use `action_item(:edit)`. (called from action_item at /Users/aidanfeldman/.rvm/gems/ruby-2.2.3/bundler/gems/activeadmin-470817d8b43b/lib/active_admin/dsl.rb:92)
```
There …
=> fix deprecation warning for DelayedJob actions in ActiveAdmin

app/models/proposal.rb, lib/incoming_mail/handler.rb, spec/features/incoming_mail_handler_spec.rb, spec/models/proposal_spec.rb
Story: https://www.pivotaltracker.com/story/show/106855394
Removes authorization backdoor where a non-subscriber could add themselves as an observer by replying to an email mentioning a request. The rules were clarified in a24118d9012c2bd53af40997907fa9dbd9fc88ea
**Testing**: this can be tested by sending an email to the `*inbox@c2.18f.gov` address from a non-subscriber. The email subject should have the same Request ID pattern as any legit email from the system. The most straightforward way to do this would be:
* create new request
* reply to the generated announcement email, cc'ing a non-subscriber who is a user in the system
* reply from the non-subscriber's email account
=> [Delivers #106855394] close authorization backdoor for non-subscriber email reply

app/decorators/hash_diff_decorator/base.rb, app/models/ncr/work_order.rb, spec/decorators/hash_diff_decorator_spec.rb, spec/models/ncr/work_order_spec.rb
Story: https://www.pivotaltracker.com/story/show/99135662
* render nil and empty strings explicitly in HashDiff so it is clear what the original value was
=> [Delivers #99135662] improve HashDiff for empty original values

app/mailers/concerns/proposal_conversation_threading.rb, spec/mailers/communicart_mailer_spec.rb
Story: https://www.pivotaltracker.com/story/show/107239306
This makes the reply-to address of each email include the proposal `public_id` so that OOO auto-replies are unique-per-request rather than unique-per-requester.
To test, trigger any email and check that the reply-to address contains the request public_id.
=> [Delivers #107239306] improve OOO comment coverage

db/migrate/20151103223107_drop_properties.rb, db/schema.rb
Story: https://www.pivotaltracker.com/story/show/89851836
Final clean up for deprecated Properties table. Related code was removed several months ago in dd5b0b5c56b28b44fa5d5effed7967f44294dde1
DB snapshots since then have backed up data.
=> [Delivers #89851836] drop Properties table

app/views/proposals/index.html.erb, app/views/shared/formatter/_review_status.html.haml
To QA: visit proposals index and see that the "status" column is HTML, not non-interpreted markdown.
Story: https://www.pivotaltracker.com/story/show/107421592
=> [Delivers #107421592] Use HAML instead of markdown in view partial

app/decorators/hash_diff_decorator/base.rb, spec/decorators/hash_diff_decorator_spec.rb
Story: https://www.pivotaltracker.com/story/show/107501786
Treat `Fixnum` numeric objects like integers, not floats.
You should see this in action on the `/proposals/:id/history` endpoint. Id values and other integers should display as `123` (integers) not as `123.00` (floats).
=> [Delivers #107501786] hashdiff numerics

app/decorators/hash_diff_decorator/base.rb, spec/decorators/hash_diff_decorator_spec.rb
Story: https://www.pivotaltracker.com/story/show/107393700
This fixes a regression introduced in #751 where the `empty?` method was being called on an object w/o that method.
=> [Delivers #107393700] /history endpoint returns 500 error

app/controllers/observations_controller.rb, app/policies/observation_policy.rb, app/views/proposals/show.html.haml, spec/features/observer_spec.rb
Story: https://www.pivotaltracker.com/story/show/104744396
Enables **Delete** button for Observers to remove themselves from a Proposal.
Testing:
1. Login as User A
1. Create Proposal
1. Add User B as an Observer
1. Login as User B
1. Navigate to the Proposal
1. Click Delete next to User B's name
1. Verify success message says "Deleted Observation for {Proposal.public_id}"
=> [Delivers #104744396] allow Observer to delete themselves from a Proposal

app/controllers/proposals_controller.rb, app/helpers/communicart_mailer_helper.rb, app/mailers/communicart_mailer.rb, app/views/communicart_mailer/cancellation_email.html.haml, app/views/communicart_mailer/on_observer_added.html.haml, app/views/communicart_mailer/on_observer_added.text.erb, lib/dispatcher.rb, spec/lib/dispatcher_spec.rb, spec/mailers/communicart_mailer_spec.rb
* Include reason if there is one
* Story: https://www.pivotaltracker.com/story/show/101131916
To QA: 
scenario 1:
create a proposal with an approver with a non-pending approval status (aka - approver knows about proposal)
cancel the proposal as a requester WITH a reason
email to approver SHOULD include the reason
=> Include cancellation reason in email

Gemfile, Gemfile.lock, spec/spec_helper.rb
I've used WebMock in a bunch of other projects, and it's really useful to ensure that you're not accidentally making calls to an external API (or SMTP, etc.) from the test suite. The [discussion](https://18f.slack.com/archives/cap/p1446842150000127) around API calls to MyUSA reminded me of this.
=> ensure no calls to external sites are made from tests

spec/controllers/ncr/work_orders_controller_spec.rb, spec/factories/ncr/work_orders.rb, spec/factories/proposals.rb, spec/factories/users.rb, spec/features/client_slug_authz_spec.rb, spec/features/inactive_users_spec.rb, spec/features/ncr/work_orders/approver_edit_spec.rb, spec/features/ncr/work_orders/comment_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/edit_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/ncr/work_orders/show_spec.rb, spec/features/observer_spec.rb, spec/helpers/ncr/work_orders_helper_spec.rb, spec/lib/dispatcher_spec.rb, spec/lib/query/proposal/listing_spec.rb, spec/models/ncr/work_order_spec.rb, spec/policies/ncr/work_order_policy_spec.rb, spec/services/proposal_update_recorder_spec.rb
Story: https://www.pivotaltracker.com/story/show/107603900
Internal refactor to make User factory default to `client_slug: nil`
This makes our tests not assume `ncr` by default.
Opened in response to https://github.com/18F/C2/pull/772#discussion_r44179509
=> [Delivers #107603900] User factory client_slug now defaults to nil

app/models/user.rb, config/initializers/omniauth.rb, spec/features/link_to_new_proposal_spec.rb, spec/requests/set_user_after_login_spec.rb
Story: https://www.pivotaltracker.com/story/show/87947800
If the User has configured MyUSA to share first and last name, the app will now use those values to populate the local User record.
Testing:
1. Logout of app
1. Logout of https://alpha.my.usa.gov/
1. Login to app
1. On MyUSA confirmation page, select **yes** for first and last names.
1. Confirm name is populated on app login
=> [Delivers #87947800] myusa first last

app/models/proposal.rb, app/models/user.rb, lib/dispatcher.rb, spec/lib/dispatcher_spec.rb, spec/models/proposal_spec.rb
Story: https://www.pivotaltracker.com/story/show/107609788
Do not send attachment notification emails to proposal delegates, even if they relate to the currently actionable approval/step.
Testing guidelines are listed in the Story (link above).
=> [Delivers #107609788] exclude Delegates from attachment notifications

doc/developer_onboarding.md, doc/production.md
* Most updated docs are now at docs.cloud.gov
* See convo at https://18f.slack.com/archives/cloud-gov-support/p1447700999000073
=> Update CF docs links

app/admin/user.rb, spec/features/active_admin_spec.rb
Story: https://www.pivotaltracker.com/story/show/107777486
`/admin/` section should not have a Delete User button.
=> [Delivers #107777486] disable Delete User action in /admin/users

app/controllers/ncr/work_orders_controller.rb, app/controllers/use_case_controller.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/post_approval_modification_spec.rb
Story: https://www.pivotaltracker.com/story/show/108012382
Story: https://www.pivotaltracker.com/story/show/97035674
use `flash.now` to make sure warning appears only on the current page
To test this, attempt to modify an already fully-approved NCR request. On the edit page, there should be a warning about attempting to modify the request. When you click "Discard Changes" at the bottom of the page, the flash warning should not appear on the request view page.
=> [Delivers #108012382] fix persistent flash message

db/migrate/20141031215718_add_flow_to_approval_groups.rb, db/migrate/20150319212424_migrate_ncr_to_models.rb
I wasn't able to run migrations on an empty database. These
modifications will make it easier for developers to jump into
the project my making the migrations work from scratch.
=> Fixes database migrations to run on empty database

app/admin/user.rb
because `/admin/users` endpoints create filters for all relationships by default, page load time was 10+ seconds every time. This gets it down in the 1-2 second range.
=> optimize /admin/users endpoint to not load filters for all relationships

app/models/gsa18f/procurement.rb, app/policies/gsa18f/procurement_policy.rb, app/views/proposals/show.html.haml, spec/features/18f_procurement_spec.rb, spec/features/cancel_spec.rb, spec/features/ncr/work_orders/show_spec.rb, spec/models/gsa18f/procurement_spec.rb, spec/policies/gsa18f/procurement_policy_spec.rb
Story: https://www.pivotaltracker.com/story/show/108372360
This PR adds a couple methods to distinguish a *purchaser* from another kind of approver, and amends the gsa18f policy to allow non-purchaser approver on gsa18f procurement to cancel the proposal.
Testing:
* Verify who the gsa18f purchaser user is. That is controlled via Roles so you should be able to manage/view it from the `/admin` UI. Verify you will be able to login as that user.
* Create a gsa18f procurement
* Login as the approver and verify that you can cancel the procurement
=> [Delivers #108372360] 18f approver can cancel

manifest.yml
there's a bug in the cf-blue-green deploy that gets a false positive match based on the current ELK naming convention. I have re-named all our ELK services to workaround that bug.
=> rename elk services to workaround blue-green deploy bug

app/models/proposal.rb, app/policies/gsa18f/procurement_policy.rb, app/policies/ncr/work_order_policy.rb, app/policies/proposal_policy.rb, spec/features/cancel_spec.rb, spec/policies/gsa18f/procurement_policy_spec.rb, spec/policies/proposal_policy_spec.rb
* Via regular UI
* To test:
log in as admin
visit proposal that you are not a requester or approver for (will have
to find via rails console since it will not be in your dashboard)
you should see option to cancel
confirm that you can cancel
- story https://www.pivotaltracker.com/story/show/108485468
=> [Delivers #108485468] User with admin role can cancel any request

app/mailers/concerns/proposal_conversation_threading.rb, app/models/ncr/work_order.rb, app/serializers/ncr/work_order_serializer.rb, config/locales/en.yml, lib/ncr/approval_manager.rb, spec/features/requester_switches_work_order_to_whsc_spec.rb, spec/mailers/communicart_mailer_spec.rb, spec/mailers/concerns/proposal_conversation_threading_spec.rb, spec/models/ncr/work_order_spec.rb, spec/requests/api/ncr/work_orders_spec.rb
* Been working on moving NCR orgs to the database. In the process, I
decided that the relationship betwen `ncr_work_order`s and
`ncr_organization`s should actually be named `ncr_organization` rather
than `organization`. By making this change now, the move to AR will be
smaller
*  In the process of that PR, I also found that the use of I18n for
dealing with email subject logic was confusing. This clarifies that
logic and puts it under test at the unit level
=> Refactor to prep for moving organizations to DB

app/controllers/client_data_controller.rb, app/controllers/gsa18f/procurements_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/helpers/application_helper.rb, app/models/concerns/client_data_mixin.rb, app/models/concerns/client_data_type.rb, app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, app/views/gsa18f/procurements/_form.html.haml, app/views/ncr/work_orders/_form.html.haml, spec/lib/services/client_data_creator_spec.rb
* Previously, used `UseCase`, `model_instnace`, and `proposal_delegate`
* Move to variations of `client_data` everywhere
* Story: https://www.pivotaltracker.com/story/show/101710542
=> [Delivers #101710542] Unify naming of client-specific code

app/models/concerns/client_data_mixin.rb, app/models/proposal.rb, app/policies/proposal_policy.rb, spec/policies/ncr/work_order_policy_spec.rb
Story: https://www.pivotaltracker.com/story/show/109396552
To test:
* create a NCR Work Order
* login as a Tier 1 approver delegate (see #823 for testing detail tips)
* after approving the request, the delegate user should be able to modify the proposal (has a big blue Modify Request button on the /proposals/:id page)
=> [Delivers #109396552] treat step.completer as an approver in proposal policy

app/models/user.rb, spec/features/admin_spec.rb, spec/models/user_spec.rb
Story: https://www.pivotaltracker.com/story/show/108469926
Testing:
* visit `/admin`
* any time a user record is displayed, it should use the name+email if both are defined, otherwise just email
=> [Delivers #108469926] add User.display_name method for active_admin to use

app/admin/approval_delegate.rb
* See https://github.com/18F/C2/pull/848
To test:
* Log in as admin
* View `admin/approval_delegates`
* Confirm that you see name and email address for assignees / assigners
=> Use `display_name` for ApprovalDelegates in admin

doc/setup.md
Ruby version in setup doc file was different from the version in the actual Gemfile, so I updated it in the docfile.
=> updated ruby version

script/bootstrap
No such file or directory error is thrown by delayed_job command when trying to start the server
=> make sure C2/tmp/pids exists to prevent ./script/start error

lib/clock_tasks.rb
Story: https://www.pivotaltracker.com/story/show/109530778
This doesn't fix the problem, but it should fix the reporting of the problem as step zero.
Story should stay open (un-finished) even after this is merged.
=> [Delivers #109530778] fix new relic report tracking

app/models/gsa18f/procurement.rb, spec/models/gsa18f/procurement_spec.rb
* To QA:
log in as an 18F user
visit new procurement form
see 2 new purchase type options: hardware and other
* Story: https://www.pivotaltracker.com/story/show/109362998
=> [Delivers #109362998] Add 2 more purchase types for 18F

spec/features/attachment_spec.rb, spec/features/ncr/work_orders/create_approver_options_spec.rb, spec/features/ncr/work_orders/create_requires_login_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/create_with_attachment_spec.rb, spec/features/ncr/work_orders/create_with_different_expense_types_spec.rb, spec/support/feature_spec_helper.rb
* Previously, we turned JS on for some and off for others
* The problem with this was that we were not mirroring reality --
selectize changes the values for certain fields, so params were being
set differently when javascript was turned off
* This PR moves on JS for all feature specs for creating a work order
* Adds helper methods for setting and viewing values for selectize fields
=> Turn on JS for feature specs using selectize

app/controllers/concerns/token_auth.rb, app/policies/proposal_policy.rb, spec/controllers/proposals_controller_spec.rb
Story: https://www.pivotaltracker.com/story/show/109547738
Test:
* Create NCR work order with approver that delegates to 2 or more other users
* Using the Approve link in the email that is sent, approve the work order as one of the delegates. The Proposal should approve as usual.
* Using the same Approve link in a different browser, try to use the link as the other delegate. Instead of an authorization error, you should be redirected to the proposals/:id link and get an error message that "A response has already been logged for this proposal"
=> [Delivers #109547738] catch policy exception for already-approved proposal

app/controllers/proposals_controller.rb, app/policies/proposal_policy/scope.rb, lib/query/proposal/clauses.rb, lib/query/proposal/listing.rb, lib/query/proposal/versions.rb, lib/tabular_data/container.rb, spec/lib/query/proposal/clauses_spec.rb, spec/lib/query/proposal/versions_spec.rb
* Privatize methods that are unused outside of class to minimize API of
objects
* Prep for https://www.pivotaltracker.com/story/show/105014352 (uses
`Versions` query object, which I was having a hard time wrapping my
head around with previous organization)
=> Refactor query objects

app/models/ncr/work_order.rb, spec/features/ncr/work_orders/create_approver_options_spec.rb
* Same logic lives in `Ncr::Mailboxes`
* Part of https://trello.com/c/smBumRFX/38-move-non-ncr-specific-logic-out-of-workorders
=> Remove duplicate mailbox methods from Ncr::WorkOrder

app/models/concerns/client_data_mixin.rb, app/models/concerns/fiscal_year_mixin.rb, app/models/concerns/purchase_card_mixin.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, app/services/fiscal_year_finder.rb, lib/client_summarizer.rb, lib/clock_tasks.rb, spec/lib/client_summarizer_spec.rb, spec/services/fiscal_year_finder_spec.rb
* Part of moving NCR-specific logic out of Ncr::WorkOrder
* Also removes duplication
https://trello.com/c/smBumRFX
=> Move `for_fiscal_year` method into mixin

app/controllers/client_data_controller.rb, app/decorators/proposal_decorator.rb, app/helpers/mailer_helper.rb, app/models/concerns/client_data_mixin.rb, app/models/proposal.rb, app/serializers/proposal_serializer.rb, app/services/client_data_creator.rb, app/views/proposals/show.html.haml, app/views/shared/_email_status.html.erb, db/migrate/20151215230732_remove_flow_from_proposals.rb, db/schema.rb, doc/api.md, lib/dispatcher/class_methods_mixin.rb, spec/decorators/proposal_decorator_spec.rb, spec/factories/gsa18f/procurements.rb, spec/factories/ncr/work_orders.rb, spec/factories/proposals.rb, spec/features/display_status_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb, spec/features/parallel_approvals_spec.rb, spec/lib/dispatcher_spec.rb, spec/lib/linear_dispatcher_spec.rb, spec/models/concerns/step_manager_spec.rb, spec/models/proposal_spec.rb, spec/requests/api/ncr/work_orders_spec.rb, spec/support/shared_examples/client_data.rb
* We do not use this concept for serial or parallel steps
* Steps of type `Serial` or `Parallel` are added to a proposal, instead
* Removing at suggestion of https://github.com/18F/C2/pull/835#issuecomment-161836392
=> Remove `flow` from proposals

spec/features/ncr/work_orders/requester_edit_spec.rb
This "Discard Changes" spec keeps breaking when run locally because testing `current_path` doesn't use Capybara's waiting mechanisms to ensure that `click_link` is done. But good news! [There's now a waiting matcher for current_path](https://github.com/jnicklas/capybara/pull/1567), so this fix uses that.
=> Fix path-checking spec by using a waiting matcher

app/models/approval_delegate.rb, app/models/proposal.rb, spec/policies/proposal_policy_spec.rb
Fixes the bug wherein purchase delegates weren't getting the "mark as purchased" button, per https://trello.com/c/ymdHIPMF .
(and no I can't spell 'assignee' either).
=> Purchase delegate bugfix

app/decorators/ncr/work_order_decorator.rb, app/views/report_mailer/daily_budget_report.text.erb, lib/ncr/reporter.rb, spec/decorators/ncr_work_order_decorator_spec.rb, spec/lib/ncr/reporter_spec.rb, spec/models/ncr/work_order_spec.rb, spec/models/proposal_spec.rb
* We already have the concept of `currently_awaiting_approvers` in
StepManager
* Part of https://trello.com/c/smBumRFX
=> Move `current_approver` logic out of Ncr::WorkOrder

spec/features/return_to_spec.rb
since specs run in a random order, it's hard to know if we've added the necessary `elasticsearch: true` tag to all relevant specs. Let's leave this PR open and add to it as CI reveals more that need it.
=> add elasticsearch:true tag to specs that require it

app/controllers/auth_controller.rb, app/views/auth/failure.html.haml, config/routes.rb, spec/features/login_spec.rb
Trello: https://trello.com/c/yp6uuxcF
Note that I was not able to duplicate the exact scenario reported in the Trello card, though I have hit that 404 page before via that same URL. This PR at least gets rid of the 404, and should (hopefully) smooth out the UX till we can figure out why it is getting triggered.
=> myusa failure sometimes redirects to a non-existent endpoint

Gemfile, Gemfile.lock
Should solve the problem brought up [in Slack](https://18f.slack.com/archives/cap-public/p1454536738000051):
> When running $ ./script/bootstrap, the port for Git is blocked by the firewall team here at [agency]
> 
> "Retrying git clone 'git://github.com/activeadmin/activeadmin.git' "/usr/local/rvm/gems/ruby-2.2.3/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git' "/usr/local/rvm/gems/ruby-2.2.3/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet` in directory /root/C2 has failed."
> 
> So in general, I can get to ports 80, 443... but even 21 (ftp) is …
=> switch to downloading activeadmin via HTTPS

config/initializers/elasticsearch.rb, lib/expired_record_cleaner.rb, spec/lib/query/proposal/search_spec.rb, spec/support/es_spec_helper.rb
* To prevent unnecessary output during spec runs
=> Wrap es output in check for `ES_DEBUG` var

spec/rails_helper.rb, spec/support/database_cleaner.rb
* Easier to read / tweak
* We want this in all specs, not just specs the include `rails_helper`
(even though all of our specs require it now)
=> Move database cleaner setup to its own file

spec/controllers/proposals_controller_spec.rb, spec/features/reports_spec.rb, spec/queries/proposal_search_query_spec.rb, spec/support/es_spec_helper.rb
Trello: https://trello.com/c/8nuPwMap
ES server may fail to sync immediately in CI environment, causing spurious errors. Can't always test for this precisely during feature tests, but in all others, wrap in a try/catch and re-try if ES-specific error is caught.
=> add es_execute_with_retries method

app/views/gsa18f/_proposal_mail.html.haml
Trello: https://trello.com/c/46RtuI2C
This has the added benefit of making it easier to refactor all emails now that the client-specific templates are virtually identical.
=> align GSA18F email with NCR email template

app/helpers/mailer_helper.rb, app/mailers/application_mailer.rb, app/views/cancellation_mailer/cancellation_confirmation.html.haml, app/views/cancellation_mailer/cancellation_email.html.haml, app/views/cancellation_mailer/proposal_fiscal_cancellation.html.haml, app/views/cancellation_mailer/proposal_fiscal_cancellation.text.erb, app/views/layouts/mailer.html.erb, config/locales/mailers/en.yml, lib/mail_previews/cancellation_mailer_preview.rb, spec/mailers/cancellation_mailer_spec.rb
* Add preview for all cancellation mailers
* Minor: include helper in mailer because `property_to_s` method was
previously undefined
* Trucking along on https://trello.com/c/xvL5TN7d
=> Move cancellation email text to I18n

doc/import_users.md, lib/tasks/import_users.rake
Hi C2 team!  We're trying to help update documentation that references the `data-private` repo as that has been deprecated in favor of the `team-api.18f.gov` repo.  I've created this PR to account for the changes needed in your documentation.
This changeset updates the instructions for importing users to reflect recent changes with the Team API.  The `data-private` repository has been deprecated and the team information is now found in the `team-api.18f.gov` repository.  This update is in reference to https://github.com/18F/team-api.18f.gov/issues/169
If you have any questions, please reach out to the practices team in the #hub Slack channel!
=> Update instructions for importing user information

app/assets/javascripts/enable_popovers.js.coffee, app/views/ncr/work_orders/_form.html.haml, config/locales/helpers/en.yml, config/locales/simple_form.en.yml, spec/features/ncr/work_orders/create_spec.rb
* Use old tooltip style
* Trigger on hover rather than click
* https://trello.com/c/s60xLbnD/28-as-a-user-i-can-read-about-direct-pay-so-that-i-know-whether-or-not-to-indicate-direct-pay-when-making-a-request
=> Add tooltip for direct pay

app/admin/proposal.rb, app/models/concerns/client_data_mixin.rb, app/models/concerns/searchable.rb, app/models/ncr/work_order.rb, app/models/proposal.rb, spec/models/ncr/work_order_spec.rb, spec/models/test/client_request_spec.rb, spec/queries/proposal_search_query_spec.rb
Now that NCR uses foreign keys rather than strings for related organization, searches for org code fail. This PR fixes that.
trello: https://trello.com/c/a6SjKfiH
Also included:
* zero downtime for rebuilding the Proposals index
* re-index a single Proposal via the /admin UI
=> search for associated records

db/chores/ncr_work_order_organization_reassigner.rb, spec/db/chores/ncr_work_order_organization_reassigner_spec.rb
If you were running this migration in a world where the NCR work order
approving official is not yet a relation, the validation will fail, but we
want the update to happen anyway.
Fixes https://trello.com/c/XSbWulQS/166-update-migration-to-not-fail
Paired with @jessieay
=> Fix org-reassigner migration to not run AR validations

app/assets/stylesheets/home.scss
I know I saw a support ticket for this, could not find a trello card.
just happened to me on dev. simple CSS bug.
=> add css class fix for login alert

app/views/observer_mailer/proposal_complete.html.haml, app/views/proposal_mailer/proposal_complete.html.haml, app/views/step_mailer/proposal_notification.html.haml, config/locales/mailers/en.yml
Accidentally mixed up two:
- https://trello.com/c/k344wvcO/124-3-email-conversion-requester-request-authorized
- https://trello.com/c/d6Pnezlx/155-17-email-conversion-observer-request-authorized
=> Create proposal_complete email

app/views/observer_mailer/observer_removed_confirmation.html.haml
https://trello.com/c/9wJjCoK0/153-22-email-conversion-observer-removed-as-an-observer#action-56e096145412ea2f0ebd92fe
=> Setup the Observer Removed Confirmation email

Gemfile, Gemfile.lock
This can be merged as long as we're comfortable with the slightly slower run time. No testing/measuring has been done on how this affects run time.
This is to try and address the periodic failures at CircleCI.
=> Turn off parallel circleci

app/mailers/observer_mailer.rb, app/models/dispatcher.rb, app/views/observer_mailer/observer_removed_confirmation.text.erb, app/views/observer_mailer/observer_removed_notification.html.haml, app/views/observer_mailer/observer_removed_notification.text.erb, config/locales/mailers/en.yml, lib/mail_previews/observer_mailer_preview.rb, spec/mailers/observer_mailer_spec.rb
* Rename to `observer_removed_notification` to stay consistent with
naming of other emails ('confirmation' is for actions you yourself
triggered)
https://trello.com/c/7venq0xj/224-22-round-3
=> Updates to email 22

app/decorators/proposal_decorator.rb, app/helpers/mailer_helper.rb, app/helpers/proposals_helper.rb, app/views/mail_shared/approval/_chain.html.haml, app/views/observer_mailer/proposal_complete.html.haml, app/views/observer_mailer/proposal_complete.text.erb, app/views/proposal_mailer/emergency_proposal_created_confirmation.html.haml, app/views/proposal_mailer/proposal_complete.html.haml, app/views/proposal_mailer/proposal_complete.text.erb, app/views/proposal_mailer/proposal_updated_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.html.haml, app/views/proposal_mailer/proposal_updated_no_action_required.text.erb, app/views/proposal_mailer/proposal_updated_while_step_pending.html.haml, app/views/step_mailer/proposal_notification.html.haml, app/views/step_mailer/proposal_notification.text.erb, app/views/step_mailer/step_reply_received.html.haml, app/views/step_mailer/step_reply_received.text.erb, config/locales/mailers/en.yml, spec/decorators/proposal_decorator_spec.rb, spec/helpers/mailer_helper_spec.rb
* If next step is approval, status is "pending approval"
* If next step is purchase, status is "pending purchase"
Looks like this in emails:
https://trello.com/c/wSUB35wL/237-update-status-in-emails
=> Include next step type when proposal is "pending"

app/controllers/proposals_controller.rb, app/mailers/cancelation_mailer.rb, app/models/dispatcher.rb, app/views/cancelation_mailer/cancelation_confirmation.html.haml, app/views/cancelation_mailer/cancelation_confirmation.text.erb, app/views/cancelation_mailer/cancelation_notification.html.haml, app/views/cancelation_mailer/cancelation_notification.text.erb, spec/mailers/cancelation_mailer_spec.rb, spec/models/dispatcher_spec.rb
* Previously, only the requester could cancel a proposal
* Now approvers can also cancel a proposal
* So we must pass canceler to mailers to know who gets what email
https://trello.com/c/tsQSwMvz
=> Pass canceler to cancelation mailer methods

app/mailers/application_mailer.rb, app/mailers/cancelation_mailer.rb, app/mailers/comment_mailer.rb, lib/mail_previews/cancelation_mailer_preview.rb, spec/mailers/proposal_mailer_spec.rb
* Keeping as-is until further research is conducted
https://trello.com/c/4AV6FKVn/227-subject-lines-in-emails
for NCR it looks like this:
for 18F it looks like this:
=> Revert subject lines back to old version

app/controllers/attachments_controller.rb, app/decorators/attachment_decorator.rb, app/mailers/concerns/proposal_conversation_threading.rb, app/models/dispatcher.rb, app/services/ncr/reporter.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, config/initializers/env_check.rb, config/initializers/mailer.rb, spec/models/dispatcher_spec.rb, spec/rails_helper.rb, spec/support/shared_examples/proposal_email.rb
* Link to `files` anchor when user clicks attachment in email
* Do not send attachment email to person who added attachment
https://trello.com/c/oCt6aVdo
https://trello.com/c/v24zGByh
=> Attachment mailer updates

app/controllers/observations_controller.rb, app/mailers/observer_mailer.rb, app/models/dispatcher.rb, app/views/observer_mailer/observer_removed_notification.html.haml, spec/mailers/observer_mailer_spec.rb
* Since observation is deleted after mailer, was getting `nil` errors
https://trello.com/c/lHiEURiD
=> Pass user, not observation, to observer removed email

app/models/dispatcher.rb, app/models/steps/individual.rb, lib/mail_previews/cancelation_mailer_preview.rb, spec/features/gsa18f/procurements/approve_spec.rb, spec/features/proposals/approve_spec.rb, spec/models/dispatcher_spec.rb
* Was not sending to NCR requester / observers because the former
"pending" status was cached (fixed by reloading proposal)
* Was not sending to 18F for same reason.
* Was sending `step_complete` email to 18F for same reason too
* One tweak: sending email to all observers rather than
`active_observers`
https://trello.com/c/PMcncLYA
https://trello.com/c/ri0POaQW
=> Update logic around `proposal_complete` emails

app/decorators/attachment_decorator.rb, config/locales/mailers/en.yml
https://trello.com/c/iENa45O8/250-attachment-button-when-attachment-is-pdf-styling-is-a-bit-off
=> attachment button (when attachment is PDF) styling is a bit off

app/models/dispatcher.rb, spec/features/gsa18f/procurements/approve_spec.rb, spec/features/ncr/work_orders/approve_spec.rb
* Was not sending in production because `proposal` was not reloaded
* Wrote feature specs for each use case to confirm behavior
* Always good to actually send emails :)
https://trello.com/c/CP1x6c5e
=> Send email to requester when final step is completed

app/views/observer_mailer/observer_added_notification.html.haml, app/views/observer_mailer/observer_added_notification.text.erb, spec/mailers/observer_mailer_spec.rb
* Previously showed "Reason: " when no reason
https://trello.com/c/jYGT0z5J
=> Do not show "reason" text when no reason for adding observer

config/clock.rb
fix bug at cloud.gov where clockwork tasks fail to execute rake tasks
=> explicitly load rask tasks within clockwork config

config/initializers/mailer.rb
* Previous setup was adding `scheme` to URL as a query param
eg: https://cap.18f.gov/proposals/2267?scheme=https
now it just goes to an http or https url
=> Set protocol to `https` in production

app/decorators/proposal_decorator.rb, app/views/attachment_mailer/new_attachment_notification.html.haml, app/views/attachment_mailer/new_attachment_notification.text.erb, app/views/comment_mailer/comment_added_notification.html.haml, app/views/comment_mailer/comment_added_notification.text.erb, app/views/observer_mailer/proposal_complete.html.haml, app/views/observer_mailer/proposal_complete.text.erb, app/views/proposal_mailer/emergency_proposal_created_confirmation.html.haml, app/views/proposal_mailer/proposal_complete.html.haml, app/views/proposal_mailer/proposal_complete.text.erb, app/views/proposal_mailer/proposal_updated_needs_re_review.html.haml, app/views/proposal_mailer/proposal_updated_while_step_pending.html.haml, app/views/step_mailer/proposal_notification.html.haml, app/views/step_mailer/proposal_notification.text.erb, app/views/step_mailer/step_reply_received.html.haml, lib/mail_previews/proposal_mailer_preview.rb, spec/models/step_spec.rb
* Remove `display_status` method from ProposalDecorator
* User `detailed_status` instead
https://trello.com/c/oFsbuwoq/266-attachment-email-status-should-be-complete-not-completed-in-header
=> Use lowercase status in attachment / comment emails

app/helpers/mailer_helper.rb, app/mailers/application_mailer.rb, app/mailers/observer_mailer.rb, app/mailers/proposal_mailer.rb, app/mailers/step_mailer.rb, app/views/mail_shared/approval/_chain.html.haml, spec/helpers/mailer_helper_spec.rb
* When attach all images as inline, unused images show as attachments
* In future we can inline but need to be more sophisticated about
logic, shouldn't just inline all images
=> Reference approval chain icons via http

app/models/dispatcher.rb, app/models/ncr_dispatcher.rb, spec/models/ncr_dispatcher_spec.rb
* We already had layout but were never triggering the email!
https://trello.com/c/YkctRfUy/289-emergency-request-email-update-layout-to-match-designs
=> Trigger emergency proposal confirmation when emergency

app/controllers/summary_controller.rb, spec/controllers/summary_controller_spec.rb
Fixes bug where a regular or gateway admin was only seeing one summary because they were also a client admin.
=> Ensure client admins see all summaries if they have other admin roles

doc/production.md, script/deploy
tested successfully on c2-dev and c2-staging
=> switch from cf-blue-green to autopilot for zero downtime deploys

app/decorators/gsa18f/procurement_decorator.rb, app/decorators/ncr/work_order_decorator.rb, app/decorators/proposal_decorator.rb, app/models/gsa18f/procurement_fields.rb, app/models/ncr/work_order.rb, app/models/ncr/work_order_fields.rb, config/locales/decorators/en.yml, spec/models/gsa18f/procurement_fields_spec.rb, spec/models/ncr/work_order_fields_spec.rb
* Was showing as integer rather than string
* Move logic from model -> decorator
https://trello.com/c/YEbcYtjo/255-18f-urgency-showing-as-integer-not-string
=> Fix `urgency` display for 18F procurements

app/models/ncr/organization.rb, spec/models/ncr/work_order_spec.rb, spec/services/ncr/approval_manager_spec.rb
related trello cards:
https://trello.com/c/5F3tGv0X/301-clarify-ncr-ba61-budgetteam-routing
reverts --> https://trello.com/c/4yAps2bL/241-budget-routing-request-any-request-with-a-code-with-p112xxxx-configuration
https://trello.com/c/FJLK6vYZ/118-budget-routing-request
see ticket https://18f.uservoice.com/admin/tickets/146 for original history
=> revert P112xxxx org code match for ba_6x_tier1_team logic

app/admin/proposal.rb, app/admin/step.rb, spec/features/admin_spec.rb
trello: https://trello.com/c/y5c9XvmW/299-add-tests-to-include-request-updates-from-active-admin
* removes the `/admin/proposals/:id/restart` action because confusing
* adds tests verifying behavior of modifying proposals and steps via `/admin` UI
=> Admin tests

app/services/ncr/work_order_reapproval_checker.rb, spec/services/ncr/work_order_reapproval_checker_spec.rb
trello: https://trello.com/c/95DTQOX4/307-reapprovals-a-modification-by-someone-in-budget-tier-1-or-tier-2-should-not-trigger-a-re-approval
QA: 
* full complete a NCR work order
* as a team mate (fellow delegate) of the final budget approver (but *not* the completer), edit the WO.
* verify no re-approval is triggered.
=> re-approval checks teammates as well as completers

Gemfile, Gemfile.lock, app/models/concerns/searchable.rb, app/models/proposal_role.rb, spec/models/proposal_spec.rb, spec/support/database_cleaner.rb
ticket: https://18f.uservoice.com/admin/tickets/184
Proposals are automatically updated in the search index whenever they, or their associated records, change.
Associated observers were not triggering that automatic reindexing.
This PR adds tests for reindexing, and fixes the reindex-on-observation-change bug.
=> Reindex on new observer

app/admin/user_delegate.rb
filters are useless on the `/admin/user_delegates` index page and just slow down response time.
=> turn off sidebar filters on /admin/user_delegates because un-needed and slow

app/assets/javascripts/field_filter.js.coffee, app/assets/javascripts/ncr_work_orders.js, app/models/ncr/work_order.rb, app/views/ncr/work_orders/_form.html.haml, spec/controllers/ncr/work_orders_controller_spec.rb, spec/features/ncr/work_orders/create_spec.rb, spec/features/ncr/work_orders/requester_edit_spec.rb
trello: https://trello.com/c/B8655SyP/253-on-update-cannot-set-request-to-emergency
fixes javascript to actually disable the checkbox on Edit
=> Emergency attribute update

app/decorators/ncr/work_order_decorator.rb
* Was included twice
* https://trello.com/c/kFGFWkEC/368-direct-pay-attribute-code-showing-in-emails
Before:
After:
=> Remove duplicate "direct pay" field

app/models/comment.rb, app/models/dispatcher.rb, app/models/ncr_dispatcher.rb, app/models/proposal.rb, app/services/role_picker.rb, spec/features/comment_spec.rb, spec/features/proposals/complete_spec.rb, spec/models/comment_spec.rb, spec/models/dispatcher_spec.rb, spec/models/proposal_spec.rb, spec/services/proposal_update_recorder_spec.rb, spec/services/role_picker_spec.rb
Changed active_observer to only_observers
Changed activ_observer? to observer_only?
Move comment listeners method to proposal as subscribers_except_future_step_users
Use only_observers where appropriate
https://trello.com/c/3KFzjQCC/261-investigate-use-of-active-observers
=> Clarified how active_observer was being used

app/views/observer_mailer/observer_added_notification.html.haml
Added spacing between header and steps in
observer_added email when no reason present
https://trello.com/c/Xslq7XpY/279-spacing-on-the-added-as-an-observer-with-no-reason-email
=> Add padding when no reason present Obs Email

app/models/concerns/step_manager.rb, app/models/proposal.rb, spec/factories/proposals.rb, spec/models/concerns/step_manager_spec.rb, spec/models/proposal_spec.rb
* Remove duplicate specs (were in both Proposal and StepManager spec
files)
* Move specs to StepManager spec when for method in StepManager
* Use factories in specs rather than initializing objects
=> Move more step-related logic to StepManager concern

README.md
https://chat.18f.gov now supports linking directly to the channel! See https://github.com/18F/chat/pull/5 for more information.
=> link directly to the chat room

app/models/step.rb, spec/models/steps/serial_spec.rb
Having a default scope is problematic,
even more so when using a non unique trait.
Placed scoping on child_step `position ASC`
Added test
see:
http://stackoverflow.com/questions/25087336/why-is-using-the-rails-default-scope-often-recommend-against/25087337#25087337
https://trello.com/c/P5og2Pr8/394-remove-default-scoping-on-steps
=> Removed default scope from Step

lib/c2_version.rb, spec/features/proposals/history_spec.rb, spec/lib/c2_version_spec.rb
papertrail gem stores "before" version, so switch diff logic
to always compare the version record against what comes next,
not what came before. This allows the current live record
to be included in the history.
trello: https://trello.com/c/TC59Hwop/325-look-into-comment-history-vs-admin-history-disrepancy
before:
after:
=> switch diff logic in proposal history.

app/controllers/client_data_controller.rb, app/controllers/gsa18f/procurements_controller.rb, app/controllers/ncr/work_orders_controller.rb, app/models/gsa18f/procurement.rb, app/models/ncr/work_order.rb, spec/factories/gsa18f/procurements.rb
* `fields_for_display` is defined/used in decorators (no longer needed
def in `Ncr::WorkOrder`...was left in accidentally)
* `add_steps` in client-specific controllers was setting up approvers a
second time (called `super` which did setup first time in parent
controller)
=> Remove unused / duplicate client data methods

app/admin/proposal.rb, app/models/proposal.rb, app/models/steps/individual.rb, spec/features/admin_spec.rb, spec/models/proposal_spec.rb, spec/models/steps/individual_spec.rb
trello: https://trello.com/c/OUj6cUMt/317-as-an-admin-i-can-bypass-email-sends-when-updating-the-overall-status-or-specific-step-status-of-a-request-so-that-i-can-perform
Fully completing a Proposal will, by default, send email to all affected subscribers. This adds a second button that completes without notifying.
NOTE that editing the status of a Step directly via the admin UI does **not** generate any email.
=> Admin tasks no email

manifest.yml
after 36 hours, production has climbed from 500MB to 624MB usage.
=> bump up cloud.gov web instance memory use

config/database.yml, config/puma.rb
New JS tests are failing consistently. Increasing thread pool resolves the issues.
=> Expand the Puma thread tool during testing

app/assets/javascripts/details/state/edit_mode.js, app/views/proposals/show_next.html.haml, config/puma.rb, spec/javascripts/state/edit_mode_spec.js.coffee
Use the `.on` on the `#mode-parent` element to control page's edit/view mode.
This is a partial PR. The code is functional on its own and can be merged, but doesnt make sense without the following PRs.
Not yet.
=> New Details Page "Edit mode

app/mailers/proposal_mailer.rb, spec/spec_helper.rb
Fixes [Attachment display in initial email](https://trello.com/c/3MUWkqrh/405-attachment-display-in-initial-email). 
The problem was that we were including an extra icon — the 'attachment' icon — but not referencing it in the email html. The browser then rendered it explicitly like the screenshot shows. Fixed by not including it by calling `add_approval_chain_attachments` directly.
=> Fixes the attachment display

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/notifications.js, app/assets/stylesheets/redesign/_card-action.scss, app/views/layouts/_new_javascript.html.haml, app/views/proposals/details/_action.html.haml, spec/javascripts/details/details_helper.js.coffee, spec/javascripts/details/details_helper.js.js, spec/javascripts/details/shell/c2_spec.js.coffee, spec/javascripts/details/views/notification_bar_spec.js.coffee
Add the ability for a notification bar to be generated. The notification takes three parameters and one optional parameter. 
To use the notification in the `shell/c2`, a user can call the notification event. The notification takes an object containing the four parameters above.
This currently contains test **stubs**. The tests will be written when the styles are implemented next.
=> Add the notification bar functionality

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/modal_card.js, app/views/proposals/details/_action.html.haml, app/views/proposals/details/_modal.html.haml, app/views/proposals/details/modals/_cancel.html.haml, app/views/proposals/details/modals/_save_confirm.html.haml, app/views/proposals/details/modals/_template.html.haml, config/locales/views/en.yml
Add a confirmation modal that confirms changes on request details edits.
=> Add save confirmation notice before processing edit changes

app/views/proposals/details/_attachment.html.haml, app/views/proposals/details/_request_details.html.haml
On proposals in `canceled` state, dont show modify/add attachment buttons.
=> Remove card header buttons on canceled state

app/assets/stylesheets/redesign/_card-approvals.scss, app/views/proposals/details/_approvals.html.haml
Swap out the numerical indicators on approval steps with text/css.
=> Create the option to user text instead of images for approvals

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/action_bar.js, app/assets/javascripts/details/views/details_request_card.js, app/assets/stylesheets/redesign/_card-action.scss, app/views/proposals/details/_action.html.haml, app/views/proposals/details/_request_details.html.haml, app/views/proposals/details/_summary.html.haml, spec/javascripts/details/shell/c2_spec.js.coffee
Edit/save modify button is moved into action bar.
Adding an edit feature into the title bar complicates the user interface. Previously, users would have had two places to go to initiate an "edit", but one place to go to initiate a "save". This makes a design changes to move all modification/save behavior into the action bar.
In the PR, the title bar is still not editable.
=> Move the edit/view trigger into the action bar

app/views/layouts/_notices.html.haml, app/views/layouts/application.html.erb
Create a filter that checks for the "new design" cookie before loading the on page load alert/notice bar.
=> Remove the "on load" alert/notice bar for new details

app/controllers/proposals_controller.rb
After canceling a proposal in the new view, user is redirected to the list view
=> redirect to proposals list view after cancel

app/views/proposals/details/_attachment.html.haml
https://trello.com/c/LUnO7x4Y/495-no-attachment-option-on-completed-request-should-be-able-to-add-attachments-post-completion
=> Attatchment form available on completed requests

app/controllers/observations_controller.rb, spec/features/observer_spec.rb
https://trello.com/c/lJ4xi63K/492-when-removing-the-1st-observer-in-the-observer-list-i-m-taken-back-to-the-requests-page-should-remain-on-the-page-and-be-shown-a
=> Observer redirect only happens when the user is no longer a subscriber

app/views/proposals/details/_action.html.haml
Make the action bar buttons visible for anyone with can_edit access.
https://trello.com/c/5RjPTQQR/494-action-bar-has-no-buttons-on-completed-and-canceled-requests
=> Change the action bar button conditions

app/views/ncr/fields/_emergency.html.haml
Remove the input fields for the emergency checkbox and replace with value.
https://trello.com/c/CIvM5KYu/517-as-a-user-i-am-not-allowed-to-change-a-ba61-request-to-an-emergency-request-after-submitting-it
=> Remove option to change emergency field

app/views/layouts/_notices.html.haml
Code was stopping notices from showing when you had the detail cookie set to new. 
https://trello.com/c/y65WhdCj/493-sign-in-notification-is-displayed-over-page
=> Removed code checking for cookie

app/assets/javascripts/details/views/notifications.js, app/views/layouts/_meta_notice.html.haml
Fix blank notification on page load for details
Unified the naming convention for how the meta tags stored flash messages.
=> New details page/notification fix again

app/controllers/comments_controller.rb, app/controllers/proposals_controller.rb, app/presenters/history_list.rb
On the redesign page, the activity feed shows the approval entry twice
Approvals created two entries in the change log, one updating who was doing the approval, and another that marked the step as complete. This update just filters out the first case since we aren't showing that information in the feed. 
https://trello.com/c/cgIK47ON/519-status-check-marks-not-matching-timeline-steps
=> fixes bug where the same approval shows twice in activity feed

app/views/ncr/fields/_direct_pay.html.haml
Change how direct pay is displayed on front end. 
https://trello.com/c/HSNjpjbh/532-view-details-direct-pay-should-display-yes-no-instead-of-a-disabled-checkbox
=> Update the direct pay display

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/details_request_card.js, app/assets/stylesheets/redesign/_card-request_details.scss
Update the total_price field on 18f proposals, when making frontend updates.
Pass the data response into the success trigger for the proposal update event. If the object contains the amount and quantity fields, then process the total_price value and update.
https://trello.com/c/coe76G0f/565-updating-the-quantity-or-cost-of-a-18f-proposal-item-does-not-update-the-total-price-field-without-refresh
=> Update total value on gsa18f proposals

config/locales/decorators/en.yml
Add decorator field for not to exceed.
https://trello.com/c/GC7bnpI9/571-activity-message-is-not-human-readable-for-updates-to-not-to-exceed-value
=> Fix the work order not to exceed

app/assets/stylesheets/redesign/_card-approvals.scss
Adjust styling of pending steps
Better distinction of events
https://trello.com/c/oX1xyRBN/533-as-a-user-i-understand-next-step-and-future-steps-through-visual-cues
=> Changed pending color to default with 50% opacity

app/views/layouts/_c2_header.html.erb
Remove "missing profile information" message temporarily 
https://trello.com/c/ejtsgNbb/553-deactivate-the-fill-out-your-profile-mesage
=> temporarily disable profile message

app/views/proposals/details/_comment_list.html.haml
The activity feed elements are rendering based on expecting the event elements to be present. For activity events that are created via the command line, some key elements like user_id are missing. When the events element is not complete, dont render any of the activity feed item. This will prevent the blank row with a activity feed dot.
https://c2-dev.18f.gov/proposals/295
https://trello.com/c/im1npxle/563-timeline-dots-are-not-lining-up-with-events
=> Check for event before rendering in the activity feed

spec/controllers/attachments_controller_spec.rb, spec/features/attachment_spec.rb, spec/services/client_data_creator_spec.rb
Local failures are requiring the stubbing of web requests. Updated.
=> Fix local failures that require stubbing of web requests

app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/notifications.js
Prevent potential for multiple notifications to pop up, if the content is the same as last rendered notification.
Change cancel notification text when there is no modifications made to field.
https://trello.com/c/WGKNAzEP/496-when-saving-a-change-to-a-request-the-notification-bar-repeats-multiple-times
=> New details page/prevent duplicate notification

app/models/role.rb
This is a bug I discovered while trying to get the app running on my local machine.
The fix that I used to get it working is laid out in the commit in this PR.
Prior to this commit, running the bootsrap script with `./script/bootstrap email@gsa.gov`, would fail because of a call to the database which had yet to be created.
The issue in particulair was in the Role model:
```ruby
ensure_system_roles_exist if connection.table_exists?("roles")
```
The error message looked like this:
```shell
/Users/jonathan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-ca94d1ccb189/lib/active_admin/error.rb:43:in `rescue in capture': Your file, app/models/role.rb (line 14), caused a database error while Active Admin was loading. This is most common when your database is missing or doesn't …
```
=> Remove call to database connection during bootstrap script

Gemfile, app/assets/javascripts/details/force_ethnio.js, app/views/proposals/details/_top_notification.html.haml
bug where the ethnio screener (when user reverts to the old design) couldn't be closed. 
This resolves that issue.
=> Can now close ethnio screener consistently

app/assets/javascripts/details/shell/c2.js
Update the form with ajax using the `.submit()` function. This tells the browser that the updated form fields are the _new_ fields. This makes sure the browser doesnt flag a "the fields aren't being saved" warning when the user leaves a page.'
We moved away from this `.submit()` method because the success notification gets called twice. To prevent this, the notification generator has a check that looks to see what the last notification created is. If the content is the same, it doesnt render the new one.
=> Update non-turbolink form update

app/controllers/client_data_controller.rb
The error notice on creating a new proposal results in a persistent flash notice. 
This uses the notice into a `flash.now` with our class.
=> Remove the issue around create notification error persistence

app/assets/javascripts/details/shell/c2.js
When a form is changed, the action bar save/cancel buttons are spammed with updates. This creates a condition check to see whether or not the buttons need to be updated. By preventing the DOM from being touched, the application performs much better.
=> Prevent the function for action bar from unnecesarrily running

app/assets/javascripts/details/data/details_save.js, app/assets/javascripts/details/shell/action_bar_bridge.js, app/assets/javascripts/details/shell/c2.js, app/assets/javascripts/details/views/attachment_card.js, app/controllers/client_data_controller.rb, app/views/layouts/_new_javascript.html.haml, spec/javascripts/details/shell/c2_spec.js.coffee
The front-end now sends the form params to the backend for validation. After the validation check, the front-end does a form `submit`. This allows any errors from validation to be properly handled on the front-end, without accidentally updating the `dirrty` fields or getting inconsistent notifications
=> Create validation flow and action bar

app/views/ncr/fields/_expense_type.html.haml
When modifying a current proposal, instead of showing disabled radio buttons
just show the current expense type.
Card: https://trello.com/c/JXHxpEpD/610-only-display-expense-type-of-request-remove-radio-button-and-other-expense-types
=> Show current expense type when editing

app/assets/stylesheets/ncr/_fields.scss
https://trello.com/c/w2PoepWN/608-move-text-below-description-to-be-under-description-or-in-the-form-field
=> show description field label

app/assets/javascripts/details/views/activity_card.js, app/assets/javascripts/details/views/view_helper.js, app/assets/stylesheets/redesign/_basic.scss, app/assets/stylesheets/redesign/_card-activity.scss
The comment box send button can now reinitialize after sending. The button design is also updated to transition between visible/hidden state with a change in opacity. A callback option is now available for button submissions too.
https://docs.google.com/spreadsheets/d/1ZpzCwhExizevhZhS-g3rZQmE9ihXyRv-uGGbjUVCweo/edit#gid=0
https://trello.com/c/Kl6vCjBv/643-fix-regressions-on-comment-box
=> Fix regression around comment box

app/assets/javascripts/details/shell/action_bar_bridge.js, app/assets/javascripts/details/views/attachment_card.js, app/views/gsa18f/fields/_title.html.haml, app/views/ncr/fields/_title.html.haml, app/views/proposals/details/_attachment_list.html.haml, app/views/proposals/details/_observer_row.html.haml
Remove the `form` tag that was used in removing attachment/observers. Replace with JavaScript ajax call, using the `data-delete-url` attribute to target.
Following procedure to make "one form" to rule them all.
=> Replace the form tag in the remove attachment/observer

app/assets/stylesheets/redesign/_card-action.scss, app/helpers/application_helper.rb
Move the logic for sidebar. Change the sidebar view condition to include request details.
=> Sidebar on request details

app/models/steps/approval.rb, app/models/steps/individual.rb, spec/models/proposal_spec.rb, spec/models/steps/approval_spec.rb
* Was causing Micro-purchase requests to not have steps because Alan D
is both the MP requester and Purchaser
* Closes https://rpm.newrelic.com/accounts/921394/applications/5480870/traced_errors/2713dca3-5e58-11e6-9456-f8bc12425498_0_18136?original_error_id=2713dca3-5e58-11e6-9456-f8bc12425498_0_18136
=> Remove `user_is_not_requester` validation from Purchase steps

app/views/gsa18f/_request_details.html.haml
GSA 18f proposal pages are broken when user's beta role is active. This is a fix.
=> Urgent: Fix broken GSA 18f beta mode proposals

app/assets/stylesheets/redesign/_list.scss.erb, app/assets/stylesheets/redesign/_sidebar-nav.scss, app/presenters/tabular_data/column.rb, config/tables/proposals.yml
- Add more CL, Building, and Function code to list
- Change submitted to exact date not relative
- When open, don't darken the rest of the screen
- Maintain a set row height (100px seems to allow for 2 lines of content)
- Row rollover state should be E8E8E8
- Remember last state of users table set-up
- Decrease size of logo
- Ensure divider lines are 1px
- Change color of divider lines to 71737A
- Rollover state for inactive buttons 71737A
- Rollover state for active buttons DBEAF5
- Limit the max width for nav in desktop view
- Increase height of logo box (110px or 1/3 more than height of button)
- Remove rounded corners from sub nav buttons
- Change color to dark grey
- Add rollover state underlined
- Add active for name as bold underlined
- Remove horizontal lines in table
- Remove …
=> Lots of changes from Amber

app/helpers/help_helper.rb, app/views/help/index.html.haml
This does two things
- Hide the new features article from the list of help articles because there isn't content for it yet
- The help articles can be viewed without signing in, so the tracking now checks for a logged in user before attempting to set that variable.
=> Hide new features help

app/controllers/client_data_controller.rb, app/controllers/concerns/token_auth.rb, app/controllers/users_controller.rb
dosen't reload the page after being away for awhile
To recreate, login to a page that triggers an update
new proposal for example,
go to chrome settings, and clear recent history including
cache and cookies.
Return to the page and attempt a patch action,
You will now be returned to the home page of the app instead
of crashing to an error message.
=> Fixes an ungraceful error that occurs when the user

app/assets/stylesheets/redesign/_list.scss.erb, app/views/proposals/show.html.haml, app/views/shared/_table.html.haml
Add the new table layout from proposals#index to the search result page
https://trello.com/c/HCVdy5pl/738-reports-table-legacy-apperance
=> Give legacy reports page the new table design

app/assets/stylesheets/redesign/_sidebar-nav.scss.erb, app/helpers/application_helper.rb, app/views/ncr/_header_links_next.html.haml
When new request or reports is active, change the sidebar styling on the links
=> Setup sidebar active states for new request/reports

app/controllers/comments_controller.rb, spec/features/comment_spec.rb
On the old page adding a comment displayed a "you've added an attachment" message.
Updated message and test to "You've added a comment"
https://trello.com/c/4ljZWuNa/729-message-after-adding-a-comment-is-you-successfully-added-an-attachment
=> Update flash message when adding a comment

app/assets/javascripts/details/views/list/list_view.js, app/assets/stylesheets/redesign/_list.scss.erb, config/locales/decorators/en.yml, spec/features/proposals/index_spec.rb
The filter for list view sidebar buttons uses the `status` column to display/hide. The conditions for hiding were cased on `ncr` status attributes. The conditions are now updated for the `gsa18f` status attributes for pending.
The Pending option for one user was not displaying. This is because the text in the pending area was changed.
https://trello.com/c/iJdSnPAP/786-redesign-pending-navigation-indicates-a-collection-of-requests-but-does-not-contain-any-in-the-body
=> Fix the pending state on the list view

app/assets/javascripts/details/views/list/list_view.js
Add the condition to treat search variable as a regex statement.
https://trello.com/c/iJdSnPAP/786-redesign-pending-navigation-indicates-a-collection-of-requests-but-does-not-contain-any-in-the-body
=> Add the specifier for search condition

.env.example, app/controllers/application_controller.rb, app/models/user.rb, spec/features/login_spec.rb
https://trello.com/c/7qm3GpCQ/484-as-a-user-i-automatically-see-new-detail-page-designs-after-logging-in
After logging in, it checks for `ENV["REDESIGN_DEFAULT_VIEW"]` 
if thats true, and the user is not a beta user, its sets them to a beta user and active.
=> Env sets users to default beta users

app/assets/javascripts/details/views/details_request_card.js, app/decorators/gsa18f/procurement_decorator.rb, app/models/gsa18f/procurement_fields.rb, app/views/gsa18f/fields/_is_tock_billable.html.haml, app/views/gsa18f/fields/_tock_project.html.haml, app/views/gsa18f/procurements/_form_new.html.haml, config/locales/decorators/en.yml, config/locales/simple_form.en.yml, config/tables/proposals.yml, db/migrate/20160921204321_add_billable_to18_f.rb, db/schema.rb, spec/factories/gsa18f/procurements.rb, spec/features/gsa18f/procurements/show_spec.rb
Add new fields for `is_tock_billable` and `tock_project`. These fields are in the new form and in the request fields template.
Added fields to permitted_params and display_fields. 
Conditionally show `tock_project` if `is_tock_billable` is toggled. 
JavaScript checks `is_tock_billable` value and displays human readable term (yes/no).
https://trello.com/c/DZ0KnDco/807-as-a-user-i-can-indicate-that-my-request-is-billable-and-enter-a-billable-tock-project-so-that-my-approvers-know-how-to-handle-t
=> Add tock project reference and billability

app/assets/stylesheets/redesign/_forms.scss, app/models/gsa18f/event.rb, app/views/gsa18f/events/_form_new.html.haml, app/views/gsa18f/fields/_type_of_event.html.haml
WHAT: Add radio select to event type
WHY: https://trello.com/c/G4L6WbB4/823-18f-event-type-of-event-radio-buttons
=> Added radio select to event type

app/assets/stylesheets/redesign/_card-request_details.scss, app/decorators/gsa18f/event_decorator.rb, app/decorators/gsa18f/procurement_decorator.rb, app/views/gsa18f/fields/_pegasys_document_number.html.haml, app/views/proposals/show_next.html.haml, config/locales/decorators/en.yml, config/tables/proposals.yml, db/migrate/20160923023903_add_pegasys_document_number_to18f.rb, db/schema.rb, spec/factories/gsa18f/procurements.rb, spec/features/gsa18f/procurements/show_spec.rb, spec/features/proposals/complete_spec.rb, spec/features/proposals/sort_index_spec.rb
Add the Pegasys Document Number field in the GSA 18f.
Notes: Not added when request is being created. Only appears after request is already paid.
https://trello.com/c/sjwe7RNt/808-as-an-18f-ops-purchaser-i-can-add-a-pegasys-document-number-field-after-marking-a-request-as-purchased-so-that-i-can-easily-atta
=> Add Pegasys Document Number to gsa18f

app/decorators/gsa18f/procurement_decorator.rb, app/models/gsa18f/procurement_fields.rb, app/views/gsa18f/_request_details.html.haml, app/views/gsa18f/fields/_client_billed.html.haml, app/views/shared/_search_form_next.html.haml, config/locales/decorators/en.yml, config/tables/proposals.yml, db/migrate/20160926221019_add_client_billed_to_gsa18f.rb, db/schema.rb, spec/features/gsa18f/procurements/show_spec.rb
As an 18F OPS TEAM MEMBER, I can mark an approved billable request as having an invoice generated (the client was billed) so that I can properly report which requests have been billed (Purchase request)
- Add client_billed attribute
- You have unsaved edits on this field. View edits - Discard
- Display Client has been billed + checkbox on the Modify Request page for requests that are 1) billable and 2) approved. Decide where to enforce #2 (frontend hiding of the checkbox or database level)
- User can save the request with this attribute. Do not show this attribute when creating a new request
- Reporting should allow the query of the client_billed attribute (preset or ability to create one through the search interface)
=> Create a flag for billed tock projects

doc/api.md
It looks like the status was changed from cancelled to canceled, so the API docs should reflect that.
=> Fix 'canceled' status in API docs

app/views/proposals/details/history/_attachment.html.haml, app/views/proposals/details/history/_comment.html.haml, app/views/proposals/details/history/_event.html.haml, app/views/proposals/details/history/_procurement.html.haml, app/views/proposals/details/history/_proposal.html.haml, app/views/proposals/details/history/_step.html.haml, app/views/proposals/details/history/_workorder.html.haml
Fix overflow issue due to table-cell display type.
Example: https://cap.18f.gov/proposals/5770
**Fix**
https://trello.com/c/l5P1QDfF/878-redesign-overflow-layout
=> Add a paragraph wrapper around the content in comment field

app/assets/stylesheets/redesign/_card-summary.scss
Titles were being cut off if they took more than one line
=> Fix really long titles on summary card

app/assets/javascripts/details/views/attachment_card.js
The logic in this file was flawed. On Non GSA event pages `attachment` would come out null, but `attachment !== undefined` is true, because `null != undefined`
Changed to `(attachment !== null && attachment !== undefined)` so it only proceeds if it isn't `null` and it isn't `undefined. `
=> Fixed attachment card logic

app/assets/javascripts/details/views/attachment_card.js, app/views/proposals/show_next.html.haml
Comments and attachments are triggering unfinished form prompt. Fix this by trigging a form submission on the parent form when comment and attachment is complete. This will update the native browser behavior around unfinished form without changing any content on the backend.
Note: No emails or backend activity is triggered when form submit takes place
https://trello.com/c/aONpL13i
=> Fix native browser prompt for unfinished form content

app/views/home/home_redesign.html.haml
This issue comes from the new login changes and only occurs on the redesign. 
https://trello.com/c/PwMsDlXZ/923-login-links-on-home-page-redesign-causing-an-error
=> Updated logins on redesigned home page

app/views/home/home_redesign.html.haml
Removed call directly for home_redesign.css as its already in the app css file
=> Fix css error on redesigned home page

app/models/ncr/work_order.rb, app/services/prepare_display_fields.rb, spec/features/ncr/work_orders/edit_spec.rb
The `not_to_exceed` value was not being updated when user made changes on frontend. Also when values were being reported at `false` during update, they were returning as blank. 
This fixes both of these issues.
=> Fix issue with NCR not_to_exceed

Gemfile.lock, config/brakeman.ignore
- update nokogiri via `bundle update capybara loofah rails-dom-testing roadie xpath`
Here is where Hakiri found a `WEAK` confidence SQL injection warning:
https://github.com/18F/C2/blob/master/app/models/concerns/proposal_steps.rb#L19
The WHERE clause of the query comes from another class, but is static in nature:
https://github.com/18F/C2/blob/master/app/services/proposal_services.rb#L15
I don’t see how this code could be used for SQL injection, which supports Hakiri’s weak confidence.
To silence the warning I tried to sanitize the query various ways using `ActiveRecord::Base.sanitize`.  Each attempt made Hakiri happy but broke tests.
Because there doesn’t seem to be any risk of SQL injection here I added a brakeman exception to the …
=> Silence hakiri etc to pass build

config/initializers/konacha.rb
This lets the test suite finish, but still displays the errors encountered.
It doesn't fix any errors, but at least displays them.
docs: https://github.com/teampoltergeist/poltergeist#customization
=> Configure poltergeist to continue on JS errors

app/models/attachment.rb, spec/features/attachment_spec.rb, spec/features/gsa18f/events/create_spec.rb
This adds content type checking for uploaded attachments using Paperclip's [security validations](https://github.com/thoughtbot/paperclip#security-validations).
The list of file types is based on the types of files that past users have uploaded, so there shouldn't be any noticeable difference for users.
=> Specify allowed content types for attachments

config/application.rb
Previously, CORS was permitted for all resources. This should limit it to just API calls, which are the only ones that should require CORS.
=> Limit CORS to API routes

app/models/attachment.rb
30 MB is around 5 MB larger than the largest two uploaded in the past, but I'd be happy to reduce it for the future.
=> Limit attachment size to 30 MB

app/credentials/email_credentials.rb, config/environments/production.rb
So that it's easier to move from MailChimp/Mandrill to Amazon SES (#1663), or to any other mail service, this moves more config into the CF service.
Note that this changes our default `From:` domain from `18f.gsa.gov` to `18f.gov`, purely because it's easier to add Amazon SES to that domain.
=> Extract mail config

README.md
Since the CAP Public channel is no longer listed
=> Remove chat.18f.gov link
